### ISSUE TITLE
Python绑定要自己写吗？如果用命令行有办法从标准输入读取吗？

### ISSUE THREAD

**Issue by rexdf** [BYVoid/OpenCC#111]
因为需要频繁调用，不停写入临时文件肯定不是办法。为何为没有一个绑定好的pypi包？ 而且是C++写的，要是是纯的C就好办得多了。

**Comment by rexdf** [comment]
也许我自己写个纯python的就好了，只借用下字典……

**Comment by Quotation** [comment]
Python调用很简单，一行代码，封装个函数：

```
from subprocess import Popen, PIPE

def chs2cht(chs):
  return Popen(['opencc'], stdout=PIPE, stdin=PIPE).communicate(chs)[0][:-1]

print chs2cht('简体')
```

**Comment by rexdf** [comment]
不行啊，最新版的貌似不支持标准输入读入

**Comment by rexdf** [comment]
而且我希望不依赖与任何外部包。

**Comment by BYVoid** [comment]
可以使用 ctype 調用 .dll 或者 .so https://docs.python.org/2/library/ctypes.html

**Comment by rexdf** [comment]
嗯 倒是在考虑so和dll了。 我有点想编译一个原生的Python Extention，正常尝试。如果不行就ctype吧。

**Comment by rexdf** [comment]
确实很容易啊，只要swig导出一下opencc.h就好了。

**Comment by rexdf** [comment]
虽然只要一两行swig代码就可以生成一个pyd，但是还是依赖于opencc.dll. 从跨平台考虑这样倒不如直接ctypes方便，不过能省下考虑各种数据传入传出转换的脑细胞。

如果要编译无依赖的pyd是不是要改很多代码？主要是src中一堆cpp之间的关系还没搞明白。思路上应该是重新写个cmake.txt来生成纯静态的lib(简单加了个static似乎不行，Export.hpp导出动态库的，然后一堆连链接错误)，然后各个平台编译一下。
