### ISSUE TITLE
Linux的so链接问题

### ISSUE THREAD

**Issue by rexdf** [BYVoid/OpenCC#113]
想编译静态的OpenCC library，把根目录下面CMakeLists.txt的option(BUILD_SHARED_LIBS "Build opencc as shared library" ON)改成了OFF。

这个配置在Windows环境下编译正常，我要编译目标是一个动态库，链接opencc.lib也是正常的。

但是我在Archlinux 64下面编译同样的代码时出现了错误如下：

```bash
gcc -pthread -shared *** -L../OpenCC/build/rel/src -lopencc ***
/usr/bin/ld: ../OpenCC/build/rel/src/libopencc.a(SimpleConverter.cpp.o): relocation R_X86_64_32 against `__pthread_key_create' can not be used when making a shared object; recompile with -fPIC
../OpenCC/build/rel/src/libopencc.a: error adding symbols: 错误的值
collect2: 错误：ld 返回 1
```

看上去是libopencc.a编译的不正确，但是opencc执行程序似乎是正常，能从标准输入读入然后转换。

补充，如果设置为ON，重新编译，能正常编译出结果，但是我不希望发布的程序额外带一个libopencc.so文件。

**Comment by rexdf** [comment]
这是不是意味着我要手动改cmake生成的Makefile或者啥的？

**Comment by rexdf** [comment]
已暴力解决

**Comment by BYVoid** [comment]
請問你是如何解決的？

**Comment by rexdf** [comment]
因为swig导出到python时候，默认是c，他会使用gcc/clang而不是g++/clang++来编译。我的解决办法是对Linux加上-lstdc++，对OSX加上-lc++.不知道有没有好一点的解决办法？需要根据平台定制参数，感觉这样跨平台不太舒服。

Windows上似乎不需要特别注意这一点。
