### ISSUE TITLE
Win7 x64 & Visual Studio C++ 2013 Express 编译报错

### ISSUE THREAD

**Issue by gucong3000** [BYVoid/OpenCC#115]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“binding.vcxproj”的平台无效。平台为“x64”
。您会看到此消息的可能原因是，
您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默认平台
。 [D:\www\webapp\node_modules\opencc\bu
ild\binding.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“configs.vcxproj”的平台无效。平台为“x64”
。您会看到此消息的可能原因是，
您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非默认平台
。 [D:\www\webapp\node_modules\opencc\bu
ild\configs.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: 项目“opencc_dict.vcxproj”的平台无效。平台为“x6
4”。您会看到此消息的可能
原因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目指定了并不存在的非
默认平台。 [D:\www\webapp\node_modules\openc
c\build\opencc_dict.vcxproj]

**Comment by gucong3000** [comment]
今天尝试了安装Microsoft Visual C++ 2010 Express，报错信息和之前一样呢。
大神快出来解决一下吧。建议跟 [sass](https://www.npmjs.com/package/sass) 一样，安装脚本逻辑这样写：优先尝试从网上现在编译好的zip包，下载失败才去尝试本地编译

**Comment by Vassile-D** [comment]
你应该是使用了 x86 系统尝试编译针对 x64 的项目。我没有测试过能否编译成功，但即使成功编译一定是无法运行的。

**Comment by BYVoid** [comment]
請嘗試npm i opencc@1.0.3

**Comment by gucong3000** [comment]
D:\www\h5app>npm i opencc@1.0.3
|
> opencc@1.0.3 install D:\www\h5app\node_modules\opencc
> node-gyp rebuild


D:\www\h5app\node_modules\opencc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: 项目“bind
in
g.vcxproj”的平台无效。平台为“x64”。您会看到此消息的可能原因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目
指定了并不存在的非默认平台。 [D:\www\h5app\node_modules\opencc\buil
d\binding.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: 项目“conf
ig
s.vcxproj”的平台无效。平台为“x64”。您会看到此消息的可能原因是，您尝试在没有解决方案文件的情况下生成项目，并且为此项目
指定了并不存在的非默认平台。 [D:\www\h5app\node_modules\opencc\buil
d\configs.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: 项目“open
cc
_dict.vcxproj”的平台无效。平台为“x64”。您会看到此消息的可能原因是，您尝试在没有解决方案文件的情况下生成项目，并且为此
项目指定了并不存在的非默认平台。 [D:\www\h5app\node_modules\opencc\
build\opencc_dict.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
69:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd D:\www\h5app\node_modules\opencc
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
" "opencc@1.0.3"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! opencc@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencc@1.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the opencc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\www\h5app\npm-debug.log
