### ISSUE TITLE
有關繁轉簡出錯

### ISSUE THREAD

**Issue by jovehammer16** [BYVoid/OpenCC#119]
繁體： 唓 轉簡體會出 𪠳
而不是保留原來的 唓 字

另外能否公開字庫供node.js編碼者查閱？

**Comment by osfans** [comment]
這是類推的簡化字吧

**Comment by jovehammer16** [comment]
http://holland.pk/uptow/i4/17fb4edc75c6cf761463cfca4a86e5af.png

可是我看到的是亂碼 （見上圖）
請問你可以看到字嗎？

**Comment by osfans** [comment]
可以啊，參見漢典：
http://www.zdic.net/z/af/js/2A833.htm

**Comment by BYVoid** [comment]
這個字的確有類推簡化字，但是不在Unicode BMP區域，所以會造成有時無法顯示的問題。

**Comment by akar1nchan** [comment]
喜帖街的 “喜”字 在香港应该作“囍” 在opencc的香港标准裡好像缺失此转换

**Comment by shtse8** [comment]
香港一般書面語都會用「喜」而不會用「囍」
囍是中國人用來辦喜事希望雙喜臨門才會寫作囍
一般中文只會用「喜」

參考來源：
https://zh.wikipedia.org/wiki/%E5%88%A9%E6%9D%B1%E8%A1%97
https://hk.answers.yahoo.com/question/index?qid=20070616000051KK04521

2015-09-29 5:32 GMT+08:00 機智的阿卡林醬 <notifications@github.com>:

**Comment by akar1nchan** [comment]
我同意你的意見
所以我提出部分情況需要特別的對待 

比如轉換簡體中文至繁體 “喜欢”會成爲“喜歡”

但是轉換簡體中文至繁體“喜帖”會成爲“囍帖”

**Comment by shtse8** [comment]
我的意思是，應該也寫作喜帖
囍帖是錯誤的，只是為了賀喜才出現的
是傳統的中國文化，但不是中文
2015年10月1日 上午2:24於 "機智的阿卡林醬" <notifications@github.com>寫道：

**Comment by akar1nchan** [comment]
https://tw.bid.yahoo.com/item/%E3%80%90%E6%84%9B%E7%8E%A9%E6%A8%822%E9%A4%A8%E3%80%91kitty-%E5%87%B1%E8%92%82%E8%B2%93-%E5%9B%8D%E8%B2%BC-%E5%A9%9A%E7%A6%AE%E5%B0%8F%E7%89%A9-%E5%A9%9A%E6%85%B6%E8%B2%BC%E7%B4%99-%E5%96%9C-100024923355

內地確實沒這種習慣，但是臺灣有這樣的寫法，香港地區我不太清楚

**Comment by shtse8** [comment]
那個人賣囍帖當然是寫囍貼啊...
因為是雙喜的貼, 你看圖就看到了 (注意是貼, 不是帖, 因為那個人是賣貼紙, 雙喜的貼紙)
中國傳統的習俗來的
但以中文的角度來說, 詞語是喜帖

囍字的由來
相傳王安石在前往考試途中，在一個鎮上見到馬員外家出了一副對聯的上聯，要求有才學的人替他對出下聯，上聯是：「走馬燈，燈馬走，燈熄馬停步」。王安石因要趕往考試，所以未有理會。事有湊巧，王安石考完試後，考試官以廳前的飛虎旗作為題目考他，考試官出了下聯，要王安石對出上聯，下聯是：「飛虎旗，旗虎飛，旗捲虎藏身」。王安石想起了馬員外的「走馬燈」上聯，便立即以它對「飛虎旗」。考試過後，王安石來到馬員外家，又以「飛虎旗」為下聯對上聯「走馬燈」。員外十分高興，便將女兒嫁了給他。就在成親當天，王安石接到金榜題名的喜訊，喜上加喜，就寫了一個大紅雙喜字貼在門上，吟道：「巧對聯成雙喜歌，馬燈飛虎結絲羅」。從此，雙喜成為新婚時不可少的字了。

2015-10-02 0:32 GMT+08:00 機智的阿卡林醬 <notifications@github.com>:

**Comment by shtse8** [comment]
修正第一句:
那個人賣囍貼當然是寫囍貼啊...

Kyle Tse <shtse8@gmail.com> 於 2015年10月2日 上午1:01 寫道：
