### ISSUE TITLE
OpenCC 支持 Delphi 开发吗

### ISSUE THREAD

**Issue by MarkZhengK** [BYVoid/OpenCC#122]

**Comment by BYVoid** [comment]
不支持，但是可以調用libopencc的接口

**Comment by steven-guan** [comment]
你好，再问一个更小白的问题。
关于libopencc的接口 , 我在本地用MSYS 给openCC 编译出来， 应该如何得到 lipopencc？
--这个delphi 调用的是一个单独的文件吗？

**Comment by MarkZhengK** [comment]
感谢上次的回答， 再问一个更小白的问题（在网上找了好久，没有找到关于使用libopencc 的例子）
我在本地用MSYS  build opencc 之后， 应该如何得到libopencc？ -- 这个libopencc 是个单独的文件吗？

**Comment by osfans** [comment]
編譯之後會生成動態庫的。我在linux系統中編譯生成的是libopencc.so，一個單獨的文件。
當然，要轉換，還要有數據文件和配置文件，在OpenCC/data目錄下。

**Comment by Arthur2e5** [comment]
@MarkZhengK 要用接口的话看 http://byvoid.github.io/OpenCC/1.0.2/group__opencc__c__api.html 呀。
