### ISSUE TITLE
使用dllimport调用无法正确转换。

### ISSUE THREAD

**Issue by seo1214** [BYVoid/OpenCC#124]
c#使用dllimport调用无法正确转换。
[DllImport(DLL_NAME_64, EntryPoint = "opencc_open")]
        public static extern IntPtr opencc_open(string configFileName);

[DllImport(DLL_NAME_64, EntryPoint = "opencc_convert_utf8", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Winapi)]
        public static extern IntPtr opencc_convert_utf8(Int64 opencc, string input, long length);

IntPtr o = opencc_open(OPENCC_DEFAULT_CONFIG_SIMP_TO_TRAD);
string s = "龙";
IntPtr s1 = opencc_convert_utf8(o.ToInt64(), s, -1);
String s2 = Marshal.PtrToStringAnsi(s1);

执行成功，但是“龙”还是简体，并且文本稍长还会返回null
请问本人是否使用有误？
我使用的版本是“opencc-1.0.1-win64”

**Comment by BYVoid** [comment]
我並沒有在C#上測試過，不過1.0.3版本修正了已知的一些問題，你可以嘗試編譯最新的版本。

**Comment by seo1214** [comment]
c++不熟悉，我下载了最新源代码，但是编译失败
错误	398	error LNK2019: 无法解析的外部符号 "public: void __cdecl opencc::PhraseExtract::SelectWords(void)" (?SelectWords@PhraseExtract@opencc@@QEAAXXZ)，该符号在函数 "public: void __cdecl opencc::PhraseExtract::Extract(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@PhraseExtract@opencc@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用	D:\Desktop\opencc-1.0.3\vs2013\src\tools\PhraseExtract.obj	opencc_phrase_extract
能否提供最新的for win64的版本下载呢？

**Comment by OemalK** [comment]
input string 需要是 UTF-8
你這樣是 ANSI

**Comment by seo1214** [comment]
请问怎么能正确调用呢

2016-04-26 12:30 GMT+08:00 OemalK <notifications@github.com>:

**Comment by seo1214** [comment]
搞定了 感谢。入参出参是关键。非常好用

private static string PtrToStringUtf8(IntPtr ptr) // aPtr is nul-terminated{
    if (ptr == IntPtr.Zero)
        return "";
    int len = 0;
    while (System.Runtime.InteropServices.Marshal.ReadByte(ptr, len) != 0)
        len++;
    if (len == 0)
        return "";
    byte[] array = new byte[len];
    System.Runtime.InteropServices.Marshal.Copy(ptr, array, 0, len);
    return System.Text.Encoding.UTF8.GetString(array);}


2016-05-01 13:21 GMT+08:00 徐巍 <seo1214@gmail.com>:
