### ISSUE TITLE
需要更完整的“行”“列”对调转换

### ISSUE THREAD

**Issue by Arthur2e5** [BYVoid/OpenCC#129]
目前的转换仅适用于成词的情况，例如“命令行”。是否有可能将所有认为是单字成词的“行”、“列”两字进行转换？

**Comment by 910JQK** [comment]
一行白鷺上青天

**Comment by Arthur2e5** [comment]
@910JQK ()

**Comment by BYVoid** [comment]
行和列的對調不屬於簡單轉換的範疇，而是地區用詞的轉換。完全交換「行」和「列」的風險很大，所以OpenCC沒有處理。

**Comment by Arthur2e5** [comment]
@BYVoid 那么就后退一步，把“行尾”“行号”“换行符”……啊有空 PR 好了。

**Comment by hitechbeijing** [comment]
有风险，总不能将银行转为银列吧～程序无法识别用词组字意。

**Comment by Arthur2e5** [comment]
@hitechbeijing 我已经表示“后退一步了”。
