### ISSUE TITLE
Win32 VS2013 "opencc_dict" Project dependency error

### ISSUE THREAD

**Issue by SONIC3D** [BYVoid/OpenCC#132]
After running CMake with the parameters provided in readme file,the generated project of "opencc_dict" contains the following problem(s) in all build profiles:
1.The opencc.dll created by libopencc project is not copied to the output dir of opencc_dict tool.That caused the opencc_dict tool crashes on running when it is invoked by "Dictionaries" project.

**Comment by Arthur2e5** [comment]
This seems to be quite close to my #128.
