### ISSUE TITLE
Win32 VS2013 "opencc_phrase_extract" Project dependency error

### ISSUE THREAD

**Issue by SONIC3D** [BYVoid/OpenCC#133]
After running CMake with the parameters provided in readme file,the generated project of "opencc_phrase_extract" contains the following error(s) in all build profiles:

1:This project is not linkable.
The generated project contains only one source file "PhraseExtract.cpp" which stores in path "<GitRoot>/src/tools/PhraseExtract.cpp".But it also depends on"<GitRoot>/src/PhraseExtract.cpp" which is not export its member function in dynamic library.
To solve this problem,either export function of PhraseExtract in libopencc so that it can be referenced by other projects or add "<GitRoot>/src/PhraseExtract.cpp" to "opencc_phrase_extract" Project and rename the previous "<GitRoot>/src/tools/PhraseExtract.cpp" to other filename so that the generated obj file in the same project will not be overwritten.

**Comment by osfans** [comment]
加這句看看：
set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--export-all-symbols")
