### ISSUE TITLE
向字典里添加字符对照表

### ISSUE THREAD

**Issue by hitechbeijing** [BYVoid/OpenCC#134]
我尝试在简体转香港繁体字典txt文件中添加中文引号对应繁体括号即" => 「 “ => 」（好吧github不区分中文引号）。但是编译就报错，提示Tabular not found ”   这是因为opencc不支持符号字典规则么？

**Comment by osfans** [comment]
Tabular就是鍵盤上的tab鍵。輸入時，有時候會變成空格。
看來必須是用tab分割，而不能使用空格分割。

**Comment by hitechbeijing** [comment]
你说的很对，字符之间不能用空格，得用Tab分开。
