### ISSUE TITLE
關於「線」（缐）和「綫」（线）的區別用法

### ISSUE THREAD

**Issue by akar1nchan** [BYVoid/OpenCC#135]
http://www.zhihu.com/question/24692386

目前opencc的簡繁轉換都是把簡體字“线” 無論是香港地區還是臺灣地區都轉爲“線”

其實香港地區是“綫”   臺灣地區是“線”

**Comment by BYVoid** [comment]
Opencc有地區轉換模式：

s2tw.json Simplified Chinese to Traditional Chinese (Taiwan Standard) 簡體到臺灣正體
s2hk.json Simplified Chinese to Traditional Chinese (Hong Kong Standard) 簡體到香港繁體（香港小學學習字詞表標準）

**Comment by akar1nchan** [comment]
我說的是 http://opencc.byvoid.com/ 這個上面的

我覺得在問題未解決之前
不要急著關任何一個issue  謝謝~

**Comment by shtse8** [comment]
我是香港人
但我不認同啊
香港也是用線
綫是別字
2015年9月17日 上午12:59於 "機智的阿卡林醬" <notifications@github.com>寫道：

**Comment by akar1nchan** [comment]
http://news.tvb.com/

看 <title>

**Comment by akar1nchan** [comment]
https://itaiwan.gov.tw/

台湾地区就不一样了

**Comment by shtse8** [comment]
既然你可以拿別人的公司名做例子
那我也來吧 :)

http://www.cabletv.com.hk/ct/
2015年9月17日 下午12:10於 "機智的阿卡林醬" <notifications@github.com>寫道：

**Comment by akar1nchan** [comment]
http://www.mtr.com.hk/ch/customer/tickets/more_airport_express.html

**Comment by shtse8** [comment]
所以就是說不可以這樣定斷
我從來都沒見過有人會寫[綫上遊戲]
只會看到[線上遊戲]
這跟香港不香港沒關係吧
香港人一定會用[綫]啊
所以我認為沒有改的必要，始終[綫]是異體字，[線]才是正字。
就好像[恒]和[恆]一樣
恒生銀行，但你不會寫恒心吧？
一般都是恆心。
[恒]是異體字，[恆]才是正字。
2015年9月17日 下午1:48於 "機智的阿卡林醬" <notifications@github.com>寫道：

**Comment by shtse8** [comment]
修正：香港人也不一定會用[綫]啊
2015年9月17日 下午2:09於 "Kyle Tse" <shtse8@gmail.com>寫道：

**Comment by anthonyfok** [comment]
我是香港人，「無綫電視台」用的是「綫」，
但我在八零年代上小學時，老師教我們寫的是「線」。

香港政府教育署 / 教育局所編訂的《[常用字字形表](https://zh.wikipedia.org/wiki/%E5%B8%B8%E7%94%A8%E5%AD%97%E5%AD%97%E5%BD%A2%E8%A1%A8)》中，以「線」為標準字，「綫」為異體字。

可以從香港「小學中文科常用字研究」網站 http://lcprichi.hkbu.edu.hk/ 搜尋「線」字 （「綫」沒有收錄），或直接點按進入「線」的解說： http://lcprichi.hkbu.edu.hk/search/show_word.php?id=2071

> 字形解說：
>
> 小篆 : 「糸」是形符，是從「戔」是聲符，不是「泉」。
> 標準字形 : 字形與小篆不同。

在香港，「線」、「綫」皆常見，前者是教育局標準，我自小也是寫「線」字的。現在長大了，要寫簡體字時寫「线」，要寫「無綫電視台」用「綫」，「有線電視台」用「線」，盡量忠於相關公司的原名。其他場合嘛，看心情，呵呵。

所以 OpenCC 如果用的是「線」，我覺得已經很好了，不需要更改，至少這是香港教育局的標準。我也還未聽說過香港有其他標準以「綫」字為標準字形；當然，「綫」也完全沒有錯誤，但既然有標準，兩者取捨，OpenCC 當然是要跟隨教育局官方標準啦。

**Comment by shtse8** [comment]
Anthony 說得好
我也是這樣認為
OpenCC始終都是一套工具，很難做得到完美
但只要是正字就已經是最好的選擇，不用改就最好了
沒可能每一間公司，每一個名詞都收錄在opencc吧？
2015年9月17日 下午2:13於 "Anthony Fok" <notifications@github.com>寫道：

**Comment by akar1nchan** [comment]
@shtse8 
這也不是絕對的

來自香港的新聞

http://www.hket.com/eti/article/b26008ed-2f5a-42cf-b29b-535dc52a7f0b-924192?category=hknews&source=print&printable=true

http://hk.ulifestyle.com.hk/topic/detail.html?id=ABFGD1ozBwtZFgNt

香港社區裡面用到這個字的也不少

http://www.hkbf.org/t311693.htm
http://forum.agames.hk/forum.php?mod=viewthread&tid=110605

所以不一定啊

**Comment by shtse8** [comment]
所以就是說，不是哪個正確哪個錯誤的問題，而是正字跟異體字的關係
我相信上面的和Anthony都已經解釋得很清楚了

2015-09-17 14:17 GMT+08:00 機智的阿卡林醬 <notifications@github.com>:

**Comment by anthonyfok** [comment]
OpenCC 的字詞轉換表，為了有所適從，都按照當地(臺灣)教育部、(香港)教育局的標準，如2007年的《香港小學學習字詞表》 http://www.edbchinese.hk/lexlist_ch/ 裏附錄中的〈[常用字字形表](https://zh.wikipedia.org/wiki/%E5%B8%B8%E7%94%A8%E5%AD%97%E5%AD%97%E5%BD%A2%E8%A1%A8)〉，所以，近三十多年來，在香港上學的學生，老師都是教他們寫「線」字的。

在網上找到這麼一段：

> 清代段玉裁『說文解字注』
>
> 【線】古文綫。周禮縫人作線。鮑人同。注曰。故書線作綜。當爲糸旁泉。讀爲絤。按線作綜，字之誤也。絤則鄭時行此字。漢功臣表。不絕如綫。晉灼曰。綫今線縷字。葢晉時通行線字。故云尒。許時古線今綫。晉時則爲古綫今線。葢文字古今轉移無定如此。

好一句「蓋文字古今轉移無定如此」。

@akar1nchan, 如果你較喜歡「綫」字，我建議你自行修訂你電腦上的 OpenCC 字詞轉換表，例如在 `data/dictionary/HKVariants.txt` 增加一行：

    線      綫

編譯後就好用啦！ :-)  這就是 OpenCC 是 open-source 的好處，任何人都可以按自己的需要修改。

**Comment by anthonyfok** [comment]
提外話：在 http://www.edbchinese.hk/lexlist_ch/ 找到了「麪」字，好懷念啊！只有在香港的學校依據康熙字典是以「麪」為正字，臺灣用「麵」、大陸用「面」，據說都是俗寫。可惜在香港坊間絕少見到「麪」字，都是「麵」字居多。呵呵，無所謂啦，沒關係了。

**Comment by jakwings** [comment]
這個還是依香港教育局標準處理比較好，假如是專名用字問題，建議提交補丁方便大家。「線、綫」都是常用字，我想 BYVoid 等有文字功底的項目管理員早有研究，沒必要再爭了。

**Comment by TyrWang** [comment]
http://chardb.iis.sinica.edu.tw/meancompare/7DAB/7DDA
補充一個台灣**國際電腦漢字及異體字知識庫**的資料
