### ISSUE TITLE
有關於姓氏的簡轉繁 (一簡對多繁)

### ISSUE THREAD

**Issue by johnnyWMobile** [BYVoid/OpenCC#140]
例如: 肖邦  <--> 蕭邦

現在可以configure到這樣的轉換嗎?

其實如果有一對多情況下, 我想output所有可能的value, 這樣做到嗎??

謝謝

**Comment by BYVoid** [comment]
可以自己添加辭典來做到。

輸出所有的可能性尚未被命令行工具支持。
