### ISSUE TITLE
Make error on Ubuntu cmake_symlink_library: System Error: Protocol error

### ISSUE THREAD

**Issue by hhchen1105** [BYVoid/OpenCC#141]
Can someone help me on the compiling issue? Thanks!

OS: Ubuntu 14.04
gcc version 4.9.2
python version: 2.7.6

$ make clean
$ make
[ 43%] Building CXX object src/CMakeFiles/libopencc.dir/UTF8Util.cpp.o
Linking CXX shared library libopencc.so
CMake Error: cmake_symlink_library: System Error: Protocol error
CMake Error: cmake_symlink_library: System Error: Protocol error
make[2]: *** [src/libopencc.so.1.0.0] Error 1
make[1]: *** [src/CMakeFiles/libopencc.dir/all] Error 2
make: *** [all] Error 2

**Comment by hhchen1105** [comment]
I found the reason.  I run the make command on a virtual machine.  When running the command on a folder that is shared by the guest and the host OS, the system reports the above error.  When running on a folder that is accessible only on the guest OS, everything works fine.

**Comment by bizilliam** [comment]
Thanks!  This solved my issue too.  Moving it from shared folder to a standard directory on the guest.

**Comment by idofilus** [comment]
I came here with no relate to this repository only for a the same error.
I also had it with VM and shared folder. _(using vagrant)_, I solved my issues by just doing `vagrant up` and `vagant ssh` with cmd administrator

**Comment by pajanaj** [comment]
> I found the reason. I run the make command on a virtual machine. When running the command on a folder that is shared by the guest and the host OS, the system reports the above error. When running on a folder that is accessible only on the guest OS, everything works fine.

i  had same problem,  i am working on google colab, can you suggest me how to solve
