### ISSUE TITLE
香港繁體錯字

### ISSUE THREAD

**Issue by groverlynn** [BYVoid/OpenCC#142]
「煙」字，無論是作「香煙」還是「煙霧」解，香港繁體一律作「煙」，並無「菸」的寫法。「菸」字是台灣繁體用法。但是opencc內的香港繁體，卻把「菸」作正字
另外，粵語地名特有的「涌」（拼音chong，如東涌、黃泥涌），簡繁均作「涌」，香港繁體過度轉換為「湧」

**Comment by BYVoid** [comment]
感謝。 091ef111ca18015ffc4a248d7549d969d74e4950

關於「涌」，應該沒有問題 https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/HKVariantsPhrases.txt

**Comment by kunki** [comment]
關於「涌」，似應繼續枚舉各類地名，我當時是在網上找到的一些地名直接寫上去的，肯定不全，比如「黃泥涌」就漏收了。

**Comment by kunki** [comment]
不知 @groverlynn 能否繼續補充一下所有含「涌」的地名。
