### ISSUE TITLE
Getting OpenCC CLI to translate from Traditional Chinese to Simplified Chinese.

### ISSUE THREAD

**Issue by ocyedwin** [BYVoid/OpenCC#144]
As above.

I've installed OpenCC in Ubuntu using "sudo apt-get install opencc"

Due to 'Default configuration(zhs2zht.ini) will be loaded if not set', 
"opencc -i test.txt -o result.txt" will convert simplified Chinese to traditional Chinese.

Where do I find the correct config file to feed in to do the reverse?

Thanks for writing such a great software.

**Comment by osfans** [comment]
`sudo dpkg -L libopencc1` 會列出所有配置文件，我這裏有：`zht2zhs.ini`
所以，命令可能是：`opencc -i test.txt -o result.txt -c zht2zhs.ini`

**Comment by BYVoid** [comment]
Please run 'opencc --help'. The predefined configurations are (for latest version):

https://github.com/BYVoid/OpenCC#configurations-配置文件

**Comment by lypanov** [comment]
Any chance of adding a link to the configuration list when using --help? Very confusing attempting to use this project (I'm learning Simplified).
