### ISSUE TITLE
先跑过来赞个

### ISSUE THREAD

**Issue by tooktoo** [BYVoid/OpenCC#145]
三天啦总算搞定了。装这个东西，搞了三天。。。。。。唉

**Comment by BYVoid** [comment]
能告訴我你遇到的問題嗎

**Comment by tooktoo** [comment]
编译好后没办法转换。

能正常显示opencc 版本。。

但不转换！！！

![qq 20151111191534](https://cloud.githubusercontent.com/assets/12507122/11089914/bc37d47e-88a8-11e5-906c-7d2a26833469.png)

![qq 20151111191614](https://cloud.githubusercontent.com/assets/12507122/11089916/c3c6400e-88a8-11e5-8a02-91833b46b6f2.png)

**Comment by osfans** [comment]
系統編碼不是utf8的？
終端執行`locale`看看

**Comment by tooktoo** [comment]
我现在重做系统。我也不清楚是什么编码，我用的阿里云的服务器，他直接装的系统。要等一会才看的见

如果不是utf8怎么搞？阿里云那里边是默认安装的

**Comment by osfans** [comment]
不影響你處理utf8文本文件。

也许可以用iconv之類的轉成utf8。
`echo 测试中文转换|iconv -fGBK -tUTF-8|opencc|iconv -fUTF-8 -tGBK`

**Comment by tooktoo** [comment]
系统是UTF8的。。我晕了！

**Comment by osfans** [comment]
那你遠程登錄的？那要看你本地的編碼了。

**Comment by tooktoo** [comment]
先谢谢你。我再看看原因吧！不行晚点再求助。

**Comment by tooktoo** [comment]
@osfans 搞好了，不知道什么原因。每装一次得重启一次。重启就好了。还是谢谢你。为什么要重启。这很不科学，我装另一台机器时，就好像没有重启。。。无法用科学解释的问题都是长相问题。谢谢你！
