### ISSUE TITLE
关于字典转换表的疑问

### ISSUE THREAD

**Issue by chasuner** [BYVoid/OpenCC#146]
字典表中有的行有超过两个的，例如`"綵	彩 䌽"`，但是好像没有用到后面的那些字，只使用了第一个，请问一下放多个目的是什么？
```class OPENCC_EXPORT MultiValueDictEntry : public DictEntry {
public:
  virtual const char* GetDefault() const {
    if (NumValues() > 0) {
      return Values().at(0);
    } else {
      return Key();
    }
  }```

**Comment by lotem** [comment]
这是一对多映射。
例如简→繁转换有 `发` → `發 髪`。在词句和短语里有可能根据上下文决定转换为那个繁体字。
但如果只转换单字，在需要完整结果的场合（如在输入法中），应该给出两个可能的转换结果。

**Comment by chasuner** [comment]
谢谢回复！存在多个转换我明白，我的疑问是在代码和测试中似乎都没有发现选择多个转换的实现，因而想请问一下是本来就没有实现还是我理解错了？

**Comment by lotem** [comment]
`DictEntry::Values()`

**Comment by chasuner** [comment]
它本来用来的是数组`values`，但是转换值的时候貌似只用到了`values.get(0)`，其实我自己重新实现了一份java版本的代码，然后觉得这里没有实现多个转换的选择

**Comment by BYVoid** [comment]
目前的確是只用到了第一個結果，但是並不妨礙你使用其他的結果。OpenCC以後可能會實現交互式選擇異體字。

**Comment by chasuner** [comment]
明白了，谢谢！
