### ISSUE TITLE
centOS 64bit安装失败

### ISSUE THREAD

**Issue by reec20** [BYVoid/OpenCC#148]
系统环境，centOS 6.5 64bit   ,GCC4.6.1
make失败，错误如下，请教！

 make
mkdir -p build/rel
(cd build/rel; cmake \
        -DBUILD_DOCUMENTATION:BOOL=ON \
        -DENABLE_GTEST:BOOL=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        ../..)
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/OpenCC/build/rel
make -C build/rel VERBOSE= PREFIX=/usr
make[1]: Entering directory `/usr/OpenCC/build/rel'
make[2]: Entering directory `/usr/OpenCC/build/rel'
make[3]: Entering directory `/usr/OpenCC/build/rel'
make[3]: Leaving directory `/usr/OpenCC/build/rel'
make[3]: Entering directory `/usr/OpenCC/build/rel'
[  2%] Building CXX object src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o
In file included from /usr/OpenCC/src/Common.hpp:43,
                 from /usr/OpenCC/src/BinaryDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/Exception.hpp:43: error: expected 鈥?鈥?before 鈥榥oexcept鈥?
/usr/OpenCC/src/Exception.hpp:45: error: expected 鈥?鈥?before 鈥榩rotected鈥?
In file included from /usr/OpenCC/src/Common.hpp:45,
                 from /usr/OpenCC/src/BinaryDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/Optional.hpp: In constructor 鈥榦pencc::Optional<T*>::Optional()                                             鈥?
/usr/OpenCC/src/Optional.hpp:62: error: 鈥榥ullptr鈥?was not declared in this s                                             cope
/usr/OpenCC/src/Optional.hpp: In member function 鈥榖ool opencc::Optional<T*>::I                                             sNull() const鈥?
/usr/OpenCC/src/Optional.hpp:70: error: 鈥榥ullptr鈥?was not declared in this s                                             cope
In file included from /usr/OpenCC/src/DictEntry.hpp:22,
                 from /usr/OpenCC/src/Dict.hpp:22,
                 from /usr/OpenCC/src/SerializableDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.hpp:22,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/UTF8Util.hpp: In static member function 鈥榮tatic std::string op                                             encc::UTF8Util::Join(const std::vector<std::basic_string<char, std::char_traits<                                             char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_                                             traits<char>, std::allocator<char> > > >&, const std::string&)鈥?
/usr/OpenCC/src/UTF8Util.hpp:212: error: expected initializer before 鈥?鈥?tok                                             en
/usr/OpenCC/src/UTF8Util.hpp:220: error: expected primary-expression at end of i                                             nput
/usr/OpenCC/src/UTF8Util.hpp:220: error: expected 鈥?鈥?at end of input
/usr/OpenCC/src/UTF8Util.hpp:220: error: expected primary-expression at end of i                                             nput
/usr/OpenCC/src/UTF8Util.hpp:220: error: expected 鈥?鈥?at end of input
/usr/OpenCC/src/UTF8Util.hpp:220: error: expected statement at end of input
/usr/OpenCC/src/UTF8Util.hpp:211: warning: unused variable 鈥榝irst鈥?
/usr/OpenCC/src/UTF8Util.hpp:220: error: expected 鈥榼鈥?at end of input
/usr/OpenCC/src/UTF8Util.hpp:220: warning: no return statement in function retur                                             ning non-void
/usr/OpenCC/src/UTF8Util.hpp: In static member function 鈥榮tatic std::string op                                             encc::UTF8Util::Join(const std::vector<std::basic_string<char, std::char_traits<                                             char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_                                             traits<char>, std::allocator<char> > > >&)鈥?
/usr/OpenCC/src/UTF8Util.hpp:227: error: expected initializer before 鈥?鈥?tok                                             en
/usr/OpenCC/src/UTF8Util.hpp:230: error: expected primary-expression before 鈥榬                                             eturn鈥?
/usr/OpenCC/src/UTF8Util.hpp:230: error: expected 鈥?鈥?before 鈥榬eturn鈥?
/usr/OpenCC/src/UTF8Util.hpp:230: error: expected primary-expression before 鈥榬                                             eturn鈥?
/usr/OpenCC/src/UTF8Util.hpp:230: error: expected 鈥?鈥?before 鈥榬eturn鈥?
In file included from /usr/OpenCC/src/DictEntry.hpp:23,
                 from /usr/OpenCC/src/Dict.hpp:22,
                 from /usr/OpenCC/src/SerializableDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.hpp:22,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/Segments.hpp: In constructor 鈥榦pencc::Segments::Segments(std::                                             initializer_list<const char*>)鈥?
/usr/OpenCC/src/Segments.hpp:33: error: expected initializer before 鈥?鈥?toke                                             n
/usr/OpenCC/src/Segments.hpp:36: error: expected primary-expression before 鈥榼?                                            €?token
/usr/OpenCC/src/Segments.hpp:36: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/Segments.hpp:36: error: expected primary-expression before 鈥榼?                                            €?token
/usr/OpenCC/src/Segments.hpp:36: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/Segments.hpp:36: error: expected primary-expression before 鈥榼?                                            €?token
/usr/OpenCC/src/Segments.hpp:36: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/Segments.hpp: In constructor 鈥榦pencc::Segments::Segments(std::                                             initializer_list<std::basic_string<char, std::char_traits<char>, std::allocator<                                             char> > >)鈥?
/usr/OpenCC/src/Segments.hpp:39: error: expected initializer before 鈥?鈥?toke                                             n
/usr/OpenCC/src/Segments.hpp:42: error: expected primary-expression before 鈥榼?                                            €?token
/usr/OpenCC/src/Segments.hpp:42: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/Segments.hpp:42: error: expected primary-expression before 鈥榼?                                            €?token
/usr/OpenCC/src/Segments.hpp:42: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/Segments.hpp:42: error: expected primary-expression before 鈥榼?                                            €?token
/usr/OpenCC/src/Segments.hpp:42: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/Segments.hpp: In member function 鈥榮td::string opencc::Segments                                             ::ToString() const鈥?
/usr/OpenCC/src/Segments.hpp:98: error: expected initializer before 鈥?鈥?toke                                             n
/usr/OpenCC/src/Segments.hpp:101: error: expected primary-expression before 鈥榬                                             eturn鈥?
/usr/OpenCC/src/Segments.hpp:101: error: expected 鈥?鈥?before 鈥榬eturn鈥?
/usr/OpenCC/src/Segments.hpp:101: error: expected primary-expression before 鈥榬                                             eturn鈥?
/usr/OpenCC/src/Segments.hpp:101: error: expected 鈥?鈥?before 鈥榬eturn鈥?
In file included from /usr/OpenCC/src/Dict.hpp:22,
                 from /usr/OpenCC/src/SerializableDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.hpp:22,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/DictEntry.hpp: In constructor 鈥榦pencc::StrMultiValueDictEntry:                                             :StrMultiValueDictEntry(const std::string&, const std::vector<const char*, std::                                             allocator<const char*> >&)鈥?
/usr/OpenCC/src/DictEntry.hpp:131: error: expected initializer before 鈥?鈥?to                                             ken
/usr/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before 鈥?                                            }鈥?token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before 鈥?                                            }鈥?token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before 鈥?                                            }鈥?token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/DictEntry.hpp: In member function 鈥榲irtual std::vector<const c                                             har*, std::allocator<const char*> > opencc::StrMultiValueDictEntry::Values() con                                             st鈥?
/usr/OpenCC/src/DictEntry.hpp:144: error: expected initializer before 鈥?鈥?to                                             ken
/usr/OpenCC/src/DictEntry.hpp:147: error: expected primary-expression before 鈥?                                            return鈥?
/usr/OpenCC/src/DictEntry.hpp:147: error: expected 鈥?鈥?before 鈥榬eturn鈥?
/usr/OpenCC/src/DictEntry.hpp:147: error: expected primary-expression before 鈥?                                            return鈥?
/usr/OpenCC/src/DictEntry.hpp:147: error: expected 鈥?鈥?before 鈥榬eturn鈥?
In file included from /usr/OpenCC/src/BinaryDict.cpp:20:
/usr/OpenCC/src/Lexicon.hpp: In destructor 鈥榦pencc::Lexicon::~Lexicon()鈥?
/usr/OpenCC/src/Lexicon.hpp:34: error: expected initializer before 鈥?鈥?token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before 鈥榼鈥                                             ?token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before 鈥榼鈥                                             ?token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before 鈥榼鈥                                             ?token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected 鈥?鈥?before 鈥榼鈥?token
/usr/OpenCC/src/BinaryDict.cpp: In member function 鈥榮ize_t opencc::BinaryDict:                                             :KeyMaxLength() const鈥?
/usr/OpenCC/src/BinaryDict.cpp:26: error: expected initializer before 鈥?鈥?to                                             ken
/usr/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression before 鈥?                                            return鈥?
/usr/OpenCC/src/BinaryDict.cpp:29: error: expected 鈥?鈥?before 鈥榬eturn鈥?
/usr/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression before 鈥?                                            return鈥?
/usr/OpenCC/src/BinaryDict.cpp:29: error: expected 鈥?鈥?before 鈥榬eturn鈥?
/usr/OpenCC/src/BinaryDict.cpp: In member function 鈥榲irtual void opencc::Binar                                             yDict::SerializeToFile(FILE*) const鈥?
/usr/OpenCC/src/BinaryDict.cpp:49: error: expected initializer before 鈥?鈥?to                                             ken
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected primary-expression at end of                                              input
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected 鈥?鈥?at end of input
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected primary-expression at end of                                              input
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected 鈥?鈥?at end of input
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected statement at end of input
/usr/OpenCC/src/BinaryDict.cpp:48: warning: unused variable 鈥榢eyCursor鈥?
/usr/OpenCC/src/BinaryDict.cpp:48: warning: unused variable 鈥榲alueCursor鈥?
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected 鈥榼鈥?at end of input
make[3]: *** [src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o] Error 1
make[3]: Leaving directory `/usr/OpenCC/build/rel'
make[2]: *** [src/CMakeFiles/libopencc.dir/all] Error 2
make[2]: Leaving directory `/usr/OpenCC/build/rel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/OpenCC/build/rel'
make: *** [build] Error 2

**Comment by osfans** [comment]
爲何這麼多亂碼？
或者換clang編譯器看看。
```
rm -rf build
make CXX=clang++ VERBOSE=1
```

**Comment by reec20** [comment]
您好，因为是生产环境的机器，我暂时没有使用clang编译
我在网上找了一条命令，乱码转为英文了，能否帮忙看看问题？

[root@li745-70 OpenCC]# export LANG=en_US
[root@li745-70 OpenCC]# make
mkdir -p build/rel
(cd build/rel; cmake \
        -DBUILD_DOCUMENTATION:BOOL=ON \
        -DENABLE_GTEST:BOOL=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        ../..)
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/OpenCC/build/rel
make -C build/rel VERBOSE= PREFIX=/usr
make[1]: Entering directory `/tmp/OpenCC/build/rel'
make[2]: Entering directory `/tmp/OpenCC/build/rel'
make[3]: Entering directory `/tmp/OpenCC/build/rel'
make[3]: Leaving directory `/tmp/OpenCC/build/rel'
make[3]: Entering directory `/tmp/OpenCC/build/rel'
[  2%] Building CXX object src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o
In file included from /tmp/OpenCC/src/Common.hpp:43,
                 from /tmp/OpenCC/src/BinaryDict.hpp:21,
                 from /tmp/OpenCC/src/BinaryDict.cpp:19:
/tmp/OpenCC/src/Exception.hpp:43: error: expected ';' before 'noexcept'
/tmp/OpenCC/src/Exception.hpp:45: error: expected ';' before 'protected'
In file included from /tmp/OpenCC/src/Common.hpp:45,
                 from /tmp/OpenCC/src/BinaryDict.hpp:21,
                 from /tmp/OpenCC/src/BinaryDict.cpp:19:
/tmp/OpenCC/src/Optional.hpp: In constructor 'opencc::Optional<T*>::Optional()':
/tmp/OpenCC/src/Optional.hpp:62: error: 'nullptr' was not declared in this scope
/tmp/OpenCC/src/Optional.hpp: In member function 'bool opencc::Optional<T*>::IsN                                             ull() const':
/tmp/OpenCC/src/Optional.hpp:70: error: 'nullptr' was not declared in this scope
In file included from /tmp/OpenCC/src/DictEntry.hpp:22,
                 from /tmp/OpenCC/src/Dict.hpp:22,
                 from /tmp/OpenCC/src/SerializableDict.hpp:21,
                 from /tmp/OpenCC/src/BinaryDict.hpp:22,
                 from /tmp/OpenCC/src/BinaryDict.cpp:19:
/tmp/OpenCC/src/UTF8Util.hpp: In static member function 'static std::string open                                             cc::UTF8Util::Join(const std::vector<std::basic_string<char, std::char_traits<ch                                             ar>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_tr                                             aits<char>, std::allocator<char> > > >&, const std::string&)':
/tmp/OpenCC/src/UTF8Util.hpp:212: error: expected initializer before ':' token
/tmp/OpenCC/src/UTF8Util.hpp:220: error: expected primary-expression at end of i                                             nput
/tmp/OpenCC/src/UTF8Util.hpp:220: error: expected ';' at end of input
/tmp/OpenCC/src/UTF8Util.hpp:220: error: expected primary-expression at end of i                                             nput
/tmp/OpenCC/src/UTF8Util.hpp:220: error: expected ')' at end of input
/tmp/OpenCC/src/UTF8Util.hpp:220: error: expected statement at end of input
/tmp/OpenCC/src/UTF8Util.hpp:211: warning: unused variable 'first'
/tmp/OpenCC/src/UTF8Util.hpp:220: error: expected '}' at end of input
/tmp/OpenCC/src/UTF8Util.hpp:220: warning: no return statement in function retur                                             ning non-void
/tmp/OpenCC/src/UTF8Util.hpp: In static member function 'static std::string open                                             cc::UTF8Util::Join(const std::vector<std::basic_string<char, std::char_traits<ch                                             ar>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_tr                                             aits<char>, std::allocator<char> > > >&)':
/tmp/OpenCC/src/UTF8Util.hpp:227: error: expected initializer before ':' token
/tmp/OpenCC/src/UTF8Util.hpp:230: error: expected primary-expression before 'ret                                             urn'
/tmp/OpenCC/src/UTF8Util.hpp:230: error: expected ';' before 'return'
/tmp/OpenCC/src/UTF8Util.hpp:230: error: expected primary-expression before 'ret                                             urn'
/tmp/OpenCC/src/UTF8Util.hpp:230: error: expected ')' before 'return'
In file included from /tmp/OpenCC/src/DictEntry.hpp:23,
                 from /tmp/OpenCC/src/Dict.hpp:22,
                 from /tmp/OpenCC/src/SerializableDict.hpp:21,
                 from /tmp/OpenCC/src/BinaryDict.hpp:22,
                 from /tmp/OpenCC/src/BinaryDict.cpp:19:
/tmp/OpenCC/src/Segments.hpp: In constructor 'opencc::Segments::Segments(std::in                                             itializer_list<const char*>)':
/tmp/OpenCC/src/Segments.hpp:33: error: expected initializer before ':' token
/tmp/OpenCC/src/Segments.hpp:36: error: expected primary-expression before '}' t                                             oken
/tmp/OpenCC/src/Segments.hpp:36: error: expected ';' before '}' token
/tmp/OpenCC/src/Segments.hpp:36: error: expected primary-expression before '}' t                                             oken
/tmp/OpenCC/src/Segments.hpp:36: error: expected ')' before '}' token
/tmp/OpenCC/src/Segments.hpp:36: error: expected primary-expression before '}' t                                             oken
/tmp/OpenCC/src/Segments.hpp:36: error: expected ';' before '}' token
/tmp/OpenCC/src/Segments.hpp: In constructor 'opencc::Segments::Segments(std::in                                             itializer_list<std::basic_string<char, std::char_traits<char>, std::allocator<ch                                             ar> > >)':
/tmp/OpenCC/src/Segments.hpp:39: error: expected initializer before ':' token
/tmp/OpenCC/src/Segments.hpp:42: error: expected primary-expression before '}' t                                             oken
/tmp/OpenCC/src/Segments.hpp:42: error: expected ';' before '}' token
/tmp/OpenCC/src/Segments.hpp:42: error: expected primary-expression before '}' t                                             oken
/tmp/OpenCC/src/Segments.hpp:42: error: expected ')' before '}' token
/tmp/OpenCC/src/Segments.hpp:42: error: expected primary-expression before '}' t                                             oken
/tmp/OpenCC/src/Segments.hpp:42: error: expected ';' before '}' token
/tmp/OpenCC/src/Segments.hpp: In member function 'std::string opencc::Segments::                                             ToString() const':
/tmp/OpenCC/src/Segments.hpp:98: error: expected initializer before ':' token
/tmp/OpenCC/src/Segments.hpp:101: error: expected primary-expression before 'ret                                             urn'
/tmp/OpenCC/src/Segments.hpp:101: error: expected ';' before 'return'
/tmp/OpenCC/src/Segments.hpp:101: error: expected primary-expression before 'ret                                             urn'
/tmp/OpenCC/src/Segments.hpp:101: error: expected ')' before 'return'
In file included from /tmp/OpenCC/src/Dict.hpp:22,
                 from /tmp/OpenCC/src/SerializableDict.hpp:21,
                 from /tmp/OpenCC/src/BinaryDict.hpp:22,
                 from /tmp/OpenCC/src/BinaryDict.cpp:19:
/tmp/OpenCC/src/DictEntry.hpp: In constructor 'opencc::StrMultiValueDictEntry::S                                             trMultiValueDictEntry(const std::string&, const std::vector<const char*, std::al                                             locator<const char*> >&)':
/tmp/OpenCC/src/DictEntry.hpp:131: error: expected initializer before ':' token
/tmp/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before '}'                                              token
/tmp/OpenCC/src/DictEntry.hpp:134: error: expected ';' before '}' token
/tmp/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before '}'                                              token
/tmp/OpenCC/src/DictEntry.hpp:134: error: expected ')' before '}' token
/tmp/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before '}'                                              token
/tmp/OpenCC/src/DictEntry.hpp:134: error: expected ';' before '}' token
/tmp/OpenCC/src/DictEntry.hpp: In member function 'virtual std::vector<const cha                                             r*, std::allocator<const char*> > opencc::StrMultiValueDictEntry::Values() const                                             ':
/tmp/OpenCC/src/DictEntry.hpp:144: error: expected initializer before ':' token
/tmp/OpenCC/src/DictEntry.hpp:147: error: expected primary-expression before 're                                             turn'
/tmp/OpenCC/src/DictEntry.hpp:147: error: expected ';' before 'return'
/tmp/OpenCC/src/DictEntry.hpp:147: error: expected primary-expression before 're                                             turn'
/tmp/OpenCC/src/DictEntry.hpp:147: error: expected ')' before 'return'
In file included from /tmp/OpenCC/src/BinaryDict.cpp:20:
/tmp/OpenCC/src/Lexicon.hpp: In destructor 'opencc::Lexicon::~Lexicon()':
/tmp/OpenCC/src/Lexicon.hpp:34: error: expected initializer before ':' token
/tmp/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before '}' to                                             ken
/tmp/OpenCC/src/Lexicon.hpp:37: error: expected ';' before '}' token
/tmp/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before '}' to                                             ken
/tmp/OpenCC/src/Lexicon.hpp:37: error: expected ')' before '}' token
/tmp/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before '}' to                                             ken
/tmp/OpenCC/src/Lexicon.hpp:37: error: expected ';' before '}' token
/tmp/OpenCC/src/BinaryDict.cpp: In member function 'size_t opencc::BinaryDict::K                                             eyMaxLength() const':
/tmp/OpenCC/src/BinaryDict.cpp:26: error: expected initializer before ':' token
/tmp/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression before 're                                             turn'
/tmp/OpenCC/src/BinaryDict.cpp:29: error: expected ';' before 'return'
/tmp/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression before 're                                             turn'
/tmp/OpenCC/src/BinaryDict.cpp:29: error: expected ')' before 'return'
/tmp/OpenCC/src/BinaryDict.cpp: In member function 'virtual void opencc::BinaryD                                             ict::SerializeToFile(FILE*) const':
/tmp/OpenCC/src/BinaryDict.cpp:49: error: expected initializer before ':' token
/tmp/OpenCC/src/BinaryDict.cpp:179: error: expected primary-expression at end of                                              input
/tmp/OpenCC/src/BinaryDict.cpp:179: error: expected ';' at end of input
/tmp/OpenCC/src/BinaryDict.cpp:179: error: expected primary-expression at end of                                              input
/tmp/OpenCC/src/BinaryDict.cpp:179: error: expected ')' at end of input
/tmp/OpenCC/src/BinaryDict.cpp:179: error: expected statement at end of input
/tmp/OpenCC/src/BinaryDict.cpp:48: warning: unused variable 'keyCursor'
/tmp/OpenCC/src/BinaryDict.cpp:48: warning: unused variable 'valueCursor'
/tmp/OpenCC/src/BinaryDict.cpp:179: error: expected '}' at end of input
make[3]: *** [src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o] Error 1
make[3]: Leaving directory `/tmp/OpenCC/build/rel'
make[2]: *** [src/CMakeFiles/libopencc.dir/all] Error 2
make[2]: Leaving directory `/tmp/OpenCC/build/rel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/OpenCC/build/rel'
make: *** [build] Error 2
[root@li745-70 OpenCC]#

**Comment by reec20** [comment]
linux放在linode，是英文版本，是否跟缺中文字库有关系？

**Comment by osfans** [comment]
應該是編譯器的問題。
參數中改成`-std=gnu++11`看看
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a0c3747..d451904 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -121,7 +121,8 @@ if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
   endif ()
 elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
   add_definitions(
-    -std=c++0x
+    #-std=c++0x
+    -std=gnu++11
     -Wall
   )
   set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pthread")
```

**Comment by osfans** [comment]
還有`-std=gnu++0x`看看。

**Comment by reec20** [comment]
问题已解决，确实是编译器问题。我把gcc升级之后，c++未ln到新版本。

另外安装完成后输入opencc命令提示
opencc: error while loading shared libraries: libopencc.so.2: cannot open shared object file: No such file or directory

查出
lrwxrwxrwx 1 root root 18 Nov 20 13:30 /usr/OpenCC/build/rel/src/libopencc.so.2 -> libopencc.so.1.0.0

请问以哪个库最新？
