### ISSUE TITLE
 iphone5 以前的设备崩溃

### ISSUE THREAD

**Issue by yaoguaige** [BYVoid/OpenCC#149]
malloc: *** mach_vm_map(size=3852439552) failed (error code=3)

**Comment by gelosie** [comment]
Yes. Should be optimized for the limited memory devices.

**Comment by yaoguaige** [comment]
but I don't  what to do?

**Comment by gelosie** [comment]
Use dictionaries with txt format, it works well on iOS

**Comment by yaoguaige** [comment]
Give me a URL link?  I also want to know how  to solve the problem ....thank you!

**Comment by gelosie** [comment]
Example for iOS : https://github.com/gelosie/OpenCC/tree/master/iOS

**Comment by yaoguaige** [comment]
thank you

**Comment by BYVoid** [comment]
Thanks for the example for iOS.
