### ISSUE TITLE
Is STPhrases.ocd 4.3 MB?

### ISSUE THREAD

**Issue by gelosie** [BYVoid/OpenCC#150]
TSPhrases.txt is 1MB.  Why ocd format is larger than text?

**Comment by BYVoid** [comment]
Because there are more phrases.

**Comment by gelosie** [comment]
In iPhone 4, iPhone 4s, iPhone 5s, iPhone 5, STPhrases.ocd(4.3 MB)  will run out memory.

In current version, I use STPhrases.txt in my iOS app.
Example for iOS : https://github.com/gelosie/OpenCC/tree/master/iOS

Maybe we should make a special phrases list for memory-bound system. 
Or Optimizing memory usage for full phrases list.

**Comment by BYVoid** [comment]
Thank you very much.
