### ISSUE TITLE
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find -lpthread error

### ISSUE THREAD

**Issue by aaronlyt** [BYVoid/OpenCC#151]
in window 32,using MSYS makefiles, cmake has been success,however in make process,there has some problem
[ 46%] Linking CXX executable opencc.exe
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
make[2]: **\* [src/tools/opencc.exe] Error 1
make[1]: **\* [src/tools/CMakeFiles/opencc.dir/all] Error 2
make: **\* [all] Error 2

**Comment by BYVoid** [comment]
please try to remove -lpthread manually.

**Comment by aaronlyt** [comment]
Thanks for your answer.however,I am not familiar with Cmake,How can I remove -lpthread from which file?
