### ISSUE TITLE
人工订正支持

### ISSUE THREAD

**Issue by wpchou** [BYVoid/OpenCC#155]
一对多转换时，能否考虑把不确定的情况输出，利于人工订正。
最简单的方法，把一对多的情况全部输出并用“或”运算符联结起来。用编辑器搜索这个输出结果就能方便地标定所有需要注意的地方。

**Comment by LNDDYL** [comment]
強烈支持！

**Comment by osfans** [comment]
我覺得還是只輸出一個值比較好。
當然，不確定的情況可以作爲錯誤日誌輸出。

**Comment by wpchou** [comment]
@osfans 我说的就是这个意思，表述得有点歧义。

**Comment by lotem** [comment]
猜想，把词典里所有一对多的条目由空格分隔各个结果改为用“或”分隔，就能转换为包含所有选项的文本。

**Comment by BYVoid** [comment]
多謝建議，OpenCC計劃要實現這個功能。
