### ISSUE TITLE
安装成功，却无法把 繁体 转换成 简体，这是为什么？

### ISSUE THREAD

**Issue by kashu** [BYVoid/OpenCC#156]
第一次使用opencc，我想把 繁体 转成 简体，但安装后测试发现没变化，这是为什么？
root@kashu:~# echo 透過上一步的查詢我們會知道反斜線 | opencc
透過上一步的查詢我們會知道反斜線

`@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@`

操作系统：Xubuntu 14.04.3 LTS amd64
系统语言：English

opencc安装方式：编译安装的，安装成功。

opencc版本：
root@kashu:~# opencc --version
Open Chinese Convert (OpenCC) Command Line Tool
Version: 1.0.3

root@kashu:~# dpkg -l gcc cmake
Name       Version                 Architecture           Description
cmake      3.0.2-1ubuntu2          amd64              cross-platform, open-source make system
gcc           4:4.9.2-2ubuntu2       amd64              GNU C compiler

**Comment by kashu** [comment]
这是我系统的locale信息：
root@kashu:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=zh_CN.UTF-8
LC_TIME=zh_CN.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_ADDRESS=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL=


我实际试用情况如下：
wget http://linux.vbird.org/linux_basic/0160startlinux.php
下载的文件是utf-8的编码

opencc -i 0160startlinux.php -o test.php
输出的文件打开查看，和原文件一样，仍然是繁体，没有变成简体。

第一次使用opencc，求指导，谢谢大家！

**Comment by osfans** [comment]
還要-c指定一個config文件。json格式的。

**Comment by kashu** [comment]
谢谢，可以了。

opencc --help給出的幫助信息有點難懂……新手看着有壓力
建議完善一下幫助信息

顯然，對文件進行轉換時，-c 已然成了必選項了。
