### ISSUE TITLE
繁体转简体，补丁的丁没有转换

### ISSUE THREAD

**Issue by Geng-G-Razor** [BYVoid/OpenCC#158]
系统是Mac OS 10.11
`# 补靪功能：将自然码双拼的词库修改为朙月拼音扩充词库`

**Comment by jakwings** [comment]
「靪」字不在简化字表中。这只是朙月拼音词库的用字风格问题。
其实很多繁体字的异体也不会被转换，如：廚（厨）→㕑。

**Comment by Geng-G-Razor** [comment]
哦，略懂了。
是不是那些字不是规范的繁体字写法？

**Comment by jakwings** [comment]
假如不能轻易在流通的繁体词典中查到相关词汇的话，那个异体字基本上可以说是不规范的，香港和台湾都有各自的标准。Rime 拼音词库里有很多生僻的用字，不用心很难发现的。

**Comment by gugod** [comment]
提供個參考，在台灣教育部的詞典裡面直接有列出「補靪」 條目：

https://www.moedict.tw/%E8%A3%9C%E9%9D%AA

感覺起來，此例比較像是詞的轉換。
