### ISSUE TITLE
手工校正了一些翻译

### ISSUE THREAD

**Issue by kashu** [BYVoid/OpenCC#160]
OpenCC挺好的

我用openCC把繁体中文转换成简体中文后，还手工再用sed进一步校正了一些词汇（只是一小部分）

sed -i 's/万用字元/通配符/g' text.txt
sed -i 's/硬体/硬件/g' text.txt 
sed -i 's/程式/程序/g' text.txt 
sed -i 's/伺服器/服务器/g' text.txt
sed -i 's/网络卡/网卡/g' text.txt
sed -i 's/网路/网络/g' text.txt
sed -i 's/软体/软件/g' text.txt
sed -i 's/滑鼠/鼠标/g' text.txt
sed -i 's/萤幕/屏幕/g' text.txt
sed -i 's/协定/协议/g' text.txt
sed -i 's/原始码/原代码/g' text.txt
sed -i 's/显示卡/显卡/g' text.txt

**Comment by osfans** [comment]
你可能要指定config文件，能解決一部分問題：`opencc -c tw2sp.json`

轉換時，它就會用到這個詞表：
https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TWPhrasesIT.txt

如果還沒有，那可能就是缺詞，或者因爲大陸也會用，所以就沒有轉。

**Comment by kashu** [comment]
也就是说，可以把自定义的一些词汇放到里面？ 然后转换时会根据我想要的词汇来转？

**Comment by osfans** [comment]
當然可以啦。

**Comment by BYVoid** [comment]
已經增補 d114b84975b9e92ea9db222f5f2c39a0586c4d2e
