### ISSUE TITLE
nodejs下编译错误

### ISSUE THREAD

**Issue by EthianWong** [BYVoid/OpenCC#161]
Python 2.7.3
node-gyp 3.2.1
node 4.2.2

---

  win_delay_load_hook.c
  正在生成代码
  已完成代码的生成
  opencc_dict.vcxproj -> E:\backend\node_modules\opencc\build\Release\opencc_d
  ict.exe
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fai
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proce
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\node
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd E:\backend\node_modules\opencc
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "opencc" "--save"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! opencc@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencc@1.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the opencc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\backend\npm-debug.log

**Comment by DingWeizhe** [comment]
github 值接下載下來 node-gyp build後丟node_modules/opencc內即可

**Comment by BYVoid** [comment]
已經修復了編譯錯誤，發佈了新版本1.0.3-1，請再次嘗試。謝謝。

**Comment by gucong3000** [comment]
#244 
希望能通过预编译的方式彻底关闭这个issue
