### ISSUE TITLE
Build failed on Visual Studio 2013 Win7 & Win8

### ISSUE THREAD

**Issue by thatblstudio** [BYVoid/OpenCC#164]
opencc_phrase_extract:

10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall opencc::PhraseExtract::PhraseExtract(void)" (??0PhraseExtract@opencc@@QAE@XZ)，该符号在函数 "void __cdecl Extract(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@@YAXABV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: virtual __thiscall opencc::PhraseExtract::~PhraseExtract(void)" (??1PhraseExtract@opencc@@UAE@XZ)，该符号在函数 "void __cdecl Extract(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@@YAXABV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: struct opencc::PhraseExtract::Signals const & __thiscall opencc::PhraseExtract::Signal(class opencc::UTF8StringSliceBase<unsigned char> const &)const " (?Signal@PhraseExtract@opencc@@QBEABUSignals@12@ABV?$UTF8StringSliceBase@E@2@@Z)，该符号在函数 "void __cdecl Extract(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@@YAXABV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: double __thiscall opencc::PhraseExtract::LogProbability(class opencc::UTF8StringSliceBase<unsigned char> const &)const " (?LogProbability@PhraseExtract@opencc@@QBENABV?$UTF8StringSliceBase@E@2@@Z)，该符号在函数 "void __cdecl Extract(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@@YAXABV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall opencc::PhraseExtract::ExtractSuffixes(void)" (?ExtractSuffixes@PhraseExtract@opencc@@QAEXXZ)，该符号在函数 "public: void __thiscall opencc::PhraseExtract::Extract(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@PhraseExtract@opencc@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall opencc::PhraseExtract::ExtractPrefixes(void)" (?ExtractPrefixes@PhraseExtract@opencc@@QAEXXZ)，该符号在函数 "public: void __thiscall opencc::PhraseExtract::Extract(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@PhraseExtract@opencc@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall opencc::PhraseExtract::ExtractWordCandidates(void)" (?ExtractWordCandidates@PhraseExtract@opencc@@QAEXXZ)，该符号在函数 "public: void __thiscall opencc::PhraseExtract::Extract(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@PhraseExtract@opencc@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall opencc::PhraseExtract::CalculateFrequency(void)" (?CalculateFrequency@PhraseExtract@opencc@@QAEXXZ)，该符号在函数 "public: void __thiscall opencc::PhraseExtract::Extract(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@PhraseExtract@opencc@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall opencc::PhraseExtract::CalculateCohesions(void)" (?CalculateCohesions@PhraseExtract@opencc@@QAEXXZ)，该符号在函数 "public: void __thiscall opencc::PhraseExtract::Extract(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@PhraseExtract@opencc@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall opencc::PhraseExtract::CalculateSuffixEntropy(void)" (?CalculateSuffixEntropy@PhraseExtract@opencc@@QAEXXZ)，该符号在函数 "public: void __thiscall opencc::PhraseExtract::Extract(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@PhraseExtract@opencc@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall opencc::PhraseExtract::CalculatePrefixEntropy(void)" (?CalculatePrefixEntropy@PhraseExtract@opencc@@QAEXXZ)，该符号在函数 "public: void __thiscall opencc::PhraseExtract::Extract(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@PhraseExtract@opencc@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
10>PhraseExtract.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall opencc::PhraseExtract::SelectWords(void)" (?SelectWords@PhraseExtract@opencc@@QAEXXZ)，该符号在函数 "public: void __thiscall opencc::PhraseExtract::Extract(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Extract@PhraseExtract@opencc@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
10>C:\blProjects\OpenCC\vsbuild\src\tools\Release\opencc_phrase_extract.exe : fatal error LNK1120: 12 个无法解析的外部命令

**Comment by PCMan** [comment]
Confirmed.
I have the same problem, too.

**Comment by BYVoid** [comment]
請嘗試將opencc_phrase_extract手動去除，不影響Opencc使用。

**Comment by xpol** [comment]
#189 fixes this.

**Comment by thatblstudio** [comment]
@xpol Bravo! I'll try that later.

**Comment by xpol** [comment]
Because class `opencc::PhraseExtract` does not declare as dll class, and then not exported in the libopencc.dll and its import lib.
