### ISSUE TITLE
繁轉繁的困擾

### ISSUE THREAD

**Issue by jasliu** [BYVoid/OpenCC#165]
您好, 因為我們的程式開發商使用了你們這邊的軟體, 所以只好上來這邊詢問.
問題是這樣子. 我們是台灣的用戶, 常常會遇到繁體轉成錯誤繁體字的困擾. 
舉例來說, 我們在介面上輸入了 "李松仁"的名字, 但是在經過你們這邊軟體的轉換後, 使用者看到的會是"李鬆仁". 這會非常麻煩. 雖然我們程式開發商說, 可以把這個"李松仁"三個字變成一組詞語, 然後下次遇到的時候, 就會轉換正確, 但是由於我們每次在網頁上發布一個訊息, 只要出現這樣的錯誤, 尤其是人名的錯誤, 那就是對用戶非常不尊重的行為. 人名那麼多, 我們一個個去修正, 也不知道會修正到何年何月.

我的想法是, 可不可以先偵測出使用者輸入的是繁體字, 那就完全不要再做繁轉繁的轉換了? 我們的程式開發商說, 因為unicode的中簡體和繁體的編碼中有重複的關係, 所以他們無法在程式碼中就這點做判斷. 但是, 我想在你們收到繁體的input的時候, 你們應該有機會檢查出到底這個字是簡體的編碼, 或是繁體的編碼. 那麼, 你們的程式裡面, 應該就可以判斷決定, 是否繼續進行 繁體轉繁體的動作。

把繁體轉成繁體, 除了 "松"這個字, 還有劉"發"泉->"髮", 干->幹..等等, 不勝枚舉. 這些字如果出現在人名, 那就非常不禮貌了.

**Comment by shtse8** [comment]
沒辦法判斷的吧
是不是繁體字在你們的系統是最清楚的
編碼上是沒有明顯區分簡繁的區域
因為簡繁相差處才只是區區兩三千字
我的平台做法是如果是繁體內容就不要再處理
2016年2月3日 上午10:13於 "jasliu" <notifications@github.com>寫道：

**Comment by jasliu** [comment]
shtse8 您好,
請問你們的網頁是預設為 big-5 嗎? 我們這邊是預設為 unicode.
我們的程式開發商說因為 unicode 的關係, 所以無法處理. 請問他這樣的說法是正確的嗎?

**Comment by thatblstudio** [comment]
提供一个蹦出来的最简单的实现方法。
如果你是一大段输入，中间有名字：用opencc翻译，然后取翻译之后的字符串和原字符串进行比较，如果差距较大则认为原文是简体，如果差距不大则认为是繁体。为了避免除了中文以外的字符干扰，可以只取中文这部分的字符，Unicode定位中文块还是很方便的。
如果输入只有姓名或者输入较少：那么在输入的时候提供选项，让用户决定是否使用系统的自动翻译即可。

**Comment by lotem** [comment]
是否所求爲：凡遇簡化字則轉換爲對應傳統漢字，傳承字（未簡化）則不轉換？
這可通過條改轉換字典中「一簡對多繁」字多個結果的順序達成。
即，對於被合併簡化的傳承字，其爲「一簡對多繁」，要把該字本身作爲第一結果。例如：松—松 鬆、干—干 乾。可以寫腳本或用一個正則表達式在字典中搜尋本字不在首位的記錄。但對這種情況：簡化字原本是一個不常見的古字，宜優先當作簡化字轉換。例如：广—廣 广、适—適 适。
對於簡化字，若爲一簡對多繁，也可以跟據應用場景調整優先出字的順序。例如按人名中的使用率：发—發 髮、纤—纖 縴。這部分大致不用調整。

**Comment by lotem** [comment]
補充一句，如果只用來處理人名，那麼只須使用定製的字一級轉換表，詞語一級轉換似無必要採用，也好免去審查詞語中轉換不當的辛勞。

**Comment by LNDDYL** [comment]
被合併簡化的傳承字應該被應用程式標註出來。

**Comment by LNDDYL** [comment]
因為「被合併簡化的傳承字」是錯誤轉換的重災區。
