### ISSUE TITLE
Please consider to switch to python 3.x for scripts

### ISSUE THREAD

**Issue by epico** [BYVoid/OpenCC#167]
Fedora 24 uses python 3.x as default now, please consider to switch to use 
python 3.x.

BTW, 2to3 tool can assist this switch.

**Comment by BYVoid** [comment]
Do you mean the script for dictionary generation?

**Comment by epico** [comment]
Yes, I mean the scripts in data/scripts.

**Comment by BYVoid** [comment]
Done. 81b7113da1a022cbc2f4e0dd835d7d27d15b080f
