### ISSUE TITLE
关于“線”和“綫”

### ISSUE THREAD

**Issue by daya-prac** [BYVoid/OpenCC#168]
貌似大陆标准中，“线”的繁体字应该是“綫”而不是“線”

**Comment by 910JQK** [comment]
《通用规范汉字表》確實是這麽寫的：
![_2016-02-17_20-44-59](https://cloud.githubusercontent.com/assets/2187099/13109846/d94d3f44-d5b6-11e5-8026-5e1562398aa7.png)

**Comment by jakwings** [comment]
opencc 沒有提供大陆繁簡標準轉換吧？

**Comment by daya-prac** [comment]
@jakwings 啊？

**Comment by daya-prac** [comment]
@jakwings README 里面写了支持的呀——

> Open Chinese Convert (OpenCC, 開放中文轉換) is an opensource project for conversion between Traditional Chinese and Simplified Chinese, supporting character-level conversion, phrase-level conversion, variant conversion and regional idioms among **Mainland China**, Taiwan and Hong kong.

**Comment by lotem** [comment]
@daya-prac 大陸的規範字形是指「簡化字」。

**Comment by daya-prac** [comment]
@lotem 感谢公子解答，不过我还有个疑惑：
* s2hk 是简化字转化为香港繁体
* s2tw 是简化字转化为台湾繁体

那 s2t 是什么呢？

**Comment by osfans** [comment]
t是opencc標準

**Comment by BYVoid** [comment]
opencc標準是最小區分原則下的標準，即語義有差別能分則不合。
