### ISSUE TITLE
使用opencc做了简转繁的网站。太占内存了！

### ISSUE THREAD

**Issue by tooktoo** [BYVoid/OpenCC#170]
4万PV左右。不算上蜘蛛爬行。
估计应该也就占300多M的内存。但现在占了2G的内存。还经常档掉php-fpm。
因为我使用的opencc for php这个。好像不是你们出的。
现在我网站基本一天档一次机。搞的我不停重启php-fpm 
请问你们官方能不能出一个opencc php的版本？

**Comment by BYVoid** [comment]
謝謝告知。opencc node版本沒有聽說這個問題，可以考慮使用。

**Comment by tooktoo** [comment]
我现在网站运行的php写的。改成nodejs是不是成本太大了？你们这边就不能出个php的吗？
加上网站语言用php还是多些啊~！

**Comment by buganini** [comment]
試試php-bsdconv搭配bsdconv-opencc ?
https://github.com/buganini/bsdconv
https://github.com/buganini/php-bsdconv
https://github.com/buganini/bsdconv-opencc

**Comment by buganini** [comment]
還是你的代碼忘記呼叫opencc_close()?

**Comment by BYVoid** [comment]
如果可以，最後能夠提供貴站調用opencc的代碼

**Comment by tooktoo** [comment]
肯定要关闭opencc_close()啊！
代码就是用的就是openccfor php的。
https://github.com/NauxLiu/opencc4php

**Comment by owyowoos** [comment]
我也打算用opencc4php，很占内存么？

**Comment by tooktoo** [comment]
非常占，能让你的php-fpm直接档掉。。。apache也直接档掉。。。我现在每小时重启一次php-fpm。
每天重启机器一次。。。。你就知道了。。。

**Comment by pkujhd** [comment]
@tooktoo, 我看了下opencc4php的实现，代码在104行(如果你使用的是php7.0+）有memleak， 请注释掉
Z_TYPE_INFO_P(zod) = IS_NULL；这个语句，这个语句会造成56bytes的zval的泄露，如果是php5的话，请注释掉102行的代码。 仅仅做了简单的测试，如果需要应用在你的web站点上，请多测试一下，
