### ISSUE TITLE
NPM Version Issue

### ISSUE THREAD

**Issue by sorpaas** [BYVoid/OpenCC#173]
According to [Semantic Versioning 2.0.0](http://semver.org/), ppending a hyphen is considered a per-release version. Pre-release versions have a lower precedence than the associated normal version.

As a result, running [node-semver](https://github.com/npm/node-semver) with `semver.maxSatisfying` with version `1.0.3-1` would results in `1.0.3` (because both `1.0.3-1` and `1.0.3` co-exist in the repo). This causes some other applications that indirectly use `packages.json`, for example, [npm2nix](https://github.com/NixOS/npm2nix) to fail.

Although this can be fixed by appending with equal sign as `=1.0.3`, maybe consider to publish a new version, for example, `1.0.4`?

**Comment by BYVoid** [comment]
Thank you. I will release 1.0.4 soon.
