### ISSUE TITLE
使用browserify 轉換含opencc的js會出錯

### ISSUE THREAD

**Issue by desjoyce** [BYVoid/OpenCC#176]
Hi,
我在現有專案(須使用browserify )中,引用opencc後,
再使用browserify 打包會有下列錯誤,
請問有沒有人遇過呢?

browserify 指令:browserify src/start.js > public/js/bind.js

Error: Cannot find module '../build/Release/binding' from '/home/xxxx/nodejs/xxxx-nodejs/node_modules/opencc/node'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by jakwings** [comment]
browserify 是遊覽器前端應用，不適用於 opencc 這種需要在地編譯二制包的工具。可自行在前端提供 API 供調用後端的 opencc。

**Comment by desjoyce** [comment]
感謝~已自行找了前端可使用的api
