### ISSUE TITLE
請問iOS該如何正確導入？

### ISSUE THREAD

**Issue by ShawnQQ** [BYVoid/OpenCC#180]
請問是否有iOS 使用openCC的相關文件？安裝方法？
載了iOS的sample code 使用方法看似簡單
但具體該導入哪些文件卻一直導入不成功
或者有什麼地方該特別設定嗎？
感謝

**Comment by DaengGWokFook** [comment]
@ShawnQQ 目前ios系統有中州韻輸入法嗎?

**Comment by ShawnQQ** [comment]
@DaengGWokFook 沒看到耶...輸入法沒研究

**Comment by vbonluk** [comment]
同问啊！独立开一个project，完全不能run。
