### ISSUE TITLE
请问一下可以支持iOS吗？

### ISSUE THREAD

**Issue by ghost** [BYVoid/OpenCC#181]
我尝试gyp和cmake都不能成功生成iOS的项目, 但是我可以直接运行您给的iOS Sample. 
导入了文件之间之后, 一直提示gtest这个路径下的头文件都找不到.. 
谢谢解答..

**Comment by vbonluk** [comment]
同问啊！独立开一个project，完全不能run。

**Comment by XQS6LB3A** [comment]
写了一个支持全平台的framework [SwiftyOpenCC](https://github.com/XQS6LB3A/SwiftyOpenCC)

**Comment by ucoker** [comment]
@ghost 解决了吗？ 直接引入，也是提示缺少'gtest/gtest.h'

**Comment by ddddxxx** [comment]
@ucoker 删除所有`*Test.cpp`文件。你还可以尝试我在楼上提及的 SwiftyOpenCC。

**Comment by ucoker** [comment]
@ddddxxx 尝试制作成Framework，可成功使用了。谢谢

**Comment by hustshawn** [comment]
你们起个docker不是什么都解决了么   管他什么7788平台
