### ISSUE TITLE
簡轉繁建議

### ISSUE THREAD

**Issue by kyleskimo** [BYVoid/OpenCC#183]
TWVariants.txt 建議應該要加入:
檐        簷
鉢        缽
嫋        裊
繮        韁

STCharacters.txt 則建議要加入下列漏字:
𬶍    鮀
𬶋    鮈
𬶏    鮠
𬶟    鯻
𬸪    鷭
丬 爿
凼 氹
𨦎    䥑

**Comment by kunki** [comment]
“䥑”的简化字是“鿏”，不是“𨦎”。“鿏”字收于Unicode8.0标准，是根据《通用规范汉字表》追加的。
“凼 氹”只是普通的异体字关系。

**Comment by kyleskimo** [comment]
TWVariants.txt 再建議加入:
孃	娘
賬	帳

STPhrases.txt 有問題的地方:
丁丁炒面	丁丁炒**面**
乌冬面	烏冬**面**
面 => 麪

种姓制度	種姓**製**度
製 => 制

钮扣	鈕**釦**
釦 => 扣

纽扣	**鈕釦**
鈕釦 => 紐扣

须后水	**須**後水
須 => 鬚

熏衣草	**熏**衣草
熏 => 薰

涂尔干	涂爾**干**
干 => 幹

冲压	**衝**壓
冲压机	**衝**壓機
衝 => 沖

菲舍尔	菲**捨**爾
捨 => 舍

**Comment by kyleskimo** [comment]
其實我修改的地方比列出來的還多, 因為目前很多用字已經有些差異..
列出覺得比較重要的..

TWVariants.txt 再建議加入:
幷	并
柺	枴
礆	鹼
齶	顎
燬	毀
譭	毀

STPhrases.txt 有問題的地方:
也舍下	也**舍**下
=> 捨

对冲基金	對**衝**基金
=> 沖

未松下	未**松**下
松狮犬	**松**獅犬
=> 鬆

复员军人	**複**員軍人
来复枪	來**複**槍
来复线	來**複**線
=> 復

千里姻缘一线牵	千**裏**姻緣一線牽
=> 里

给我干脆	給我**干**脆
=> 乾

核准的	覈**準**的
=> 准

受聘于	受聘**于**
=> 於

抵**觸**	牴觸
=> 触(前面要簡體)

**Comment by kyleskimo** [comment]
加里宁	加**裏**寧
加里宁格勒	加里寧格勒
加里宁格勒州	加**裏**寧格勒州
布里斯托	布里斯托
布里斯托尔	布**裏**斯托爾
布里斯托尔海峡	布里斯托爾海峽
马里亚纳	馬里亞納
马里亚纳海沟	馬**裏**亞納海溝
马里亚纳群岛	馬里亞納羣島

上述都是摘自 STPhrases.txt
為了簡轉繁的一致性, "裏" 應該都要用"里"

干球温度	**幹**球溫度
"幹" => "乾"

僵尸	殭屍
僵尸网络	**僵**屍網絡
為了簡轉繁的一致性, "僵" => "殭

战略防御倡议	戰略防**御**倡議
"御" => "禦"

炼金	鍊金
炼金术	鍊金術
炼金术士	**煉**金術士
為了簡轉繁的一致性, "煉" => 鍊

杠杆	槓桿
杠杆收购	**杠杆**收購
為了簡轉繁的一致性, "杠杆" => 槓桿

**Comment by BYVoid** [comment]
感謝
https://github.com/BYVoid/OpenCC/commit/957fbedbe3f50e7c4c84eb17a0a2bc8c0c416616
