### ISSUE TITLE
轉換建議 "type": "text"

### ISSUE THREAD

**Issue by kyleskimo** [BYVoid/OpenCC#184]
修改 s2tw.json & s2twp.json..等配置文件, 如果使用了 "type": "text" 之後, 
直接使用STCharacters.txt、STPhrases.txt...等進行轉換, 轉換速度就會變得異常緩慢.
使用ocd, 轉換100MB約兩分多鐘.
使用txt, 轉換100MB, 花了四分鐘才轉換出3MB, 只好中斷..

雖然在底下的緣由有提到
https://github.com/BYVoid/OpenCC/wiki/%E7%B7%A3%E7%94%B1

> 平面文本數據庫格式方便閱讀和修改，ocd格式是OpenCC構造出的Double Array Trie數據結構，基於darts-clone，使用其可以大大提供轉換速度。OpenCC還提供了詞庫轉換程序，可以自由在兩種格式之間轉換。

然而, 如果用opencc_dict.exe 將 STPhrases.txt (最大的txt) 轉成 STPhrases.ocd, 不到兩秒鐘, 碼表都來不及按.

所以有一個建議,  即使 使用者指定使用text格式, 
讓opencc可在後台(記憶體/內存)先將  STPhrases.txt 轉成 STPhrases.ocd, 
再間接使用後台轉出來的 STPhrases.ocd , 我相信轉換100MB的時間不會差兩秒.

**Comment by lotem** [comment]
讚。
繼續這一討論：我猜想對足夠小的文件來說，也許不轉換爲 ocd 纔是更高效的——爲此需要做一系列實驗，找出可以高效訪問 txt 格式數據的上限，即 txt 文件小於一個定值時直接加載，否則即時轉換爲 ocd。

**Comment by kyleskimo** [comment]
這兩個禮拜以來, 因為想讓簡繁轉換正確率提高, 所以利用一些個人時間去修改opencc \data\dictionary 底下各個txt檔案.
其中STPhrases.txt當然是花最多時間去增修的,  修改了兩百餘處, 並增加四千多行.
增修每一行都需要逐一確認測試轉換是否正確, 所以也就測了應該有超過千次.
有些是使用opencc-gui.exe的介面直接測試轉換效果, 
也有拿整部英漢詞典、武俠小說或法規來使用opencc.exe進行轉換後, 再做全文比對.

所以為了快速且方便的轉換大檔案, 我做了簡單的批次檔, 內容如下:
opencc_dict.exe -i TSCharacters.txt -o TSCharacters.ocd -f text -t ocd
opencc_dict.exe -i STCharacters.txt -o STCharacters.ocd -f text -t ocd
opencc_dict.exe -i TWVariants.txt -o TWVariants.ocd -f text -t ocd
opencc_dict.exe -i STPhrases.txt -o STPhrases.ocd -f text -t ocd

就使用經驗來說, 上述批次檔執行起來都是畫面一閃而逝, 不會超過一秒,  
這樣再用TC檔案管理程式,  使用opencc.exe命令, 搭配參數?-c s2tw.json -i %N -o %N.cht
就能快速的進行檔案轉換, 不用每次都到dos視窗, 或是在opencc-gui介面選檔案.

**所以我會建議只要是json設定為"type": "text" 不管檔案大小都在背景(後台)轉換ocd.**
也因為這個"type": "text"模式, 不是預設(默認)值, 並不會影響原先的使用者.

**Comment by BYVoid** [comment]
謝謝建議。

如果轉換的是非常短的文字，生成詞典的開銷太大。所以決定還是用戶根據需要自己轉換。
