### ISSUE TITLE
Can't build under Visual Studio 2015.

### ISSUE THREAD

**Issue by xpol** [BYVoid/OpenCC#188]
Lots of warnings.
And got 10+ build errors.

After add `-DBUILD_SHARED_LIBS=OFF` the build errors gone, but still lots of warnings:

```
    6615 Warning(s)
    0 Error(s)
```

**Comment by kyleskimo** [comment]
目前opencc這裡 ver.1.0.4 僅有原始碼,  要比較舊的 2014 年 1.0.1 版才有提供 win32 & win64 執行檔.

一二十年前, 雖然有在 UNIX 系統下使用 gcc / make 編譯簡單程式的經驗, 只要相關環境與設定都對了,  步驟不會很多..
但經過多年, 要在現今不同的 Visual Studio 2015 環境下編譯, 實在是難以了解, 裝了以後, 環境也弄不出來..

相信在了解編程的高人手上, 編譯應該只是幾個步驟而已.
希望有高人能提供編譯好的執行檔...
非常感謝.

**Comment by Prcuvu** [comment]
Those warnings are hardly readable.
You just would NOT like to mess with C++ templates.

**Comment by gucong3000** [comment]
https://www.npmjs.com/package/windows-build-tools
用这个工具，可以不装Visual Studio
(求翻译)

**Comment by gucong3000** [comment]
@xpol Fixed in the latest master branch.
