### ISSUE TITLE
Compatibility with XML

### ISSUE THREAD

**Issue by FreddyVall** [BYVoid/OpenCC#191]
Hello,

Is the tool compatible with XML files?

Thank you

**Comment by jakwings** [comment]
Do you want to convert Chinese characters in XML files? Since ASCII characters are not changed, it is fine to convert XML files directly, except that the escaped characters `&#XXXX;` are not affected too.

**Comment by BYVoid** [comment]
Only Chinese characters are afftected.

**Comment by FreddyVall** [comment]
yes correct a standalone XML file with Chinese text 

here is a sample below (ZH_CN)

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<translation-batch sender="XXXXX" generated="2016-07-20T16:15:09+02:00" recipient="XXXXX" batch-id="3" source="CNFULL" original-language="zh" target-language="en" tech-domain="1">
    <publication pub-id="2982664">
        <translation-item text-type="Title">一种移动充电器</translation-item>
        <translation-item text-type="Abstract"><p num="1">本发明一种移动充电器包括一壳体和设置在壳体内的电芯，还包括一导电片组，正极配电单元及负极配电单元；正极配电单元及负极配电单元设置在壳体二端相对电芯的正、负极处；导电片组设置在壳体内,以电性连接正极配电单元及负极配电单元,再在壳体组设充电单元,并使充电单元的正、负极端脚经正极配电单元及导电片组、负极配电单元,而与电芯的正、负极电性连接,另又在壳体上设置有供电单元,且使供电单元的正、负极接脚经正极配电单元及导电片组、负极配电单元,而与电芯的正、负极电性连接，藉此，使交流电经交流充电器转为直流电后由充电单元对电芯进行充电，再使电芯由供电单元输出直流电，以随时随地提供需使用直流电源的电子产品充足的电力者。</p></translation-item>
        <translation-item text-type="Description"><invention-title id="tilte1"><b>一种移动充电器</b>     	  
			</invention-title>     	  
			<p id="p0001" num="0001">技术领域     	  
	</p>     	  
			<p id="p0002" num="0002">本发明涉及一种移动充电器，尤指一种可随时随地可提供需使用直流电源作动力的电子产品充足电力的充电器结构。。     	  
	</p>     	  
			<p id="p0003" num="0003">背景技术     	  
	</p>     	  
			<p id="p0004" num="0004">随着科技的发达，各式电子、电气产品，如：移动电话、笔记型计算机、数字相机、个人数字助理〔PDA〕等相继问世，提供给人们生活极大的便利性。 　　移动电话等数码产品作动能源主要来自于直流电力，其通常配备有一可充电的内置电池，以供应所需电力，但内置电池因蓄电容量有限，尤其随着移动电话等的轻薄小型化，其内置电池的体积及电容量相对缩小，故电力很快消耗殆尽，无法长时间持续使用，因此，使用者必须随身携带交流充电器以随时充电保持其功能的运作；然，由于使用移动电话时，大多是在户外，故即便随身携带交流充电器欲进行充电，亦因无适当插接之交流电插座而难以实施，而造成使用上极大的麻烦与不便。 　　缘是，本发明人有鉴于现有移动电话、数字相机等电子、电气产品其内置电池的蓄电量有限，且使用地点常于户外等难以进行交流充电之场所，以致时常造成移动电话等产品无法使用的情况，乃藉其多年于相关领域的制造及设计经验和知识的辅佐，并经多方巧思后，研创出一种可在移动状态随时随地为移动电话等产品提供充足电能之充电器结构。。	   	 	 
	</p>	 	 	 	 
			<p id="p0005" num="0005">发明内容

**Comment by jakwings** [comment]
You should make it clear for yourself which parts of the XML documents should be convert, and I'm afraid this tool cannot help with that.
