### ISSUE TITLE
Invalid format: Error parsing JSON

### ISSUE THREAD

**Issue by callzhang** [BYVoid/OpenCC#194]
Can't understand this error, I am passing .txt file in the CL
`$ opencc -i wiki_corpora.txt -o wiki_corpora_chs.txt -c mix2zhs.ini`

**Comment by lotem** [comment]
You might be using a configuration file of an older format (0.x), with the new (1.x) opencc executable.
Try updating your open data files and use `t2s.json` instead.

**Comment by callzhang** [comment]
I have installed the opencc from `brew install opencc`, and it didn't include the `.ini` file. So I just downloaded from google. Can you tell me where to find the .ini files?

**Comment by callzhang** [comment]
Got it. Thank you!

**Comment by ShawXh** [comment]
I also met this problem. Because initially, I use yum install opencc and I found that the version of the opencc is 0.x. And when I use git clone and make install, the version is 1.x. So I followed the lotem's advice and the problem is solved.
