### ISSUE TITLE
在命令行下, 轉換小文件檔案, 無法正確簡轉繁

### ISSUE THREAD

**Issue by kyleskimo** [BYVoid/OpenCC#195]
例如, test.txt, 內容只有一行, 四個字:
只鸡斗酒

在命令行下執行:
opencc -c s2t.json -i test.txt -o test.txt.cht

結果是:
**只**雞斗酒

如果是使用OpenCC GUI版, 或是命令行下轉換大檔案, 則可以得到正確的結果:
**隻**雞斗酒

**Comment by lotem** [comment]
會不會是因爲文本文件包含BOM字符。

**Comment by kyleskimo** [comment]
抱歉, 找到原因了, 因為在dos命令下測試, 目錄切換較為不易.
所以用到原始opencc的STPhrases, 造成轉換錯誤..
不是程式有問題..
