### ISSUE TITLE
请问怎么添加新的转化词？

### ISSUE THREAD

**Issue by czly** [BYVoid/OpenCC#198]
比如繁体转化成简体是阿公，但是通常都应该转化成爷爷

**Comment by zairwolf** [comment]
同问

**Comment by iblis17** [comment]
這裡有字典檔 https://github.com/BYVoid/OpenCC/tree/master/data/dictionary

**Comment by iblis17** [comment]
https://github.com/BYVoid/OpenCC/tree/master/data/config 這裡的各種設定 會指定要用哪個字典

**Comment by zairwolf** [comment]
谢谢。每次修改完字典后重启apache发现没生效。是要从新编译opencc吗？ubuntu

**Comment by BYVoid** [comment]
不需要重新編譯，但是需要重新生成詞典。建議創建一個新的字典，並且修改配置。

**Comment by zairwolf** [comment]
能否提供一个文档或方法可以查看怎样从新生成词典？谢谢。是要把txt convert to ocd 吗？

**Comment by czly** [comment]
我想在原有繁体转简体的基础上，添加我的扩展词典，却不知操作步骤

**Comment by iblis17** [comment]
用法很簡單：
1. 準備設定檔，以 `config/s2t.json` 為範例
```shell
$ cp config/s2t.json demo.json
$ diff -u demo.json config/s2t.json
--- demo.json   2017-02-02 14:33:51.538004653 +0800
+++ config/s2t.json     2017-02-02 14:27:50.587766778 +0800
@@ -16,10 +16,6 @@
       }, {
         "type": "ocd",
         "file": "STCharacters.ocd"
-      },
-      {
-        "type": "text",
-        "file": "./magic.txt"
       }]
     }
   }]
```

2. 新增一個 `magic.txt`
注意此處 *一定* 要用 `tab` 作為分割字元（註：github 貼上後變成空白，請見諒
```shell
$ cat magic.txt
雲端  屁股
```

3. 準備需要被轉換的文件
```shell
$ cat test.txt 
雲端大數據
```

4.
```shell
$ opencc -c demo.json -i test.txt
屁股大數據
```
🎉

**Comment by hustshawn** [comment]
@iblis17 如上例所示，`magic.txt` 文件所在的目錄是？我`./magic.txt`是指 `xxx/data/config/`嗎？

**Comment by iblis17** [comment]
@hustshawn `./magic.txt` 所在的目錄是你的 working dir ；不確定的話，給全路徑吧。

**Comment by liuwind** [comment]
> 
> 
> 用法很簡單：
> 
>     1. 準備設定檔，以 `config/s2t.json` 為範例
> 
> 
> ```shell
> $ cp config/s2t.json demo.json
> $ diff -u demo.json config/s2t.json
> --- demo.json   2017-02-02 14:33:51.538004653 +0800
> +++ config/s2t.json     2017-02-02 14:27:50.587766778 +0800
> @@ -16,10 +16,6 @@
>        }, {
>          "type": "ocd",
>          "file": "STCharacters.ocd"
> -      },
> -      {
> -        "type": "text",
> -        "file": "./magic.txt"
>        }]
>      }
>    }]
> ```
> 
>     1. 新增一個 `magic.txt` 的字典
>        注意此處 _一定_ 要用 `tab` 作為分割字元（註：github 貼上後變成空白，請見諒
> 
> 
> ```shell
> $ cat magic.txt
> 雲端  屁股
> ```
> 
>     1. 準備需要被轉換的文件
> 
> 
> ```shell
> $ cat test.txt 
> 雲端大數據
> ```
> 
> 
> ```shell
> $ opencc -c demo.json -i test.txt
> 屁股大數據
> ```
> 
> 🎉

不好意思程式麻瓜，請問有影片教學嗎?首頁好像也沒提到這詞庫用法。
openCC是python寫的?
謝謝
