### ISSUE TITLE
请问，现在如何在python中使用OpenCC？

### ISSUE THREAD

**Issue by retsyo** [BYVoid/OpenCC#200]
http://pypi.python.org/pypi/opencc-python/ 是老版本的OpenCC。谢谢

我试着将新版本的 TWPhrasesRev.txt（也使用过TWPhrases.txt），用opencc_dict.exe 转换为 TWPhrasesRev.ocd，然后编写zhs2zhtp.ini
【zhs2zhtp.ini】
title = simp_to_trad_pharase
description = Standard Configuration for Conversion from Simplified Chinese to Traditional Chinese
dict0 = OCD TWPhrasesRev.ocd
dict1 = OCD simp_to_trad_characters.ocd
【/zhs2zhtp.ini】

并修改**init**.py
BUILDIN_CONFIGS = {
    's2t': os.path.join(DATA_PATH, 'zhs2zht.ini'),
    't2s': os.path.join(DATA_PATH, 'zht2zhs.ini'),
    'mix2t': os.path.join(DATA_PATH, 'mix2zht.ini'),
    'mix2s': os.path.join(DATA_PATH, 'mix2zhs.ini'),
    'zhs2zhtp': os.path.join(DATA_PATH, 'zhs2zhtp.ini'),
}

但是，依然没法将“鼠标”变换成“滑鼠”。

**Comment by BYVoid** [comment]
可以考慮試用 ctypes 
https://docs.python.org/2/library/ctypes.html#module-ctypes

**Comment by osfans** [comment]
https://github.com/osfans/PIME/tree/master/python/opencc

这里有一版

**Comment by osfans** [comment]
不过没有实现通过ctypes生成ocd 好像很麻烦的样子

**Comment by retsyo** [comment]
谢谢

**Comment by Hopkins1** [comment]
Also take a look at a python implementation of opencc. It uses the opencc data files.

[https://github.com/yichen0831/opencc-python](https://github.com/yichen0831/opencc-python)
