### ISSUE TITLE
干锅鸡 -> 幹鍋雞

### ISSUE THREAD

**Issue by hanfeisun** [BYVoid/OpenCC#201]
简体转繁体：http://opencc.byvoid.com/

正确的写法应该是“乾鍋雞“吧

**Comment by kyleskimo** [comment]
"干 ->乾幹干" 的問題還有很多, 略舉幾例如下:
干炒牛河 -> 幹炒牛河
松脆饼干 -> 鬆脆餅幹
干李子 -> 幹李子
干皮症 -> 幹皮症
不干燥 -> 不幹燥

以上都應該是要轉成"乾"才對.

我覺得要提高正確率沒別的辦法, 就是自己一行一行的增加到轉換表.
原本 STPhrases.txt 有 48933 行
我已經一行一行測試並增加到了六萬多行, 也就是比原本多了一萬多行簡轉繁的數據.
如果沒有增加這些, 在轉換一些簡體書的過程中, 就會出現這一萬多個可能轉換有問題的地方.

**Comment by hanfeisun** [comment]
我試過用某中文輸入法輸入繁體詞組，發現  “乾鍋雞 乾炒牛河 乾燥 鬆脆餅乾” 都可以正確輸入。
對於這種轉換時候容易出錯的字，也許只需要將一個輸入法的“詞庫”導入進來即可。。

**Comment by kyleskimo** [comment]
目前 opencc的STPhrases.txt 估計也有部分是從"國語辭典"導入進來的.
導入現有詞庫是很方便, 但是如果沒有人工過濾, 可能也會有一些問題.
因為像是新注音輸入法, 會自動依據輸入的前後字而有部分調整.
然而, opencc 對一個字串的處理方式是從前面處理到後面..

例如 opencc 有個 "个中	-> 箇中" , 單純兩個字本身沒問題, 但會影響到有用到 "個中" 的字串.
像是底下的轉換都不正確了, 我就得自己增加了數十行來解決這個問題.
数个中的 -> 數箇中的
多个中间商 -> 多箇中間商
一个中年 -> 一箇中年
一个中立 -> 一箇中立
一个中等 -> 一箇中等

**Comment by hanfeisun** [comment]
这种问题能不能通过NLP中的“词性标注”方法来解决呢？

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/commit/0306285d552db491b61b4909c4143d45b1bd0f5a
