### ISSUE TITLE
請添加新功能：OpenCC支援正則運算式

### ISSUE THREAD

**Issue by tsiupokleung** [BYVoid/OpenCC#202]
OpenCC如果可以支援正則運算式的話，有些問題可以很好解決，比如用在輸入法的時候，”干.*酒“就很容易正確轉換了，再者，OpenCC的實際用途應遠超簡繁轉換這個簡單的程式，它更可以勝任作爲一個翻譯機器，比如在輸入法中，可以輸入普通話透過OpenCC轉換爲粵語

**Comment by 2d-gate** [comment]
正則表的維護（出錯時的除錯）難度其實挺高的...
"干.*酒" 這條轉換做起來可能很驚險...

**Comment by tsiupokleung** [comment]
使用正則是一個選擇，一種解決問題的工具，用在有需要的地方，達到一定目的，如果某些地方不需要它的話就可以不用，這正是opencc存在的原因。 
簡繁轉換不可能達到百分之百正確的。同時opencc也可以作爲更多的文字轉換功能。所以有必要加入這個功能
希望可以提供這樣的選擇。

**Comment by jakwings** [comment]
有沒有具體到配置語法、處理流程和算法複雜度的可行方案？

**Comment by lotem** [comment]
类似的讨论：
https://github.com/BYVoid/OpenCC/issues/175
