### ISSUE TITLE
运行崩溃

### ISSUE THREAD

**Issue by comword** [BYVoid/OpenCC#206]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bb470d in opencc::DartsDict::MatchPrefix(char const*) const ()
   from /usr/lib/x86_64-linux-gnu/libopencc.so.2
(gdb) backtrace
#0  0x00007ffff7bb470d in opencc::DartsDict::MatchPrefix(char const*) const ()
   from /usr/lib/x86_64-linux-gnu/libopencc.so.2
#1  0x00007ffff7bb9245 in opencc::DictGroup::MatchPrefix(char const*) const ()
   from /usr/lib/x86_64-linux-gnu/libopencc.so.2
#2  0x00007ffff7bb22e8 in opencc::Conversion::Convert[abi:cxx11](char const*) const () from /usr/lib/x86_64-linux-gnu/libopencc.so.2
#3  0x00007ffff7bb2af5 in opencc::Conversion::Convert(std::shared_ptr<opencc::Segments> const&) const () from /usr/lib/x86_64-linux-gnu/libopencc.so.2
#4  0x00007ffff7bb34d0 in opencc::ConversionChain::Convert(std::shared_ptr<opencc::Segments> const&) const () from /usr/lib/x86_64-linux-gnu/libopencc.so.2
#5  0x00007ffff7bb391b in opencc::Converter::Convert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
   from /usr/lib/x86_64-linux-gnu/libopencc.so.2
#6  0x000055555555e5ed in ConvertLineByLine() ()
#7  0x000055555555d4b6 in main ()

**Comment by comword** [comment]
这是Ubuntu 16.10自带软件包libopencc2 的问题..

**Comment by math120908** [comment]
Can use 
```bash
for i in hk2s s2hk s2t s2tw s2twp s2tw t2hk t2s t2tw t2tw t2sp ; do curl -s https://raw.githubusercontent.com/BYVoid/OpenCC/master/data/config/${i}.json > /usr/share/opencc/${i}.json; done
```
to fix the bug .
