### ISSUE TITLE
请问：繁->简  单字转换支持的范围

### ISSUE THREAD

**Issue by HYDRAwang** [BYVoid/OpenCC#207]
你好
繁->简   单字转换支持的范围 是哪些繁体字会被转换？是否Unicode3.0包含的全部繁体字（有对应unicode3.0简体字的)都会被正确转换为简体字？

**Comment by sgalal** [comment]
https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TSCharacters.txt
