### ISSUE TITLE
Config::NewFromString throws the exception when path does not contain trailing slash

### ISSUE THREAD

**Issue by bunhere** [BYVoid/OpenCC#219]
Below line throws the exception.
```
config.NewFromString("some config", "/some/directory/containing/opencc/data")
```

Just adding "/" to the path like below looks fine.
```
config.NewFromString("some config", "/some/directory/containing/opencc/data/")
```

I am not sure whether it is intended, but, I prepared naive patch for it.
https://github.com/bunhere/OpenCC/commit/7491bf9c4e5c948db27a6f9b7fa72d761a73ffcd

**Comment by BYVoid** [comment]
Thanks. Could you please submit a pull request?
