### ISSUE TITLE
centos下编译执行到Linking CXX executable opencc_phrase_extract出错

### ISSUE THREAD

**Issue by shadowJF** [BYVoid/OpenCC#222]
make[3]: Entering directory `/home/liangjfc/opencc-1.0.4/build/rel'
make[3]: Leaving directory `/home/liangjfc/opencc-1.0.4/build/rel'
make[3]: Entering directory `/home/liangjfc/opencc-1.0.4/build/rel'
[ 40%] Linking CXX executable opencc_phrase_extract
CMakeFiles/opencc_phrase_extract.dir/PhraseExtract.cpp.o: In function `Extract(std::vector<std::string, std::allocator<std::string> > const&,
std::string const&)':
PhraseExtract.cpp:(.text+0x30): undefined reference to `std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_o
stringstream(std::_Ios_Openmode)'
PhraseExtract.cpp:(.text+0x94): undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(std::string const&,
 std::_Ios_Openmode)'
PhraseExtract.cpp:(.text+0xa3): undefined reference to `std::allocator<char>::allocator()'
PhraseExtract.cpp:(.text+0x109): undefined reference to `std::allocator<char>::~allocator()'
PhraseExtract.cpp:(.text+0x122): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_t
raits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::a
llocator<char> > const&)'
PhraseExtract.cpp:(.text+0x131): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string
()'
PhraseExtract.cpp:(.text+0x140): undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::~basic_ifstream()'
PhraseExtract.cpp:(.text+0x186): undefined reference to `std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str()
const'
PhraseExtract.cpp:(.text+0x219): undefined reference to `std::basic_ofstream<char, std::char_traits<char> >::basic_ofstream(std::string const&
, std::_Ios_Openmode)'

全都是undefined reference的错，怎么解决啊？

**Comment by gucong3000** [comment]
```
npm i git+https://github.com/gucong3000/OpenCC.git#node-pre-gyp
```
试试这个吧

**Comment by sgalal** [comment]
报错信息中的 undefined reference 都是标准库的内容，故不是 OpenCC 本身的原因。可能是在编译时没有链接标准库 `-lstdc++`。
