### ISSUE TITLE
可否考虑支持 node-pre-gyp

### ISSUE THREAD

**Issue by Mooo123asd** [BYVoid/OpenCC#228]
node-gyp  安装繁琐且有几率失败暂且不提.
在本地开发环境中需要部署Py或VC Build Tools也可以接受
但是如果在生产库中部署Py或VC Build Tools，在仅仅使用Opencc这一个模块的情况下，可能不是一个好的解决方案。

能否支持一下node-pre-gyp？ node-pre-gyp 貌似需要使用 AWS S3 ，也就是需要付费。
但是能否 参考下 https://github.com/bchr02/node-pre-gyp-github 的工具
使用 Github 来做 release 版本的储存？

**Comment by iblis17** [comment]
用 appveyor 來 build + artifact 如何?

**Comment by gucong3000** [comment]
顶楼上两位，我愿意尝试，成功的话我会发pr

**Comment by gucong3000** [comment]
https://github.com/WindWen/node-pre-opencc
这个项目貌似已经实现了此功能

**Comment by gucong3000** [comment]
我已在CI上编译成功
https://travis-ci.org/gucong3000/OpenCC
https://ci.appveyor.com/project/gucong3000/opencc

接下来需要搞定`node-pre-gyp-github `

**Comment by WindWen** [comment]
EthanWong其实也是我的Github账号之一，之所以没有继续进行 node-pre-opencc 是因为个人可能觉得这样做不大合适

没有找到很好的办法进行规范化处理 fork的项目需要每次作者更新后，才能手动更新 node-pre-opencc 而且版本号也很难以决策 最好的方案是跟随OpenCC的版本号 但会出现一个问题，并不是fork以后直接就可以产出 pre版本，还需要修改几个地方才可以 假设OpenCC 现在是 1.0.4 我更新了 node-pre-opencc 并推送到了npm中，但随后发现因为我的修改 造成了一些额外问题 需要修复 那么修复以后再次推送去npm的时候 版本号就必须比上一次的高 就会产生没办法和OpenCC的版本保持一致，如果不和OpenCC的版本保持一致 是不完美的妥协.

所以考虑后觉得 还是可能由原项目的作者来进行适配pre更合理，这样子对用户的使用其实更加的便利 而且因为pre带来的问题 也变得更加容易解决

但是如果你愿意做相关的PRE的支持 也是非常好的 没有什么问题 只不过是每个人不同的思维方式而已

**Comment by gucong3000** [comment]
https://github.com/gucong3000/OpenCC/releases
CI下编译，并发布二进制包到github成功
需要进一步补充32平台的

**Comment by gucong3000** [comment]
都搞定了，但是大陆地区网络原因，测试总是不成功，哪位能帮我测试一下啊？
```bash
npm i git+https://github.com/gucong3000/OpenCC.git
```

**Comment by gucong3000** [comment]
master分支已支持node-pre-gyp，但是 @BYVoid 还没有配置CI上的release发布权限，导致目前依然是客户端编译方式安装
