### ISSUE TITLE
Cmake compile always fails

### ISSUE THREAD

**Issue by aeolius** [BYVoid/OpenCC#229]
Scanning dependencies of target opencc_dict
[ 54%] Building CXX object src/tools/CMakeFiles/opencc_dict.dir/DictConverter.cpp.obj
[ 57%] Linking CXX executable opencc_dict.exe
CMakeFiles/opencc_dict.dir/objects.a(DictConverter.cpp.obj):DictConverter.cpp:(.text+0x94c): undefined reference to `opencc::ConvertDictionary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/tools/opencc_dict.exe] Error 1
make[1]: *** [src/tools/CMakeFiles/opencc_dict.dir/all] Error 2
make: *** [all] Error 2

**Comment by krrr** [comment]
i run into this bug too, but it has been fixed: https://github.com/BYVoid/OpenCC/commit/76caac3c6a350e5dbeff6b43802803af46812b74
