### ISSUE TITLE
请问如何在不编译整个项目的情况下生成OCD字典文件

### ISSUE THREAD

**Issue by XQS6LB3A** [BYVoid/OpenCC#230]
我把这个项目以 framework 的形式移植到了 macOS | iOS
[SwiftyOpenCC](https://github.com/XQS6LB3A/SwiftyOpenCC)

我希望我的项目能自动从这个项目中获取OCD字典文件，而不用编译整个源项目。

我也尝试使用项目中的cmake文件，然而才疏学浅，不知如何下手。

请问如何能够做到？

**Comment by BYVoid** [comment]
You can also refer to https://github.com/BYVoid/OpenCC/blob/master/node/dicts.gypi

**Comment by XQS6LB3A** [comment]
使用gpy是可行的

然而macOS并不预装gpy，我不希望我的项目有过多依赖
在不侵入OpenCC项目文件的条件下，无论是gpy,cmake还是重写makefile，要生成到原目标文件夹都相当麻烦。手动添加字典到自己的项目中似乎是更简便的方案

thanks anyway
