### ISSUE TITLE
Converter是线程安全的吗，是否可重入？

### ISSUE THREAD

**Issue by XQS6LB3A** [BYVoid/OpenCC#231]
就源代码来看似乎是线程安全的，但是我没有在文档中看到任何保证。

线程安全应该是个重要的特性，因为创建一个转换器的开销非常高，在线程安全的条件下，可以创建较少的转换器并在多个线程中重复使用。如果确实如此，建议在文档中增加说明。

**Comment by BYVoid** [comment]
是的，Unit test中有測試。
