### ISSUE TITLE
OpenCC 网站挂了

### ISSUE THREAD

**Issue by hotpxl** [BYVoid/OpenCC#235]
看来是 opencc.byvoid.com 的 DNS 挂了？

**Comment by iblis17** [comment]
hmm... it works for me

**Comment by hotpxl** [comment]
```
dig opencc.byvoid.com @8.8.8.8

; <<>> DiG 9.8.3-P1 <<>> opencc.byvoid.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 57095
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;opencc.byvoid.com.		IN	A

;; AUTHORITY SECTION:
byvoid.com.		271	IN	SOA	ns-cloud-c1.googledomains.com. cloud-dns-hostmaster.google.com. 2 21600 3600 259200 300

;; Query time: 8 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Mar 19 16:15:34 2017
;; MSG SIZE  rcvd: 125
```

**Comment by PuwenHsiao** [comment]
同掛

# dig @168.95.1.1 opencc.byvoid.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @168.95.1.1 opencc.byvoid.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 49619
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 3072
;; QUESTION SECTION:
;opencc.byvoid.com.             IN      A

;; AUTHORITY SECTION:
byvoid.com.             300     IN      SOA     ns-cloud-c1.googledomains.com. cloud-dns-hostmaster.google.com. 2 21600 3600 259200 300

;; Query time: 39 msec
;; SERVER: 168.95.1.1#53(168.95.1.1)
;; WHEN: Mon Mar 20 18:57:03 CST 2017
;; MSG SIZE  rcvd: 136

**Comment by lmmsoft** [comment]
Should be this one?  https://www.byvoid.com/en/project/opencc

**Comment by BYVoid** [comment]
多謝，已經修復

**Comment by hotpxl** [comment]
赞
