### ISSUE TITLE
黄宏 为何会被替换成 黃巨集？

### ISSUE THREAD

**Issue by imfantuan** [BYVoid/OpenCC#237]
台湾标准 台湾模式下。

**Comment by robaggio** [comment]
我也遇到过这个问题，因为电脑词汇里有一个宏->巨集的词条。建议考虑删掉这个词条，因为宏字太容易命中其他的人名了，比如李彦宏，而macro这个在一般文章里很少出现的。

**Comment by PuwenHsiao** [comment]
macro, 
台灣翻成 巨集
大陸翻成 宏

類似的問題: https://github.com/BYVoid/OpenCC/issues/224

**Comment by NicolJiang** [comment]
竟然是macro。。。
请问，词典在哪啊？

**Comment by iblis17** [comment]
這裡： https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TWPhrasesIT.txt#L107

**Comment by NicolJiang** [comment]
这个 是说要重新编译吗？

**Comment by iblis17** [comment]
重新編譯 可以。
或是用 `opencc_dict` 直接去產生 ocd file
