### ISSUE TITLE
Windows下编译警告信息

### ISSUE THREAD

**Issue by gucong3000** [BYVoid/OpenCC#242]
Windows环境下编译，尚有三个警告信息未修复

- [deps\darts-clone\darts.h(811): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (compiling source file ..\node\binding.cc)](https://ci.appveyor.com/project/Carbo/opencc/build/1.0.42/job/xe7ncoyu8cgdxicu#L27)
- [deps\darts-clone\darts.h(759): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) (compiling source file ..\node\binding.cc)](https://ci.appveyor.com/project/Carbo/opencc/build/1.0.42/job/9xykggnactkqvhxe#L27)
- [deps\darts-clone\darts.h(761): warning C4319: '~': zero extending 'unsigned int' to 'Darts::Details::std::id_type' of greater size (compiling source file ..\node\binding.cc)](https://ci.appveyor.com/project/Carbo/opencc/build/1.0.42/job/9xykggnactkqvhxe#L28)

**Comment by zhixing2017** [comment]
你编译成功了吗？可否给发了份啊？

**Comment by gucong3000** [comment]
@zhixing2017 
请提供一下以下信息运行以下两条命令，告诉我结果。不同平台的编译结果不同，不可通用
```bash
node -p “os.platform()”
node -p “os.arch()”
```

**Comment by gucong3000** [comment]
windows下自己编译的办法为：
```bash
npm i windows-build-tools -g --python_mirror=https://npm.taobao.org/mirrors/python/
npm i opencc
```
