### ISSUE TITLE
不懂编译，有直接能PHP使用的文件吗？

### ISSUE THREAD

**Issue by hahaapi** [BYVoid/OpenCC#246]
http://opencc.byvoid.com/
或者类似演示的这个源码。谢谢

**Comment by shtse8** [comment]
https://github.com/BYVoid/opencc-php

**Comment by shtse8** [comment]
Linux | OS X

git clone https://github.com/BYVoid/OpenCC.git --depth 1
cd OpenCC
make
sudo make install

git clone git@github.com:NauxLiu/opencc4php.git --depth 1
cd opencc4php
phpize
./configure
make && sudo make install

**Comment by hahaapi** [comment]
还是要安装编译，虚拟机没法玩······
有没考虑下不用编译，直接PHP5.2

**Comment by shtse8** [comment]
为甚么虚拟机没法玩，我也是用虚拟机。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hahaapi** [comment]
虚拟主机，不是虚拟机，没权限编译的，见凉我说话不完整。

**Comment by shtse8** [comment]
你找一台同一樣環境的電腦編繹再拿回去用就可以

**Comment by hahaapi** [comment]
这么晚了还不休息，感谢。话说，能直接发份PHP文件给我直接使用吗？菜鸟真心不懂编译什么之类的。

**Comment by shtse8** [comment]
不可以的, 因為這個不是PHP的程序，是linux的程序，PHP只是做wrapper

**Comment by shtse8** [comment]
php是效能很差資源很有限的Scripting language, 這些複雜的, 還只能交給C去做, PHP最多只能做wrapper.
