### ISSUE TITLE
新旧版本速度问题

### ISSUE THREAD

**Issue by sevenseablue** [BYVoid/OpenCC#250]
语料：　维基百科　中文文本　800多Ｍ
别人的时间：　以前的版本，　１分钟左右
我的时间：　ubuntu 16.04，　opencc 1.04，　时间 80多分钟

能给一个大概的估计，　
１．　opencc的 performance Test．
２．　这个问题是我的问题，　还是opencc　版本的问题

**Comment by BYVoid** [comment]
配置文件只有OCD嗎？

**Comment by wlccgp3** [comment]
我的也是这样，2M的文件都要很久

**Comment by zii** [comment]
是啊速度很慢

**Comment by BYVoid** [comment]
Fixed
