### ISSUE TITLE
建议繁体模式下添加大陆标准

### ISSUE THREAD

**Issue by XHTONGYIN** [BYVoid/OpenCC#252]
如：户，台湾标准是戶，香港和大陆标准是户，同形。
换，台湾和香港标准是換，大陆标准还是换，同形。

严格说来，户和戶、换和換并不是繁简关系，它们是地区字形的差异，在Unicode中因为字源分离原则而分开编码。
为什么要把它们放进繁简转换里？或者还有什么更好的处理方法。
现在各种通行的输入法在繁体模式下总是把户转成戶，换转换为換，误导大众。

**Comment by i-font** [comment]
我卻認爲，現在OpenCC Online裏，已經有三種異體字轉換標準可選，分別是：OpenCC標準、臺灣標準、香港標準，這已足夠日常應用，包括古籍校對等專業用途。例如「户」字，如果選了香港標準，就會轉成「户」而不是「戶」。至於這三個標準都不選的，例如「换」字，實際上並沒有誰在使用正體(繁體)字時會選擇這形體，眞正的正體(繁體)用戶已約定俗成地選擇了，自然不用費神處理。

**Comment by sgalal** [comment]
有這項計劃，但未完成：https://github.com/mrhso/OpenCC_CN-draft

**Comment by sgalal** [comment]
如 @i-font 所言，目前的轉換標準已足夠日常應用，因此不需要將繁體模式的大陸標準加入本 OpenCC 倉庫中。

對於問題所描述的應用場景，可以使用香港轉換模式。最近香港轉換模式進行了更新，轉換應該非常準確。

如果確實有興趣使用繁體模式的大陸標準，可以參考我上面提供的連結。

**Comment by ayaka14732** [comment]
我開發了 OpenCC 的下一代簡繁轉換工具：[StarCC](https://github.com/StarCC0/starcc-py)，支援大陸繁體標準
