### ISSUE TITLE
where can I find TWVariantsRev(txt or ocd) ?

### ISSUE THREAD

**Issue by zhihmeng** [BYVoid/OpenCC#253]
Hi,

When I want to new an instance of OpenCCService, the exception says "can't find TWVariantsRev.txt(ocd)".

I already search the repository, and I can't find this file.

Could you help to tell me where I can get this file ?

Thank you.

**Comment by robaggio** [comment]
These files are generated by opencc, after the installation(not downloading), you can find it at ./build/rel/data . 
If you just need TWVariantsRev.txt, you can also find it from my fork(https://github.com/robaggio/OpenCC/tree/master/iOS/dictionary), as I add those generated files for iOS usage.

**Comment by zhihmeng** [comment]
Hi,

Thank you for your rapidly reply, from your fork, I can find the files and work perfectly.

Thank you again. ^_^
