### ISSUE TITLE
有没有生成好的动态链接库？

### ISSUE THREAD

**Issue by ChengjinWu** [BYVoid/OpenCC#255]

**Comment by osfans** [comment]
linux的話，有啊，比如：
https://www.archlinux.org/packages/community/x86_64/opencc/

**Comment by ChengjinWu** [comment]
谢谢了，我看看怎么调用

**Comment by gucong3000** [comment]
相关： https://github.com/BYVoid/OpenCC/issues/243

@BYVoid 求推进
