### ISSUE TITLE
php中使用出现内存泄露

### ISSUE THREAD

**Issue by micweaver** [BYVoid/OpenCC#256]
使用的opencc4php, 发现PHP进程内存使用会慢慢上升，使用Valgrind检查发现如下问题

==28106== 2,152,448 bytes in 1 blocks are possibly lost in loss record 3,490 of 3,491
==28106==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28106==    by 0x6627B2B: opencc::DartsDict::NewFromFile(_IO_FILE*) (in /usr/lib/libopencc.so.1.0.0)
==28106==    by 0x6624328: opencc::ConfigInternal::ParseDict(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const
&) (in /usr/lib/libopencc.so.1.0.0)
==28106==    by 0x66192DB: opencc::Config::NewFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string
<char, std::char_traits<char>, std::allocator<char> > const&) (in /usr/lib/libopencc.so.1.0.0)
==28106==    by 0x663D2DB: opencc_open_internal(char const*) (in /usr/lib/libopencc.so.1.0.0)
==28106==    by 0x6401168: zif_opencc_open (opencc.c:65)
==28106==    by 0x89CB71: ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:675)
==28106==    by 0x89C328: execute_ex (zend_vm_execute.h:429)
==28106==    by 0x89C409: zend_execute (zend_vm_execute.h:474)
==28106==    by 0x83CCCB: zend_execute_scripts (zend.c:1476)
==28106==    by 0x7AC51A: php_execute_script (main.c:2537)
==28106==    by 0x92F399: main (fpm_main.c:1966)
==28106== 
==28106== 2,152,448 bytes in 1 blocks are possibly lost in loss record 3,490 of 3,491
==28106==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28106==    by 0x6627B2B: opencc::DartsDict::NewFromFile(_IO_FILE*) (in /usr/lib/libopencc.so.1.0.0)
==28106==    by 0x6624328: opencc::ConfigInternal::ParseDict(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const
&) (in /usr/lib/libopencc.so.1.0.0)
==28106==    by 0x66192DB: opencc::Config::NewFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string
<char, std::char_traits<char>, std::allocator<char> > const&) (in /usr/lib/libopencc.so.1.0.0)
==28106==    by 0x661B730: opencc::Config::NewFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (in /usr/lib/libopencc.so.1.
0.0)
==28106==    by 0x663D0BA: opencc::SimpleConverter::SimpleConverter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (in /usr/lib/li
bopencc.so.1.0.0)
==28106==    by 0x663D2DB: opencc_open_internal(char const*) (in /usr/lib/libopencc.so.1.0.0)
==28106==    by 0x6401168: zif_opencc_open (opencc.c:65)
==28106==    by 0x89CB71: ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:675)
==28106==    by 0x89C328: execute_ex (zend_vm_execute.h:429)
==28106==    by 0x89C409: zend_execute (zend_vm_execute.h:474)
==28106==    by 0x83CCCB: zend_execute_scripts (zend.c:1476)
==28106==    by 0x7AC51A: php_execute_script (main.c:2537)
==28106==    by 0x92F399: main (fpm_main.c:1966)
==28106== 
==28106== 3,267,426 (8 direct, 3,267,418 indirect) bytes in 1 blocks are definitely lost in loss record 3,491 of 3,491
==28106==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28106==    by 0x663D2CD: opencc_open_internal(char const*) (in /usr/lib/libopencc.so.1.0.0)
==28106==    by 0x6401168: zif_opencc_open (opencc.c:65)
==28106==    by 0x89CB71: ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:675)
==28106==    by 0x89C328: execute_ex (zend_vm_execute.h:429)
==28106==    by 0x89C409: zend_execute (zend_vm_execute.h:474)
==28106==    by 0x83CCCB: zend_execute_scripts (zend.c:1476)
==28106==    by 0x7AC51A: php_execute_script (main.c:2537)
==28106==    by 0x92F399: main (fpm_main.c:1966)
==28106== 
==28106== LEAK SUMMARY:
==28106==    definitely lost: 216 bytes in 2 blocks
==28106==    indirectly lost: 3,269,455 bytes in 106,740 blocks
==28106==      possibly lost: 3,912,264 bytes in 7,676 blocks
==28106==    still reachable: 514,260 bytes in 601 blocks
==28106==         suppressed: 0 bytes in 0 blocks

**Comment by hahaapi** [comment]
我也是，内存一会就占用过多了
