### ISSUE TITLE
参、人参的繁简转换问题

### ISSUE THREAD

**Issue by tsauibusato** [BYVoid/OpenCC#258]
如题，opencc的s2t会把“人参”转换成“人蔘”而不是台湾教育部标准的“人參”，而遇到長句子“十二个人参与这个案件”就會變成“十二個人蔘與這個案件”，意思已经变了。查阅各种词典，发现“人參”更常用而不是“人蔘”，望注意這個BUG

**Comment by Prcuvu** [comment]
可以通过往TWPhrasesOther.txt里加入“人蔘”到“人參”的转换来解决这个问题。

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/commit/f4cefc2d30acd5392a504e73b19593f4a60e9a8d
