### ISSUE TITLE
存疑：閤 -> 合 in TSCharacters.txt

### ISSUE THREAD

**Issue by animalize** [BYVoid/OpenCC#260]
在[TSCharacters.txt的第3091行](https://github.com/BYVoid/OpenCC/blob/eeb259323cdb316705b9577d3efc0af6838b435f/data/dictionary/TSCharacters.txt#L3091)：  
`閤 合`

在[某个版本的全唐诗数据库](https://github.com/jackeyGao/chinese-poetry)里，共出现了129个`閤`，有一部分对应的其实是`阁`

这里可以考虑改成：  
`閤 阁 合`

附，百度汉语的`閤`：  
[http://hanyu.baidu.com/zici/s?wd=%E9%96%A4](http://hanyu.baidu.com/zici/s?wd=%E9%96%A4)

**Comment by BYVoid** [comment]
這個是通假字，不屬於轉換範圍

**Comment by sgalal** [comment]
如上面作者所言，通假字不屬於轉換範圍。

另外，通假字一般是按照原文直接作簡繁轉換，不必先轉換為被通假的字再簡繁轉換。
