### ISSUE TITLE
What's the status of GUI for OpenCC?

### ISSUE THREAD

**Issue by LiMinggang** [BYVoid/OpenCC#261]
I'm interested in integrate the project as a plugin to my project,  MadEdit-Mod which has a embedded simple encoding convert tools.

However, OpenCC looks like a giant in size for the editor mentioned----the file size would be doubled.

So, are there any existing projects on providing GUI for OpenCC? Do most of the users of OpenCC prefer CLI because of handling lots of files/huge files and prefer better performance?

**Comment by osfans** [comment]
https://github.com/BYVoid/opencc-gui

**Comment by osfans** [comment]
https://github.com/BYVoid/opencc-web
