### ISSUE TITLE
想请问下能在mingw下编译这个么

### ISSUE THREAD

**Issue by ashi876** [BYVoid/OpenCC#264]
现在很多人在win平台上用mingw.如果能编译的话那就太好了，

如果能的话要注意下哪些方面？学习编程不久懂的不多，恳请稍详细点的解释

**Comment by osfans** [comment]
可以的。

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-opencc

**Comment by ashi876** [comment]
多谢指点。
