### ISSUE TITLE
centos6.5 npm 安装opencc  报npm ERR! opencc@1.0.5 install: `node-gyp rebuild` 错误

### ISSUE THREAD

**Issue by snuser** [BYVoid/OpenCC#269]
centos6.5 npm 安装opencc  报npm ERR! opencc@1.0.5 install: `node-gyp rebuild` 错误

npm list -g --depth 0
/root/.nvm/versions/node/v8.6.0/lib
├── node-gyp@3.6.2
└── npm@5.4.2

echo $PATH
/root/.nvm/versions/node/v8.6.0/bin:

> npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! opencc@1.0.5 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the opencc@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-30T10_01_08_971Z-debug.log

**Comment by BYVoid** [comment]
Details? /root/.npm/_logs/2017-09-30T10_01_08_971Z-debug.log

**Comment by snuser** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.6.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.6.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   'opencc' ]
2 info using npm@5.4.2
3 info using node@v8.6.0
4 verbose npm-session 4c8eba87b9c1dca6
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 http://registry.npm.taobao.org/opencc 487ms
8 silly pacote tag manifest for opencc@latest fetched in 525ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule opencc@1.0.5 checking installable status
14 http fetch GET 200 http://registry.npm.taobao.org/nan 128ms
15 silly pacote range manifest for nan@^2.5.1 fetched in 132ms
16 silly resolveWithNewModule nan@2.7.0 checking installable status
17 silly currentTree test@1.0.0
18 silly idealTree test@1.0.0
18 silly idealTree ├── nan@2.7.0
18 silly idealTree └── opencc@1.0.5
19 silly install generateActionsToTake
20 silly diffTrees action count 2
21 silly diffTrees add nan@2.7.0
22 silly diffTrees add opencc@1.0.5
23 silly decomposeActions action count 16
24 silly decomposeActions fetch nan@2.7.0
25 silly decomposeActions extract nan@2.7.0
26 silly decomposeActions preinstall nan@2.7.0
27 silly decomposeActions build nan@2.7.0
28 silly decomposeActions install nan@2.7.0
29 silly decomposeActions postinstall nan@2.7.0
30 silly decomposeActions finalize nan@2.7.0
31 silly decomposeActions refresh-package-json nan@2.7.0
32 silly decomposeActions fetch opencc@1.0.5
33 silly decomposeActions extract opencc@1.0.5
34 silly decomposeActions preinstall opencc@1.0.5
35 silly decomposeActions build opencc@1.0.5
36 silly decomposeActions install opencc@1.0.5
37 silly decomposeActions postinstall opencc@1.0.5
38 silly decomposeActions finalize opencc@1.0.5
39 silly decomposeActions refresh-package-json opencc@1.0.5
40 silly install executeActions
41 silly doSerial global-install 16
42 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
43 verbose lock using /root/.npm/_locks/staging-73b6f1eceb388dae.lock for /usr/home/test/node_modules/.staging
44 silly doParallel extract 16
45 silly extract nan@2.7.0
46 silly pacote trying nan@http://registry.npm.taobao.org/nan/download/nan-2.7.0.tgz by hash: sha1-2Vv3IeyHfgjbJ27T/G63j5CDrUY=
47 silly extract opencc@1.0.5
48 silly pacote trying opencc@http://registry.npm.taobao.org/opencc/download/opencc-1.0.5.tgz by hash: sha1-U6korCncNVehseBY02m0I2c6t+U=
49 silly pacote nan@http://registry.npm.taobao.org/nan/download/nan-2.7.0.tgz extracted to /usr/home/test/node_modules/.staging/nan-26c64b81 by content address 87ms
50 silly pacote opencc@http://registry.npm.taobao.org/opencc/download/opencc-1.0.5.tgz extracted to /usr/home/test/node_modules/.staging/opencc-36a4eaf6 by content address 391ms
51 silly doReverseSerial unbuild 16
52 silly doSerial remove 16
53 silly doSerial move 16
54 silly doSerial finalize 16
55 silly finalize /usr/home/test/node_modules/nan
56 silly finalize /usr/home/test/node_modules/opencc
57 silly doParallel refresh-package-json 16
58 silly refresh-package-json /usr/home/test/node_modules/nan
59 silly refresh-package-json /usr/home/test/node_modules/opencc
60 silly doParallel preinstall 16
61 silly preinstall nan@2.7.0
62 info lifecycle nan@2.7.0~preinstall: nan@2.7.0
63 silly preinstall opencc@1.0.5
64 info lifecycle opencc@1.0.5~preinstall: opencc@1.0.5
65 silly doSerial build 16
66 silly build nan@2.7.0
67 info linkStuff nan@2.7.0
68 silly linkStuff nan@2.7.0 has /usr/home/test/node_modules as its parent node_modules
69 verbose linkBins nan@2.7.0
70 verbose linkMans nan@2.7.0
71 silly build opencc@1.0.5
72 info linkStuff opencc@1.0.5
73 silly linkStuff opencc@1.0.5 has /usr/home/test/node_modules as its parent node_modules
74 verbose linkBins opencc@1.0.5
75 verbose linkMans opencc@1.0.5
76 silly doSerial global-link 16
77 silly doParallel update-linked 16
78 silly doSerial install 16
79 silly install nan@2.7.0
80 info lifecycle nan@2.7.0~install: nan@2.7.0
81 silly install opencc@1.0.5
82 info lifecycle opencc@1.0.5~install: opencc@1.0.5
83 verbose lifecycle opencc@1.0.5~install: unsafe-perm in lifecycle false
84 verbose lifecycle opencc@1.0.5~install: PATH: /root/.nvm/versions/node/v8.6.0/lib/node_modules/npm/bin/node-gyp-bin:/usr/home/test/node_modules/opencc/node_modules/.bin:/usr/home/test/node_modules/.bin:/root/.nvm/versions/node/v8.6.0/bin:/usr/local/sinawap/sbin:/usr/local/sinawap/bin:/usr/local/sinawap/nginx/bin:/usr/local/sinawap/apache/bin:/usr/local/sinawap/perl/bin:/usr/local/sinawap/mysql/bin:/usr/local/sinawap/php/bin:/usr/local/sinawap/php-fpm/bin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/sbin:/sbin
85 verbose lifecycle opencc@1.0.5~install: CWD: /usr/home/test/node_modules/opencc
86 silly lifecycle opencc@1.0.5~install: Args: [ '-c', 'node-gyp rebuild' ]
87 info lifecycle opencc@1.0.5~install: Failed to exec install script
88 verbose unlock done using /root/.npm/_locks/staging-73b6f1eceb388dae.lock for /usr/home/test/node_modules/.staging
89 warn test@1.0.0 No description
90 warn test@1.0.0 No repository field.
91 verbose stack Error: opencc@1.0.5 install: `node-gyp rebuild`
91 verbose stack spawn ENOENT
91 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
91 verbose stack     at emitTwo (events.js:125:13)
91 verbose stack     at ChildProcess.emit (events.js:213:7)
91 verbose stack     at maybeClose (internal/child_process.js:927:16)
91 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
92 verbose pkgid opencc@1.0.5
93 verbose cwd /usr/home/test
94 verbose Linux 2.6.32-431.11.2.el6.toa.2.x86_64
95 verbose argv "/root/.nvm/versions/node/v8.6.0/bin/node" "/root/.nvm/versions/node/v8.6.0/bin/npm" "i" "opencc"
96 verbose node v8.6.0
97 verbose npm  v5.4.2
98 error file sh
99 error code ELIFECYCLE
100 error errno ENOENT
101 error syscall spawn
102 error opencc@1.0.5 install: `node-gyp rebuild`
102 error spawn ENOENT
103 error Failed at the opencc@1.0.5 install script.
103 error This is probably not a problem with npm. There is likely additional logging output above.
104 verbose exit [ 1, true ]

**Comment by gucong3000** [comment]
@BYVoid 
It will fixed when we closes #265.

**Comment by gucong3000** [comment]
@snuser Please try:
```bash
sudo yum install gcc-c++ make
npm i BYVoid/OpenCC --save-dev
```

**Comment by sgalal** [comment]
Just tested on CentOS. I believe this issue can be closed now.
