### ISSUE TITLE
ocd文件如何转换回原txt文件？

### ISSUE THREAD

**Issue by qq420100523** [BYVoid/OpenCC#271]
OpenCC把詞庫和程序庫完全分離，程序庫可以讀取兩種格式的詞庫，一種爲Tab分割的平面文本，一種爲OpenCC專門優化過的數據結構，ocd格式。平面文本數據庫格式方便閱讀和修改，ocd格式是OpenCC構造出的Double Array Trie數據結構，基於darts-clone，使用其可以大大提供轉換速度。OpenCC還提供了詞庫轉換程序，可以自由在兩種格式之間轉換。
---------------------------------------------------
我的原文件txt格式已丢失，有方法从ocd文件转换回原txt文件吗？

**Comment by iblis17** [comment]
`opencc_dict` ?

**Comment by qq420100523** [comment]
`PS D:\opencc> .\opencc_dict.exe --help

Open Chinese Convert (OpenCC) Dictionary Tool
Author: Carbo Kuo <byvoid@byvoid.com>
Bug Report: http://github.com/BYVoid/OpenCC/issues

Usage:

   D:\opencc\opencc_dict.exe  -i <file> -o <file> -f <text|ocd> -t <text
                              |ocd> [--] [--version] [-h]

Options:

   -i <file>,  --input <file>
     (required)  Path to input dictionary

   -o <file>,  --output <file>
     (required)  Path to output dictionary

   -f <text|ocd>,  --from <text|ocd>
     (required)  Input format

   -t <text|ocd>,  --to <text|ocd>
     (required)  Output format

   --,  --ignore_rest
     Ignores the rest of the labeled arguments following this flag.

   --version
     Displays version information and exits.

   -h,  --help
     Displays usage information and exits.


   Open Chinese Convert (OpenCC) Dictionary Tool

PS D:\opencc>`

**Comment by qq420100523** [comment]
有四个必填参数，应该怎么写？

**Comment by qq420100523** [comment]
`PS D:\opencc> .\opencc_dict.exe -i .\PYCharacters.ocd -o .\PYCharacters.txt -f ocd -t text
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
PS D:\opencc>`

**Comment by iblis17** [comment]
hmm, 我在 Linux 上面試了一下沒啥問題。找臺 Linux 試試？

**Comment by qq420100523** [comment]
我把文件上传给你，你帮我转换一下，试试
[https://pan.baidu.com/s/1kUCxsRt](url)

**Comment by iblis17** [comment]
https://gist.github.com/iblis17/d7a984fe84e4bb4430ecc9f24fe760e5

**Comment by qq420100523** [comment]
谢谢呀，你只转换了一个？随便帮我把另一下也转换吧

**Comment by qq420100523** [comment]
哦，两个都在，谢谢了

**Comment by iblis17** [comment]
👌

**Comment by qq420100523** [comment]
我发现原因了，应该是有32位和64位之分的

**Comment by IdioticMadman** [comment]
@qq420100523 32位的ocd要怎么构建呢
