### ISSUE TITLE
"計算發現" 翻譯錯誤

### ISSUE THREAD

**Issue by KayLeung** [BYVoid/OpenCC#272]
计算发现

錯誤:
計算髮現

正確:
計算發現

累推的話，可以組成不同詞語可能性很高

被 "算髮" 影響到:
https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/STPhrases.txt#L37478

**Comment by iblis17** [comment]
duplicated https://github.com/BYVoid/OpenCC/issues/224

**Comment by KayLeung** [comment]
@iblis17 謝謝！我有注意到。因為詞語不同，可能有不同處理，所以我額外開 ISSUE。

我在想短暫最佳是否只有放棄 "算髮" 這個對照，個人學術不太好，我第一次看到並不了解 "算髮" 意思，再 GOOGLE 一下看看字典，好像並不會很常用到。

https://baike.baidu.com/item/%E7%AE%97%E5%8F%91

**Comment by NavTRC** [comment]
> @iblis17 謝謝！我有注意到。因為詞語不同，可能有不同處理，所以我額外開 ISSUE。
> 
> 我在想短暫最佳是否只有放棄 "算髮" 這個對照，個人學術不太好，我第一次看到並不了解 "算髮" 意思，再 GOOGLE 一下看看字典，好像並不會很常用到。
> 
> https://baike.baidu.com/item/%E7%AE%97%E5%8F%91

並不需要"算髮" 的對照，
上述的字典"算髮" 指的是古文用法，
與本問題並無關連，正確應是：計算/發現，
@KayLeung 的提議是對的，直接翻譯容易出錯，應先分詞再翻譯

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/commit/0306285d552db491b61b4909c4143d45b1bd0f5a
