### ISSUE TITLE
cnpm安装报错opencc\src\BinaryDict.cpp(27): error C2589: '(': illegal

### ISSUE THREAD

**Issue by zaomaodou** [BYVoid/OpenCC#276]
Installing nan@^2.5.1D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\BinaryDict.cpp(27): error C2589: '(': illegal
token on right side of '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules
\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\BinaryDict.cpp(27): error C2059: syntax error:
 '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\
build\binding.vcxproj]
- [0/1] Installing nan@^2.5.1D:\Server\egg\node_modules\_opencc@1.0.5@opencc\deps\darts-clone\darts.h(759): warning C4334: '<<'
: result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) (compiling source file ..\node\bi
nding.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\deps\darts-clone\darts.h(761): warning C4319: '~':
 zero extending 'unsigned int' to 'Darts::Details::std::id_type' of greater size (compiling source file ..\node\binding
.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\deps\darts-clone\darts.h(811): warning C4530: C++
exception handler used, but unwind semantics are not enabled. Specify /EHsc (compiling source file ..\node\binding.cc)
[D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\DartsDict.cpp(138): error C2589: '(': illegal
token on right side of '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules
\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\DartsDict.cpp(138): error C2059: syntax error:
 '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\
build\binding.vcxproj]
\ [0/1] Installing nan@^2.5.1D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\TextDict.cpp(28): error C2589: '(': illegal to
ken on right side of '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules\_
opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\TextDict.cpp(28): error C2059: syntax error: '
::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\bu
ild\binding.vcxproj]
/ [0/1] Installing nan@^2.5.1  Copying data/config/t2s.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\t
  2s.json
  已复制         1 个文件。
  Copying data/config/s2t.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\s
  2t.json
  已复制         1 个文件。
  Copying data/config/s2twp.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\
  \s2twp.json
  已复制         1 个文件。
  Copying data/config/s2hk.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  s2hk.json
  已复制         1 个文件。
  Copying data/config/hk2s.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  hk2s.json
  已复制         1 个文件。
  Copying data/config/tw2sp.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\
  \tw2sp.json
  已复制         1 个文件。
  Copying data/config/t2hk.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  t2hk.json
  已复制         1 个文件。
  Copying data/config/s2tw.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  s2tw.json
  已复制         1 个文件。
  Copying data/config/tw2s.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  tw2s.json
  已复制         1 个文件。
  Copying data/config/t2tw.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  t2tw.json
  已复制         1 个文件。
- [0/1] Installing nan@^2.5.1gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\szdx\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\daxia\\nodejs\\node.exe" "C:\\Users\\szdx\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Server\egg\node_modules\_opencc@1.0.5@opencc
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
× Install fail! Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\szdx\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npminstall version: 3.1.4
npminstall args: D:\daxia\nodejs\node.exe C:\Users\szdx\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\szdx\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org opencc --save

D:\Server\egg>cnpm i opencc --save
- [0/1] Installing nan@^2.5.1
D:\Server\egg\node_modules\_opencc@1.0.5@opencc>node "C:\Users\szdx\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
/ [0/1] Installing nan@^2.5.1在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
| [0/1] Installing nan@^2.5.1  binding.cc
  win_delay_load_hook.cc
- [0/1] Installing nan@^2.5.1D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\BinaryDict.cpp(27): error C2589: '(': illegal
token on right side of '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules
\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\BinaryDict.cpp(27): error C2059: syntax error:
 '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\
build\binding.vcxproj]
\ [0/1] Installing nan@^2.5.1D:\Server\egg\node_modules\_opencc@1.0.5@opencc\deps\darts-clone\darts.h(759): warning C4334: '<<'
: result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) (compiling source file ..\node\bi
nding.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\deps\darts-clone\darts.h(761): warning C4319: '~':
 zero extending 'unsigned int' to 'Darts::Details::std::id_type' of greater size (compiling source file ..\node\binding
.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\deps\darts-clone\darts.h(811): warning C4530: C++
exception handler used, but unwind semantics are not enabled. Specify /EHsc (compiling source file ..\node\binding.cc)
[D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\DartsDict.cpp(138): error C2589: '(': illegal
token on right side of '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules
\_opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\DartsDict.cpp(138): error C2059: syntax error:
 '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\
build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\TextDict.cpp(28): error C2589: '(': illegal to
ken on right side of '::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules\_
opencc@1.0.5@opencc\build\binding.vcxproj]
D:\Server\egg\node_modules\_opencc@1.0.5@opencc\src\TextDict.cpp(28): error C2059: syntax error: '
::' (compiling source file ..\node\binding.cc) [D:\Server\egg\node_modules\_opencc@1.0.5@opencc\bu
ild\binding.vcxproj]
/ [0/1] Installing nan@^2.5.1  Copying data/config/t2s.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\t
  2s.json
  已复制         1 个文件。
  Copying data/config/s2t.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\s
  2t.json
  已复制         1 个文件。
  Copying data/config/s2twp.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\
  \s2twp.json
  已复制         1 个文件。
- [0/1] Installing nan@^2.5.1  Copying data/config/s2hk.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  s2hk.json
  已复制         1 个文件。
  Copying data/config/hk2s.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  hk2s.json
  已复制         1 个文件。
  Copying data/config/tw2sp.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\
  \tw2sp.json
  已复制         1 个文件。
  Copying data/config/t2hk.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  t2hk.json
  已复制         1 个文件。
  Copying data/config/s2tw.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  s2tw.json
  已复制         1 个文件。
  Copying data/config/tw2s.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  tw2s.json
  已复制         1 个文件。
  Copying data/config/t2tw.json to D:\Server\egg\node_modules\_opencc@1.0.5@opencc\build\Release\\
  t2tw.json
  已复制         1 个文件。
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\szdx\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\daxia\\nodejs\\node.exe" "C:\\Users\\szdx\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Server\egg\node_modules\_opencc@1.0.5@opencc
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
× Install fail! Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\szdx\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npminstall version: 3.1.4
npminstall args: D:\daxia\nodejs\node.exe C:\Users\szdx\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\szdx\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org opencc --save

npm 报错如下
npm i opencc --save
npm WARN checkPermissions Missing write access to D:\Server\egg\node_modules\co-wrap-all
npm WARN checkPermissions Missing write access to D:\Server\egg\node_modules\delayed-stream
npm WARN checkPermissions Missing write access to D:\Server\egg\node_modules\sqlstring
npm WARN checkPermissions Missing write access to D:\Server\egg\node_modules\opencc
npm WARN co-mocha@1.2.0 requires a peer of mocha@>=1.18 <4 but none was installed.

npm ERR! path D:\Server\egg\node_modules\co-wrap-all
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'D:\Server\egg\node_modules\co-wrap-all'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

请问有碰到过的吗

**Comment by gucong3000** [comment]
@zaomaodou  Please try:
```bash
npm i BYVoid/OpenCC --save
```

**Comment by kazenorin** [comment]
@gucong3000 
Hi, I have the exact problem and this seems to work.
But how do you add this as a dependency to package.json?

I find that the 1.0.4 version builds successfully, and that this issue happens only in the 1.0.5 version.

**Comment by gucong3000** [comment]
@kazenorin
just run `npm i BYVoid/OpenCC --save`
It will be add this as a dependency to package.json

**Comment by kazenorin** [comment]
@gucong3000 It worked!
It now adds "github:BYVoid/OpenCC" as a dependency to package.json
