### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by yesseecity** [BYVoid/OpenCC#277]
OS: ubuntu:16.10 docker 
opencc version: 1.0.4

我使用 ~/opencc-1.0.4/test/testcases 裡面的 t2s.in  

並使用指令
```opencc -i t2s.in  -o bb.txt -c tw2s.json```
但他顯示
```Segmentation fault```

請問我漏掉了什麼嗎？

**Comment by sgalal** [comment]
沒有復現，如果仍然存在問題請重開這個 issue。
