### ISSUE TITLE
句子翻译错误

### ISSUE THREAD

**Issue by tuxzz** [BYVoid/OpenCC#280]
"张必须发皆白
必须
须发"

被转换为了

"張必須發皆白
必須
鬚髮"

**Comment by iblis17** [comment]
duplicated #224 
目前還沒辦法斷詞，先用其他套件斷了詞在丟到 OpenCC 試試。

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/commit/0306285d552db491b61b4909c4143d45b1bd0f5a
