### ISSUE TITLE
pip install opencc-python 出错

### ISSUE THREAD

**Issue by zfyu** [BYVoid/OpenCC#282]
首先提示缺少distribute_setup.py，补全后，又出现urllib....HTTPError错误，不知道是不是我的distribute_setup.py有误？
同时，想请教一下，从https://launchpad.net/ubuntu/+source/opencc下载的.tar.gz文件解压后怎么用呢

**Comment by lionsterben** [comment]
可以使用批pip install opencc-python-reimplemented
