### ISSUE TITLE
一個授權上的問題

### ISSUE THREAD

**Issue by flier268** [BYVoid/OpenCC#283]
你好，我想開發一個類似ConvertZ的軟體，想使用你的dictionary，不知道有什麼限制呢?

**Comment by gqqnbig** [comment]
感谢您对版权的重视。本项目的首页即说明了本项目采用的协议，请点击查看。
![1](https://user-images.githubusercontent.com/614159/36059129-748772a4-0de6-11e8-9f12-b4aaa67d4a94.JPG)
