### ISSUE TITLE
VS2017编译报错

### ISSUE THREAD

**Issue by freevest** [BYVoid/OpenCC#287]
VS2017编译时有两个问题：
1、一个是PhraseExtract.cpp文件的编码问题：
![c hhi 3 b ezu nc6gt26w](https://user-images.githubusercontent.com/12496417/35154644-f6e3fbe6-fd65-11e7-9060-a00808924a3a.png)
这个可以通过修改文件编码解决；
2、另一个问题很诡异，各种搜索找不到原因，请问为何：
![12313213123123](https://user-images.githubusercontent.com/12496417/35154740-4fb83016-fd66-11e7-947e-af04ca161090.png)

**Comment by mlkui** [comment]
1、在Windows环境下，源码中的两个PhraseExtract.cpp文件的编码应该设为Unicode-代码页1200；
2、longjmp和setjmp报错的问题与SDK版本有关，用VC15生成的工程确实有问题（SDK 10.+）；

在Windows平台下使用VisualStudio2017编译Opencc 1.0.4源码的过程可以参考如下链接：http://www.meilongkui.com/archives/358

**Comment by 475059538** [comment]
你好，有个问题想请教一下，我看到了你在这个问题下的评论，我跟你遇到的问题是一样的。用HttpClient在多线程环境下使用proxy来访问网页，最后线程挂起导致阻塞，请问这个问题你最后是怎么解决的
https://github.com/apache/httpcomponents-client/commit/d954cd287dfcdad8f153e61181e20d253175ca8c

**Comment by abcfy2** [comment]
同样各种编译报错，不知道是否有人分享下编译好的成品呢？最好能提供静态编译版本的，谢谢了。

**Comment by freevest** [comment]
@mlkui 感谢分享，按照你给出的链接已解决问题，关闭。
