### ISSUE TITLE
window10 visual studio 2015 编译报错

### ISSUE THREAD

**Issue by webcatevan** [BYVoid/OpenCC#288]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "void __cdecl opencc::ConvertDictionary(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?ConvertDictionary@opencc@@YAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@000@Z)，该符号在函数 _main 中被引用	opencc_dict	C:\Users\Lin\Desktop\OpenCC-ver.1.0.5\build\src\tools\DictConverter.obj	1

![image](https://user-images.githubusercontent.com/36984876/36890418-b680af56-1e38-11e8-901a-2c56d94f5c08.png)
	
麻烦看看！
please help me!

**Comment by Mapaler** [comment]
![Screenshot 2019-06-14 20 57 47](https://user-images.githubusercontent.com/6565860/59510758-1dcbdd00-8ee7-11e9-8c48-80d0ffe3a963.png)
我用VS 2019也是有问题

**Comment by xiaoxinpro** [comment]
我也是这个LNK2019的报错，我用了VS2013，VS2015，VS2017编译存在这个问题，系统是Win10，有办法解决吗？

**Comment by sgalal** [comment]
这个问题还存在嘛？现在的 CI build 都是正常的没有问题，所以先关掉这个 issue 了。
