### ISSUE TITLE
请问怎么修改转换词库呢？有些字想要修改下

### ISSUE THREAD

**Issue by hahaapi** [BYVoid/OpenCC#289]
如
s2twp
会把“台”转成“臺”
實際中，繁體使用 台  的人更多

所以我也想把把的臺改成台。谢谢了

**Comment by kyleskimo** [comment]
編輯: TWVariants.txt
添加: 臺	台
運行: opencc_dict.exe -i TWVariants.txt -o TWVariants.ocd -f text -t ocd

**Comment by hahaapi** [comment]
運行: opencc_dict.exe -i TWVariants.txt -o TWVariants.ocd -f text -t ocd
这个没法运行，没看到opencc_dict.exe文件在哪
debian系统

**Comment by wcchh** [comment]
s2twp 會把: "激光" => "鐳射"
可是應該要這樣比較合適吧:  "激光" => "雷射"

請問是改 TWPhrasesIT.txt 嗎? 謝謝。

**Comment by sgalal** [comment]
> s2twp 會把: "激光" => "鐳射"
> 可是應該要這樣比較合適吧: "激光" => "雷射"
> 而且在Jieba分詞上，會正確分出 "雷射" 一詞；"鐳射" 會被拆成 "鐳" + "射"，如 "鐳射雷達" 拆成=> "鐳"、"射雷達"。
> 
> 請問是改 TWPhrasesIT.txt 嗎? 謝謝。

是的。修改後重新編譯即可。
