### ISSUE TITLE
请问有没有命令来忽略报错，跳过这个字符，继续转换？

### ISSUE THREAD

**Issue by gundamhyl** [BYVoid/OpenCC#292]
我找到一个繁体中文的语词向量，我需要简体版本。它用pickle打包，繁体和数字之间添加了许多的不能识别的字符。所以opencc一运行，就报错。有没有命令来忽略报错，继续转换？

**Comment by BYVoid** [comment]
可以先用其他工具修復UTF8的錯誤。
