### ISSUE TITLE
返现一个转换异常。将繁体转换为简体。

### ISSUE THREAD

**Issue by zdd** [BYVoid/OpenCC#296]
inputText如下：
[走+吾+午]（同吾）車既工#吾馬既同#吾車既好@吾馬既[馬+缶]（同阜）#君子員邋#員斿麀鹿@速君子之#求角弓玆#以寺敺（音區同驅）其@其來趩[台+辛+炎]（同炱灰）#即吾即時#麀鹿[走+朿]（音氣側行也）其@來大吾敺#其樸其[走+賣]（音讀行走）#射其[豕+肩]（同豜 三歲的豬，泛指大獸）蜀@-汧殹沔#[丞+山]（同丞辅佐）皮淖淵#[魚+妟]（同鰋鲇魚）鯉處之@君子[漁+寸]之#澫（同漫）又[小+魚]（音小細魚）其#斿[林+走+月+攵]帛魚@[帛+樂]（同皪白色）其[?+氵+盜]（音剧同菹醃菜）氐#鮮黃帛其#[魚+丙+丙]又鯆又@[魚+帛]（同鮊魚名）其[立+月]（音氣肉湯）孔#庶臠（音欒切成小塊的肉）之[?+史]#[汗+土]（同汗）[走+專]（同專）其魚@隹可隹鱮#隹鯉可以#橐之隹楊@及柳-田#車孔安鋚#勒既簡左@驂旛右驂#騝吾以隮#于[走+备+录](同原高地）吾之@[阝+夫]宮車其#寫秀弓寺#射麋豕孔@庶麀鹿雉#兔其又[方+丿+一+申]（同陣）#其[走+走+走]（同奔）大出@各亞昊執#而勿射庶#[走+樂]（動也）君子[走+西]@樂-鑾車#賁[朿+次]弓孔#彤矢四馬@其寫六轡#徒[馬+更]（同馭）孔庶#[广+虜+邑] 宣搏眚（同省）@車載[行中人]（同行）徒@如章[走+备+录](同原高地）[氵+糹+糹+土]#陰陽趍馬@射之[走+予]如#虎獸鹿如#多賢迧禽@允異-靈#雨流迄湧#盈湈濟君@子即涉馬#汧殹洎[艹+淒+艹]#舫舟西逮@自[广+虜+邑]徒[馬+更]#隹舟以[行中人]#或陰或陽@极深以戶#于水一方#勿止其奔@其敔其事#-猷乍[走+备+录]#乍導遄我@[辭左半+司]除帥皮#阪草爲卅#里微[彳+或+土]廼@罟栗柞棫#其[木+舟+畟]（同椶即棕）[木+咎]？#鳴亞箬其@華為所斿#[憂+攵+土]盩導[二+日]#樹[五+日]-而@弓[小+大]孔庶#左滔是？#不具蒦具@[月+亏]來其寫#[小+大]具天子#嗣王始古@我來-皮#走[馬+齊]馬薦#[艹+皙+艹]？？雉@其一之-#吾水既瀞#道既平既@止嘉樹則#里天子永#寧日隹丙@申吾其導#馬既康駕#左驂驁[馬束矢]@[馬+攴]毋不翰#[雨+桼+勿]公謂大#余攴如不@余攴-吳#人[粦+心]（同憐）敬載#西載北勿@勿代而用#大祝曾享#執寓逢中@囿孔鹿吾#其緟大求#又是

请告知是哪个字符引起的异常，我做一下特殊处理。

**Comment by sgalal** [comment]
經測試，目前沒有異常
