### ISSUE TITLE
請問 txt 檔內的文字是否一定要按順序排列?

### ISSUE THREAD

**Issue by dfpoon** [BYVoid/OpenCC#297]
如題。例如這個檔: https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/STPhrases.txt

看上去裡面的詞彙好像有一個順序。是按筆劃序排的嗎?
如果txt檔沒有排序，opencc 是否一樣處理得來? 謝謝回覆。

**Comment by BYVoid** [comment]
並不需要，載入時會排序。
