### ISSUE TITLE
tsphrases.txt 出丑狼借 问题 

### ISSUE THREAD

**Issue by abluesea** [BYVoid/OpenCC#299]
原表：
傷亡枕藉	伤亡枕借
出醜狼藉	出丑狼借

是否还是伤亡枕藉 出丑狼藉更合适？
微软，汉典“http://www.zdic.net/c/c/149/321508.htm“ 只有狼藉，没有狼借。

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/commit/0306285d552db491b61b4909c4143d45b1bd0f5a
