### ISSUE TITLE
繁体：廐 -> 简体：厩

### ISSUE THREAD

**Issue by barrer** [BYVoid/OpenCC#300]
截图来自《现代汉语词典第7版》
![image](https://user-images.githubusercontent.com/30139527/43630355-a52f467c-9732-11e8-8abc-77fb9553ef83.png)

《牛津高阶英汉双解词典第八版 · 繁体》
```
stable
[countable] a building in which horses are kept 馬廐
```

**Comment by sgalal** [comment]
「廐」是異體字，繁體字是「廄」，因為是異體字所以不轉換，同 #361。
