### ISSUE TITLE
怎样将 OpenCC 做成 macOS 服务？

### ISSUE THREAD

**Issue by ShikiSuen** [BYVoid/OpenCC#305]
我尝试这样做之后发现并不能正常使用：

<img width="629" alt="image" src="https://user-images.githubusercontent.com/3164826/45790802-24f7ee80-bcb9-11e8-8788-3e0c68233949.png">

**Comment by BYVoid** [comment]
具體有任何問題？

**Comment by ShikiSuen** [comment]
就是在嘗試做成 macOS 服務的時候發現無法正常工作而已。

**Comment by BYVoid** [comment]
錯誤信息是什麼？

**Comment by ShikiSuen** [comment]
@BYVoid 當時的紀錄找不到了，但 Terminal 重新試了一下之後發現這種方式似乎僅支援檔案輸入（而非熱文本輸入）：

![image](https://user-images.githubusercontent.com/3164826/79495954-63ee5180-8060-11ea-87ed-2149177fefaa.png)

**Comment by sgalal** [comment]
@ShikiSuen 

```sh
$ echo 網路 | /usr/sbin/opencc -c tw2sp
网络
```

This also works in bash and zsh:

```zsh
$ /usr/sbin/opencc -c tw2sp < <(echo 網路)
网络
```

**Comment by ShikiSuen** [comment]
感謝 @sgalal 講解用法。

**Comment by ShikiSuen** [comment]
![image](https://user-images.githubusercontent.com/3164826/79626491-7e612180-816b-11ea-93a1-60e4feb767de.png)
這樣可以用了，但我發現會在 TextEdit 當中轉換文字時破壞選中文本的格式。
猜想可能是 RTF 格式資訊被過濾掉了。

**Comment by sgalal** [comment]
@ShikiSuen 我想應該不是 RTF 格式資訊被過濾掉了，因為 OpenCC 只會轉換中文字，不會改變其他字元。所以我覺得可能是其他原因。
