### ISSUE TITLE
Win10 Node版 编译报错

### ISSUE THREAD

**Issue by zdd** [BYVoid/OpenCC#306]
D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Pro
gram Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\src\binarydict.cpp(27): error C2589: '(': illegal token on right side of '::' (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\src\binarydict.cpp(27): error C2062: type 'unknown-type' unexpected (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\src\binarydict.cpp(27): error C2059: syntax error: ')' (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.15.26726\include\setjmp.h(165): error C3829: standard attribute 'noreturn' may only be applied to functions (compiling source file ..\node\binding.cc) [D:\git\ionic\Shu
fadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.15.26726\include\setjmp.h(165): error C2206: 'longjmp': typedef cannot be used for function definition (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaq
uan_Ionic\node_modules\opencc\build\binding.vcxproj]
c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.15.26726\include\csetjmp(18): error C2039: 'longjmp': is not a member of '`global namespace'' (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic
\node_modules\opencc\build\binding.vcxproj]
c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.15.26726\include\csetjmp(18): error C2873: 'longjmp': symbol cannot be used in a using-declaration (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_
Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\deps\darts-clone\darts.h(759): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) (compiling source file ..\node\binding.cc) [D:\git\ionic\Shuf
adaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\deps\darts-clone\darts.h(761): warning C4319: '~': zero extending 'unsigned int' to 'T' of greater size [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
          with
          [
              T=Darts::Details::id_type
          ] (compiling source file ..\node\binding.cc)
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\deps\darts-clone\darts.h(811): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Io
nic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\src\dartsdict.cpp(138): error C2589: '(': illegal token on right side of '::' (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\src\dartsdict.cpp(138): error C2062: type 'unknown-type' unexpected (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\src\dartsdict.cpp(138): error C2059: syntax error: ')' (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\src\textdict.cpp(28): error C2589: '(': illegal token on right side of '::' (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\src\textdict.cpp(28): error C2062: type 'unknown-type' unexpected (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\src\textdict.cpp(28): error C2059: syntax error: ')' (compiling source file ..\node\binding.cc) [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
d:\git\ionic\shufadaquan_ionic\node_modules\opencc\node\binding.cc(122): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\binding.vcxproj]
  d:\git\ionic\shufadaquan_ionic\node_modules\nan\nan.h(1647): note: see declaration of 'Nan::Callback::Call'
  Copying data/config/t2s.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\t2s.json
          1 file(s) copied.
  Copying data/config/s2t.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\s2t.json
          1 file(s) copied.
  Copying data/config/s2twp.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\s2twp.json
          1 file(s) copied.
  Copying data/config/s2hk.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\s2hk.json
          1 file(s) copied.
  Copying data/config/hk2s.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\hk2s.json
          1 file(s) copied.
  Copying data/config/tw2sp.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\tw2sp.json
          1 file(s) copied.
  Copying data/config/t2hk.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\t2hk.json
          1 file(s) copied.
  Copying data/config/s2tw.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\s2tw.json
          1 file(s) copied.
  Copying data/config/tw2s.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\tw2s.json
          1 file(s) copied.
  Copying data/config/t2tw.json to D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc\build\Release\\t2tw.json
          1 file(s) copied.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\git\ionic\Shufadaquan_Ionic\node_modules\opencc
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN @ionic-native/device@4.13.0 requires a peer of @ionic-native/core@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/in-app-browser@4.13.0 requires a peer of @ionic-native/core@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/toast@4.12.2 requires a peer of @ionic-native/core@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencc@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencc@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SuperDong\AppData\Roaming\npm-cache\_logs\2018-09-23T23_30_46_810Z-debug.log

**Comment by zdd** [comment]
> 上面兄弟有进展了吗？
> 我这边用 Windows 7 + Visual Studio 2017 build tool 编译也是报错。
> 
> 1. error c3829: standard attribute 'noreturn' may only be applied to functions
> 2. error c2206: 'longjmp': typedef cannot be used for function definition
> 3. error c2873 'longjmp' symbol cannot be used in a using-declaration

没有，已经转到其他库了，看这里：https://github.com/compulim/node-opencc

**Comment by zdd** [comment]
想用node版本的，不要在这个库上浪费时间了，Windows根本无法编译，试试下面这个纯node版的吧，亲测好用！
https://github.com/compulim/node-opencc

**Comment by ztl8702** [comment]
#285 #290
