### ISSUE TITLE
兩個轉換錯誤

### ISSUE THREAD

**Issue by Hulenkius** [BYVoid/OpenCC#316]
「表面」誤轉爲「錶面」
「冷面笑匠」誤轉爲「冷麵笑匠」

**Comment by silascript** [comment]
哈哈，朝鮮冷麵笑匠！

**Comment by sgalal** [comment]
> 「表面」誤轉爲「錶面」

現在轉換結果是「表面」

> 「冷面笑匠」誤轉爲「冷麵笑匠」

現在詞典文件中是

```
冷面	冷麪 冷面
```

如果有需要，加一條

```
冷面笑匠	冷面笑匠
```

即可解決
