### ISSUE TITLE
請問 segmentation 與 conversion_chain 在概念上的差異

### ISSUE THREAD

**Issue by doggy8088** [BYVoid/OpenCC#326]
請問在 `*.json` 設定檔中的 `segmentation` 與 `conversion_chain` 在概念上有何差異？

我以 `t2tw.json` 為例：

```json
{
  "name": "Traditional Chinese to Traditional Chinese (Taiwan standard)",
  "segmentation": {
    "type": "mmseg",
    "dict": {
      "type": "ocd",
      "file": "TWVariants.ocd"
    }
  },
  "conversion_chain": [{
    "dict": {
      "type": "ocd",
      "file": "TWVariants.ocd"
    }
  }]
}
```

裡面的 `segmentation` 與 `conversion_chain` 區段，都套用了 `TWVariants.ocd` 檔案，在 OpenCC 執行的時候，大概是怎樣運行的？

**Comment by mikechengwei** [comment]
mark

**Comment by doggy8088** [comment]
我目前的理解是：

* `segmentation` 是**分詞**
* `conversion_chain` 是分詞後的**詞彙轉換**

如果有**跨越分詞**的字句，我發現是無法透過 `conversion_chain` 轉換的，目前這個問題對我來說有點困擾！暫時的解法是刪除一些有困擾無法轉換的的分詞。

**Comment by sgalal** [comment]
如你所言，`segmentation` 是分詞，`conversion_chain` 是分詞後的詞彙轉換
