### ISSUE TITLE
Mac安装OpenCC时make编译出错

### ISSUE THREAD

**Issue by KobeLA24** [BYVoid/OpenCC#330]
MacBook-Pro-3:Word2Vec qinchao$ cd OpenCC/
MacBook-Pro-3:OpenCC qinchao$ make PREFIX=/usr/local
mkdir -p build/rel
(cd build/rel; cmake \
	-DBUILD_DOCUMENTATION:BOOL=ON \
	-DENABLE_GTEST:BOOL=OFF \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr/local \
	../..)
-- The CXX compiler identification is GNU 4.8.5
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /opt/local/bin/c++
-- Check for working CXX compiler: /opt/local/bin/c++ -- broken
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.14/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/opt/local/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/qinchao/Desktop/Word2Vec/OpenCC/build/rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_faa9d/fast 
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_faa9d.dir/build.make CMakeFiles/cmTC_faa9d.dir/build
    Building CXX object CMakeFiles/cmTC_faa9d.dir/testCXXCompiler.cxx.o
    /opt/local/bin/c++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -o CMakeFiles/cmTC_faa9d.dir/testCXXCompiler.cxx.o -c /Users/qinchao/Desktop/Word2Vec/OpenCC/build/rel/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_faa9d
    /Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTC_faa9d.dir/link.txt --verbose=1
    /opt/local/bin/c++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_faa9d.dir/testCXXCompiler.cxx.o  -o cmTC_faa9d 
    ld: unexpected token: !tapi-tbd-v3 file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd' for architecture x86_64
    collect2: error: ld returned 1 exit status
    make[2]: *** [cmTC_faa9d] Error 1
    make[1]: *** [cmTC_faa9d/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:22 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/qinchao/Desktop/Word2Vec/OpenCC/build/rel/CMakeFiles/CMakeOutput.log".
See also "/Users/qinchao/Desktop/Word2Vec/OpenCC/build/rel/CMakeFiles/CMakeError.log".
make: *** [build] Error 1
请问有人知道怎么解决么？非常感谢！

**Comment by sgalal** [comment]
从报错信息上看，

```
The C++ compiler "/opt/local/bin/c++" is not able to compile a simple test program.
```

说明编译器无法正常工作。

这一步是在编译 OpenCC 之前，检查编译器能否正常编译一个简单的测试程序。这一步报错说明是编译器故障，不是 OpenCC 代码的问题。
