### ISSUE TITLE
To Use OpenCC in Java

### ISSUE THREAD

**Issue by elvisyjlin** [BYVoid/OpenCC#334]
I browsed through past issues and know that there are two ways to use OpenCC in Java. 1) To integrate with jni, and 2) to invoke the command line. However, I didn't see how to integrate them together exactly.

Is there any example about using OpenCC in Java with jni?

Thank you!

**Comment by sgalal** [comment]
> Is there any example about using OpenCC in Java with jni?

Perhaps https://github.com/osfans/trime?

**Comment by BYVoid** [comment]
https://github.com/qichuan/android-opencc
