### ISSUE TITLE
香港繁體转简体，`偽`字可能出现BUG

### ISSUE THREAD

**Issue by Mapaler** [BYVoid/OpenCC#341]
一个把繁体数据同时转换成简体数据的一个子项目。用的是git代码编译的Windows下64位的exe
https://github.com/Mapaler/Download-pad.skyozora.com

`偽`字使用`hk2s.json`转换为简体后，前方多出来一个`0xFEFF`字符，使用`t2s.json`则没有问题。
![图像 2](https://user-images.githubusercontent.com/6565860/59531720-3ead2600-8f19-11e9-8ca2-8f971d3d2492.png)
![图像 4](https://user-images.githubusercontent.com/6565860/59531721-3f45bc80-8f19-11e9-8a09-976a5d750b3e.png)

**Comment by sgalal** [comment]
> `偽`字使用`hk2s.json`转换为简体后，前方多出来一个`0xFEFF`字符

`0xFEFF` 是 UTF-8 BOM 文件頭，「偽」字在 `HKVariants.txt` 中位於第一行 `僞\t偽`，如果採用 UTF-8 BOM 編碼就會變成 `\ufeff僞\t偽`，再反向轉換以後就會變成 `偽\t\ufeff僞`，即 `偽` 對應 `\ufeff僞`。

但是當前版本的 OpenCC 中 `HKVariants.txt` 並沒有 UTF-8 BOM 文件頭。我猜測文件頭可能是 Windows 自動加入的

**Comment by Mapaler** [comment]
不是Windows自动加入的，是我手动改的，因为之前不改的话，无法编译通过。然后翻issues反倒有网友加了bom就能编译成功了。

**Comment by sgalal** [comment]
> 然后翻issues反倒有网友加了bom就能编译成功了

是不是説 https://github.com/BYVoid/OpenCC/issues/192 這個 issue？

應該是修改代碼文件，`HKVariants.txt` 應該不需要修改

**Comment by Mapaler** [comment]
几个月了，不太记得了，当时我是手动把所有的txt加上bom才编译通过的。

不过现在最新版只改了 PhraseExtract.cpp 就可以了， 并且转换时 `偽` 等字也没有bug了，谢谢。
