### ISSUE TITLE
想請教如何在Anaconda安裝opencc?

### ISSUE THREAD

**Issue by eropanda** [BYVoid/OpenCC#344]
如題
作業系統為windows 10
平常寫python都是使用Anaconda這個開發環境
想請教一下該如何在Anaconda內安裝opencc這個套件呢?

**Comment by sgalal** [comment]
OpenCC 是使用 C 語言開發的，要在 Anaconda 內安裝 OpenCC 可以使用 opencc-python。

**Comment by BYVoid** [comment]
opencc沒有官方的Python / Anaconda支持，你可以考慮 https://blog.csdn.net/u011467833/article/details/82932865
