### ISSUE TITLE
新人求助，为什么字典TSCharacters.txt里面映射到乱码？显示问题？

### ISSUE THREAD

**Issue by Birdandfish** [BYVoid/OpenCC#348]
![image](https://user-images.githubusercontent.com/26051798/64617592-52c9cc00-d411-11e9-87c8-821b8718d05d.png)
使用这个字典转出来的都是方框乱码。是需要安装什么吗？

**Comment by lotem** [comment]
1 https://www.zdic.net/hans/%F0%AB%9D%88
顯示該字符需要安裝CJK擴展D的字體

**Comment by Birdandfish** [comment]
多谢！
