### ISSUE TITLE
添加馬新簡體支持

### ISSUE THREAD

**Issue by yxliang01** [BYVoid/OpenCC#352]
OpenCC是一個很棒的中文轉換平台。目前支持多版本中文間的轉換（大陸簡體，香港繁體，等）。但目前未有對馬新簡體的支持。我認為可以增加馬新簡體的支持，故此建立此Issue令有興趣的人或許可以共同添加或討論 對馬新簡體的支持。

如 ：
『零錢』->『散钱』
『吸管』->『水草』

**Comment by BYVoid** [comment]
此類非簡體字轉換，而是地區用詞轉換，請參見 https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TWPhrasesName.txt 提交類似的文件。
