### ISSUE TITLE
瘉（繁体） -> 愈（简体）

### ISSUE THREAD

**Issue by barrer** [BYVoid/OpenCC#361]
牛津高阶英汉双解词典第八版

**heal**

`It took a long time for the wounds to heal. 傷口過了很長時間才瘉合。`

之前的一个类似的：https://github.com/BYVoid/OpenCC/issues/300#issue-347288781

**Comment by sgalal** [comment]
「瘉」和「愈」不全等

## 一

<https://github.com/BYVoid/ytenx/blob/master/ytenx/sync/jihthex/JihThex.csv>:

癒 = 愈 ≠ 瘉 (語義交疊)

## 二

<http://chardb.iis.sinica.edu.tw/meancompare/7609/7652>:

瘉：**1. 病；害。**    2. 同「愈」。①病愈；醫治好。②超過；高明。③更加。

癒：1. 同「瘉」、「愈」。病好了。

## 三

《詩經·小雅·正月》

父母生我，胡俾我瘉。（瘉：病，不能寫作「癒」）

## 四

現代多用「癒合」而非「瘉合」。

**Comment by barrer** [comment]
@sgalal 简体中文中没有发现“瘉”字
```
《现代汉语词典(第5版)》
愈
(①瘉癒)yù ①(病)好：痊～|病～。②较好；胜过：彼～于此。
愈
yù ①{副}叠用，跟“越…越…”相同：山路～走～陡，而风景～来～奇|～是情况紧急，～是需要沉着冷静。②(Yù){名}姓。
```
由此可见`瘉癒`在简体中文中均以`愈`替代

**Comment by sgalal** [comment]
@barrer 你的理解有一些偏差，OpenCC 不是什麼字都收錄。作「癒合」解時繁體多用「癒」，此時「瘉」應視為異體字。對於異體字，OpenCC 是不轉換的，因此「癒」->「愈」的轉換規則已經足夠。

**Comment by barrer** [comment]
我理解您说的是语义上的区别，但是**OpenCC**描述`A project for conversion between Traditional and Simplified Chinese`，既然是繁简互转，而`瘉癒`二字在简体中文中并不存在，那么是否就最终行为结果来看，在这一点上**OpenCC**并未实现其核心互转功能。
