### ISSUE TITLE
繁体翻译成简体，好多简体字会变成框框𫚥

### ISSUE THREAD

**Issue by miaofree** [BYVoid/OpenCC#365]
在将繁体句子转换成简体句子，好多原本就是简体的字会变成“𫚥”
比如：鰕、檵、蒍、魟、溡 等简体字
可以在网页版测试。

**Comment by sgalal** [comment]
Related: https://github.com/BYVoid/OpenCC/issues/121

目前的解決方法是自己修改轉換規則，只保留 Unicode 基本區的字。

轉換規則：<https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TSCharacters.txt>

**Comment by sgalal** [comment]
「鰕、檵、蒍、魟、溡」等字並非简体字

**Comment by miaofree** [comment]
谢谢提供解决方法！
是不是把框框的那些字删掉就可以了

**Comment by sgalal** [comment]
是的。其实更简单的方法是安装字体。

**Comment by miaofree** [comment]
转换后是给别人用的，所以没有办法通过安装字体解决。
除了一个个的删除，有没有批量删除框框字的方法？
