### ISSUE TITLE
Document program for offline use

### ISSUE THREAD

**Issue by jidanni** [BYVoid/OpenCC#368]
```
$ man opencc
No manual entry for opencc
$ opencc --help

Open Chinese Convert (OpenCC) Command Line Tool
Author: Carbo Kuo <byvoid@byvoid.com>
Bug Report: http://github.com/BYVoid/OpenCC/issues

Usage: 

   opencc  [--noflush <bool>] [-i <file>] [-o <file>] [-c <file>] [--]
           [--version] [-h]

...

```

OK, but say what it converts from, what it converts to, can they be
reversed, and should they both be utf8 or what etc.

Anyway, https://github.com/BYVoid/OpenCC should be copied to
/usr/share/doc/... (e.g., for Debian), and the the man page or usage
should link to that file, so users wouldn't need an internet connection
to learn how to use the program.

**Comment by sgalal** [comment]
I am sorry but our current maintainers are not familiar with these. Would you please make a pull request?

**Comment by jidanni** [comment]
It is these,
https://www.cyberciti.biz/faq/linux-unix-creating-a-manpage/
https://wiki.debian.org/ManPage
https://wiki.archlinux.org/index.php/Man_page

**Comment by BYVoid** [comment]
Thanks. It would be great if you can provide a man page for opencc and create a pull request.

I would be happy to merge your contributions.
