### ISSUE TITLE
how to define data directory in api at running time

### ISSUE THREAD

**Issue by hxsnow10** [BYVoid/OpenCC#373]
it seems the data directory is generated at compile time. 
can i define data directory in api at running time?

Thank you very much

**Comment by sgalal** [comment]
You can create your own **data files** in [this format](https://github.com/BYVoid/OpenCC/tree/master/data/dictionary), and the **configuration file** in [this format](https://github.com/BYVoid/OpenCC/tree/master/data/config). Then,

```sh
$ opencc -i <input file> -o <input file> -c <config file>
```

This is the command line usage. The api should be the same.

Note that the path to the data files are set in the configuration file.

If you use .txt for data files, either you can convert them to .ocd by `opencc_dict`, or you can change the type to "text" in the configuration file.

**Comment by hxsnow10** [comment]
@sgalal  thank you. So just opencc::SimpleConverte(**absolute_config_path**) , it can automately load data from configDirectory , right?( it seems like this from source)

**Comment by BYVoid** [comment]
You can create temporary files and load them.

**Comment by sgalal** [comment]
Here is a working example:

```cpp
#include <iostream>
#include <opencc/opencc.h>

int main() {
  const opencc::SimpleConverter converter("/path/to/my/config.json");
  std::cout << converter.Convert("奇怪") << std::endl;
}
```

Config:

`config.json`

```json
{
  "name": "A simple configuration",
  "segmentation": {
    "type": "mmseg",
    "dict": {
      "type": "text",
      "file": "test.txt"
    }
  },
  "conversion_chain": [{
    "dict": {
      "type": "text",
      "file": "test.txt"
    }
  }]
}
```

Dictionary:

`test.txt`

```raw
奇怪	竒恠
```

Output:

```raw
竒恠
```
