### ISSUE TITLE
建議：使用這個漢語大詞典的檔案來增加不少簡繁詞語！

### ISSUE THREAD

**Issue by BSBMyee** [BYVoid/OpenCC#374]
這不是一個問題，則是個建議。我剛剛找到這件檔案，是從漢語大詞典的。裏面有非常多詞語，最有幫助的是每一行包括著簡體/繁體版（if applicable）。我覺得這個檔案可以對你們的轉換器有很大的幫助！

檔案是從這個地方來的（他們其它的檔案也可能有幫助）：https://github.com/cjkvi/cjkvi-dict

我不太知道這個檔案的繁體字是否台灣或是香港的繁體

我希望這個帖子有幫助！

[hydcd-word (漢語大詞典).txt](https://github.com/BYVoid/OpenCC/files/4289952/hydcd-word.txt)

--------------------------------------------------------------------------------------------

English version:  This isn't an issue, this is a suggestion instead.  I just found this document which is from the Big Chinese Character Dictionary (漢語大詞典).  It has a LOT of entries and might be really helpful because each line contains the simplified and traditional version of the word separated by a "/".  The words that are the same in traditional and simplified do not have a "/" in the line.  I think this document could really help to add words to the STPhrases.txt file.

This document is from this github repository (their other txt files could also be helpful): https://github.com/cjkvi/cjkvi-dict

I'm not sure whether or not the traditional characters in the document are according to Taiwanese or Hong Kongese standards.

I hope this helps!

**Comment by BYVoid** [comment]
謝謝建議。OpenCC並不計劃做成字典，收錄大量無歧義的詞語。
