### ISSUE TITLE
一個轉換錯誤：宋干節

### ISSUE THREAD

**Issue by BSBMyee** [BYVoid/OpenCC#375]
宋干节 --> 宋干節

[STPhrases.txt](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/STPhrases.txt ) 缺少宋干節這個詞。

![image](https://user-images.githubusercontent.com/43587109/75930593-f0daa400-5e40-11ea-90f4-8f1f4dcd547e.png)

**Comment by sgalal** [comment]
謝謝提出！歡迎發 Pull request

**Comment by BYVoid** [comment]
Done https://github.com/BYVoid/OpenCC/commit/822c7af0399d9040b62cbc1ebdc7a91f61dce363
