### ISSUE TITLE
STPhrases.txt文件，才可以 ->纔可以

### ISSUE THREAD

**Issue by lengyuan** [BYVoid/OpenCC#379]
台湾和香港应该都用“才可以”了。"纔可以"已经不再使用了。

另外，STPhrases.txt文件是否支持人工修改？我试着把这条删除，然后重新编译，但是“才可以”还是会被转为“纔可以”。

谢谢

**Comment by sgalal** [comment]
<div lang="zh-HK">

STPhrases.txt 是「大陸簡體」到「OpenCC 繁體」。「OpenCC 繁體」用「纔可以」。這是因為 OpenCC 遵循「各地標準『能分則不合』」原則，而「大陸繁體」用「纔可以」。

STPhrases.txt 支持人工修改。但僅刪除「纔可以」一條是不夠的，還要刪除「纔可」。最好是將含「纔」字的條目都刪去。

當然，對於你的問題，不需要作如此修改，只是需要更換配置文件：

- `s2t`：「大陸簡體」到「OpenCC 繁體」
- `s2tw`：「大陸簡體」到「臺灣繁體（臺灣正體）」
- `s2hk`：「大陸簡體」到「香港繁體」

我先關閉這個 issue，若還有問題歡迎重開。

</div>
