### ISSUE TITLE
关于"打开"一词转换结果的疑问

### ISSUE THREAD

**Issue by Darwel** [BYVoid/OpenCC#386]
使用 s2twp.json 配置的转换
"打开"->"開啟"
"打开了"->"打開了"

为什么"打开了"转换出来不是"開啟了"？

**Comment by Darwel** [comment]
好像了解了，是因为使用STPhrases分词，将"开了"作为了一个词汇。

**Comment by sgalal** [comment]
這種不一致應該屬於 bug 吧？

**Comment by Darwel** [comment]
> 這種不一致應該屬於 bug 吧？

我不确定是否应该归类为bug，因为相同的，还有：
"默认"->"預設"(属于IT用语)
"默认了"->"默認了"

在没有上下文联系时，"默认"->"預設" 并不能算准确的转换。

**Comment by sgalal** [comment]
我覺得需要台灣人確認一下，台灣有「默認了」的説法麼？
