### ISSUE TITLE
Windows MSYS Build 預設說明編譯設定，轉換檔案時間太慢。

### ISSUE THREAD

**Issue by qopencc** [BYVoid/OpenCC#393]
環境:

commit 8e8fb25707b5ef5709e1a278149ce88217a5fbf6
gcc version 9.3.0 (Rev2, Built by MSYS2 project)

Windows MSYS:

cmake -H. -Bbuild -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX="path/to/install"
cmake --build build --config Release --target install

轉換檔案 42 個
時間 27.10 s

Windows MSYS:

cmake -H. -Bbuild -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX="path/to/install" -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release --target install

轉換檔案 42 個
時間 9.964 s

Prebuild 預編譯 Windows (64-bit): Latest build 2020 0501 11:38
https://github.com/BYVoid/OpenCC/wiki/Download

轉換檔案 42 個
時間
9.959 s

**Comment by BYVoid** [comment]
Fixed: https://github.com/BYVoid/OpenCC/commit/d3a58f7eb207b473a2da3ff6e99b97089c17818e
