### ISSUE TITLE
ocd 與 ocd2 轉換檔案時間不同

### ISSUE THREAD

**Issue by qopencc** [BYVoid/OpenCC#394]
環境:

commit 8e8fb25707b5ef5709e1a278149ce88217a5fbf6
gcc version 9.3.0 (Rev2, Built by MSYS2 project)

Windows MSYS:

cmake -H. -Bbuild -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX="path/to/install" -DCMAKE_BUILD_TYPE=Release

opencc.exe 用 commit 8e8fb25707b5ef5709e1a278149ce88217a5fbf6

ocd : commit  33d57bd86c5da06f00559916cd64718e6c3961c6

轉換檔案 42 個
時間 4.756 s

ocd2 : commit 8e8fb25707b5ef5709e1a278149ce88217a5fbf6

轉換檔案 42 個
時間 9.964 s

txt text : commit 8e8fb25707b5ef5709e1a278149ce88217a5fbf6

轉換檔案 42 個
時間 51.82 s

**Comment by BYVoid** [comment]
這是一個已知的問題，還沒有進行改進。ocd2還沒有正式發佈。

**Comment by qopencc** [comment]
謝謝

Prebuild 預編譯 Windows (64-bit): Latest build 2020 0501 11:38
https://github.com/BYVoid/OpenCC/wiki/Download

commit 8e8fb25707b5ef5709e1a278149ce88217a5fbf6 編譯出來。
預設都是 ocd2 。



把 OpenCC\data\CMakeLists.txt ocd2 改成 ocd與  .json  ocd2 改成 ocd，重新編譯。

轉換檔案 42 個
時間 4.785 s


可是 ocd2 容量變得很小。
ocd  4.7 MB
ocd2 1.0 MB

**Comment by BYVoid** [comment]
Fixed: https://github.com/BYVoid/OpenCC/commit/d3a58f7eb207b473a2da3ff6e99b97089c17818e
