### ISSUE TITLE
Readme is incomplete on PyPI

### ISSUE THREAD

**Issue by BYVoid** [BYVoid/OpenCC#403]
On https://pypi.org/project/OpenCC/, there is only one line.

**Comment by BYVoid** [comment]
Hello @mingruimingrui,

Do you know how `get_long_description()` works on PyPI?

**Comment by mingruimingrui** [comment]
Let me check on this!

**Comment by mingruimingrui** [comment]
The problem exists in the windows build
https://files.pythonhosted.org/packages/b5/3e/fa835cfe46a550128473eb22651068b82a9c468dec30009119c96acb10dd/OpenCC-1.1.0.post1-py2.py3-none-win_amd64.whl
found on https://pypi.org/project/OpenCC/#files

Somehow, only the first line of the README.md got read.

I'll have to explore from a windows machine and try to replicate the error.

**Comment by mingruimingrui** [comment]
@BYVoid I'm having problems replicating your error.

On my desktop, I'm managing python environments using `miniconda`.

I've tested building the `.whl` files from both `python==2.7.18` and `python==3.7.6` but detected no errors in `dist-info/METADATA`.

Would you mind running the following code to ensure results are consistent?

```python
with open('README.md', 'rb') as f:
    desc = f.read().decode('utf-8')
print(desc)  # This should output the entire README
```

If the output here is expected, I highly doubt that running `python setup.py` would produce different outputs.
Though it doesn't hurt to check.
1. Run `python setup.py bdist_wheel` as usual
2. Unzip the generated `OpenCC-1.1.0.post1-py2.py3-none-win_amd64.whl` file
3. Check `OpenCC-1.1.0.post1.dist-info/METADATA`. The entire `README.md` should be present.

**Comment by mingruimingrui** [comment]
> Hello @mingruimingrui,
> 
> Do you know how `get_long_description()` works on PyPI?

@BYVoid PyPI would not perform any code execution.
The value of `long_description` in `setup.py` should have been saved to the `*.dist-info/METADATA` file and PyPI would retrieve the `long_description` value from there.

**Comment by BYVoid** [comment]
Thank you for the instructions. There is no problem on Linux and Mac OS. However the contents of `METADATA` generated on Windows are shown below:

```
Metadata-Version: 2.1
Name: OpenCC
Version: 1.1.0.post1
Summary: Conversion between Traditional and Simplified Chinese
Home-page: https://github.com/BYVoid/OpenCC
Author: Carbo Kuo, Peng Huang, Kefu Chai, LI Daobing, Asias, Peng Wu, Xiaojun Ma, 佛振
Author-email: byvoid@byvoid.com, shawn.p.huang@gmail.com, tchaikov@gmail.com, lidaobing@gmail.com, asias.hejun@gmail.com, alexepico@gmail.com, damage3025@gmail.com, chen.sst@gmail.com
License: Apache License 2.0

# Open Chinese Convert 開放中文轉換


```

**Comment by mingruimingrui** [comment]
Hey @BYVoid, would you mind testing the new build files and checking if the problem has been resolved?

**Comment by sgalal** [comment]
I have tested on Windows, the `METADATA` file in `OpenCC-1.1.1-cp37-cp37m-win_amd64.whl` is now complete.
