### ISSUE TITLE
OpenCC Python 1.1.1 is broken on Ubuntu

### ISSUE THREAD

**Issue by sgalal** [BYVoid/OpenCC#419]
The 1.1.0 version works fine, but 1.1.1 version is broken:

`docker run -it python:3.8-buster /bin/bash`

```sh
root@f3e42ddba779:/#  cat /proc/version
Linux version 4.15.0-88-generic (buildd@lgw01-amd64-036) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020

root@f3e42ddba779:/# pip install opencc
...
Successfully installed opencc-1.1.1

root@f3e42ddba779:/# python
Python 3.8.3 (default, May 16 2020, 07:08:28)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import opencc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/opencc/__init__.py", line 44, in <module>
    libopencc = CDLL(_libopenccfile, use_errno=True)
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/python3.8/site-packages/opencc/clib/lib/libopencc.so.1.1)
```

**Comment by nqzhang** [comment]
same issue found on centos7

[root@sxcmvn~]# python3.6 a.py 
Traceback (most recent call last):
  File "a.py", line 1, in <module>
    import opencc
  File "/usr/local/lib64/python3.6/site-packages/opencc/__init__.py", line 44, in <module>
    libopencc = CDLL(_libopenccfile, use_errno=True)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib64/python3.6/site-packages/opencc/clib/lib/libopencc.so.1.1)

**Comment by sgalal** [comment]
@mingruimingrui Can you help solving this problem?

**Comment by mingruimingrui** [comment]
I realized this problem as well.

For the time being, I'd recommend downgrading back to version 1.1.0, which I've tested on most minimal distributions to work.
The alternative is to download this repository and build from source with the `setup.py` script. (But this would require cmake and a c++ compiler)

In the meanwhile, I'll rebuild the Linux files.

In the long term, it might better to build and upload to PyPI directly with CI/CD so that build environments would be less of an issue.

**Comment by nqzhang** [comment]
Thank you for your fix.
1.1.0 now works on centos7 
but 1.1.1 not

**Comment by mingruimingrui** [comment]
It's done, `pip install OpenCC` should now download a patched version of the library for Linux users.

I'm sorry for the problems this caused for everyone.

**Comment by mingruimingrui** [comment]
@nqzhang Could you clear your pip cache and try again?

**Comment by nqzhang** [comment]
yes. it works now

(opencc) [root@sxcmvn~]# pip install OpenCC
Collecting OpenCC
  Downloading OpenCC-1.1.1.post1-py2.py3-none-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 5.9 MB/s 
Installing collected packages: OpenCC
Successfully installed OpenCC-1.1.1.post1
(opencc) [root@sxcmvn~]# python a.py
(opencc) [root@sxcmvn ~]#

**Comment by sgalal** [comment]
Thanks! It works for me too.
