### ISSUE TITLE
how to make static libopencc.a

### ISSUE THREAD

**Issue by FLYo0O** [BYVoid/OpenCC#423]
Hello，guys

I just successfully make install on linux os, and got libopencc.so, it runs well.
I want to know， how to build it as libopencc.a

**Comment by mingruimingrui** [comment]
I think you can use the `BUILD_SHARED_LIBS` flag.

**Comment by mingruimingrui** [comment]
Reference the gist below. Tested to work on cmake==3.17.3.

```sh
mkdir -p build/rel
cd build/rel
cmake -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE=Release ../..
make
```
