### ISSUE TITLE
`text` to `ocd2` dictionary in python

### ISSUE THREAD

**Issue by mingruimingrui** [BYVoid/OpenCC#425]
`text` based dictionaries are significantly slower than `ocd2` dictionaries.
While `opencc_dict` performs a conversion from text to ocd2, this feature is inaccessible from the python API.

I'd like to address this issue using 1 of 2 approaches
- Add convert_dict to python API.
- Perform conversion from TextDict to MarisaDict at run time.

**Comment by BYVoid** [comment]
Sure. You can expose the API to the Python interface. Node.js interface has it.

**Comment by mingruimingrui** [comment]
Aye boss, here I go coding again.

**Comment by mingruimingrui** [comment]
Would this be a better approach?
https://github.com/BYVoid/OpenCC/pull/426

**Comment by BYVoid** [comment]
Good. Do you still want a dictionary conversion Python interface?

**Comment by mingruimingrui** [comment]
> Good. Do you still want a dictionary conversion Python interface?

Nope, I found text files to be much more convenient to manage.
