### ISSUE TITLE
Could it be possible to present multiple plausible results

### ISSUE THREAD

**Issue by nemo-nullius** [BYVoid/OpenCC#427]
Thank you in advance for such a wonderful tool! Since some simplified Chinese characters are mapped to more than one traditional characters and vice versa, does opencc have such functions to present multiple plausible results?  For example, the conversion result for `祇讓他去` could be `祇[只]让他去` or something like that, or it could just expose an API to show that `祇` here has alternative choices. This will be much helpful for proofreading after conversion. Thanks a lot!

**Comment by sgalal** [comment]
There is already an API for that, please refer to `opencc::DictEntry`.

By the way, in your case, 只 is the most commonly-used one and 衹 is a variant character for 只, which is rarely used in Traditional Chinese and invalid in Simplified Chinese. So it is quite reasonable to have only 只 in the convertion result.
