### ISSUE TITLE
「兇=>凶」從台灣地區詞轉換移除

### ISSUE THREAD

**Issue by danny0838** [BYVoid/OpenCC#431]
「兇」和「凶」在多數情況下通用，但在台灣「兇」也很常見（主要用於「兇手」），我認為可以把台灣地區詞的「兇=>凶」強制轉換刪除。

**Comment by BYVoid** [comment]
根據臺灣標準，一律使用「凶」

參見 http://dict.revised.moe.edu.tw/cbdic/index.html

**Comment by danny0838** [comment]
> 
> 根據臺灣標準，一律使用「凶」
> 
> 參見 http://dict.revised.moe.edu.tw/cbdic/index.html

我從該網站沒看到「一律使用『凶』」的說法，而且用「凶」和「兇」都可以找到許多相關詞。請問您是在哪頁看到此說法，可否提供超連結或截圖？

況且，無論此網站怎麼寫。台灣人日常使用就是兩者皆有，只要多搜尋幾個網站就能看到。全部統一成「凶」反而違反台灣人的使用習慣。
