### ISSUE TITLE
「曬=>晒」從台灣地區詞轉換移除

### ISSUE THREAD

**Issue by danny0838** [BYVoid/OpenCC#432]
如題，在台灣「曬」也很常見，可以取消強制轉換。

**Comment by sgalal** [comment]
我也注意到這一問題。

對應的 OpenCC 的詞庫是  `TWVariants.txt`  這一檔案，目前該檔案使用的是台灣標準（即《常用國字標準字體表》等表）。既然台灣標準不符合台灣的實際用字情況，不如審視一次該檔案，修正其中錯誤的轉換規則。

之前香港詞庫也做過類似修正：#418。

如果有興趣，歡迎 pr，也歡迎在 https://t.me/open_chinese_convert 中討論。

**Comment by BYVoid** [comment]
我覺得臺灣標準和香港「標準」不同，因爲臺灣標準的普及度和使用率都要高很多，所以傾向於維持臺灣標準不變。

**Comment by danny0838** [comment]
> 我覺得臺灣標準和香港「標準」不同，因爲臺灣標準的普及度和使用率都要高很多，所以傾向於維持臺灣標準不變。

這個我有異議。《常用國字標準字體表》是1979出版的，年代已經比較久遠了。

就台灣標準及實際使用情形而言，有個可能更可以參考的是台灣的編碼標準 [Big5](https://zh.wikipedia.org/wiki/%E5%A4%A7%E4%BA%94%E7%A2%BC)（約1986年公布），此編碼的常用字、次常用字本身就是參考《常用國字標準字體表》、《次常用國字標準字體表》選定，而台灣的實際用字情形也會受電腦編碼影響（Big5沒收的字難以印刷，就少見）。

而這裡的「曬」「晒」都就是收在Big5的常用字區。

**Comment by sgalal** [comment]
> 我覺得臺灣標準和香港「標準」不同，因爲臺灣標準的普及度和使用率都要高很多，所以傾向於維持臺灣標準不變。

台灣標準也存在問題，例如台灣文本中「曬」遠多於「晒」，又如目前「臺」字寫作「台」也十分常見等。為了不引起困惑，還是修改比較好。
