### ISSUE TITLE
「阪」與「坂」

### ISSUE THREAD

**Issue by danny0838** [BYVoid/OpenCC#433]
目前 `TSCharacters.txt` 有「阪=>阪 坂」，`STCharacters.txt` 卻沒有對應的轉換，何解？

這兩字應該是異體字關係，《簡化字總表》也沒這兩字。

「彞=>彝」也類似， `TSCharacters.txt` 有，`STCharacters.txt` 卻沒有對應的轉換。

**Comment by sgalal** [comment]
關於「阪」與「坂」：

zh_CN 環境依據《通用規範漢字表》，「阪」為「坂」之異體字，且註明「阪」可用于地名，如「大阪」。

實際使用時，會區分「坂」與「阪」二者，如「阪急电铁」、「平南铁路坂田站」。

根據從分不從合原則，既然「坂」與「阪」是區別使用的，則 `TSCharacters.txt` 中「阪=>阪 坂」應該改為「阪=>阪」，即刪除該條轉換規則。

**Comment by danny0838** [comment]
同意刪除 TSCharacters.txt 的「阪=>阪 坂」。

不曉得「彞=>彝」怎麼說？或是應該另開主題討論？

**Comment by sgalal** [comment]
「彞」是異體，OpenCC 不轉換異體，所以「彞=>彝」應該刪

**Comment by danny0838** [comment]
@sgalal 說「OpenCC 不轉換異體」。但我事後整理碼表又查了些資料，覺得此說還有要商榷的地方。

首先，《通用規範漢字表》的存在目的就是規範中國流通的漢字，按此，表外漢字應該是要盡量避免使用的，除了一些特殊情況，例如專業性的古籍印刷、書法和牌匾等手寫字。

而附表的規範字、繁體字、異體字，目的顯然是讓本來想使用相關繁體字、異體字的人，有代換為適當規範字的依循。

而我們都知道，OpenCC 所謂的「簡體」，實際上就是「中國規範體」，按此繁轉簡時無論是《通用規範漢字表》裡的繁體字或異體字，都應該要替換成對應的規範字，才符合《通用規範漢字表》的精神。當然，個別有特別說明的例外狀況是可以允部不替換的，比如附註說「『阪』可用於地名」，那麼原文用於地名的「阪」便不該轉換，其他情況都應該替換成規範字「坂」。

再舉一些實例，「糰」、「嚐」都是表中的異體字，台灣有時會使用二者，倘若如前所述「OpenCC 不轉換異體」，而在繁轉簡時不把「糰」、「嚐」轉換為「团」、「尝」，中國用戶可以接受嗎？我個人是相當懷疑的……。

至於簡轉繁的情況，則牽涉 OpenCC 認定的正體漢字為何，把規範字轉為適當的正體漢字即可。

因此，對於「坂」、「阪」，我的理解是 OpenCC 應提供適當的轉換，由於「阪」實際上主要就是用於人名、地名，因此TSCharacters.txt 應維持「阪=>阪 坂」，個別非人名或地名的詞彙可建入 TSPhrases.txt 轉成「坂」；STCharacters.txt 有點尷尬，因為我還不清楚 OpenCC 認定的正體字為何，或兩者皆可，以及哪些情況「坂」適合轉為「阪」，但在確定之前可以先建立「坂=>坂 阪」，之後可再逐提供適當的詞彙轉換。

至於「彞」、「彝」，《通用規範漢字表》是有把「彝」列為二級字，沒有把「彞」列入，但並沒有對照表提到「彞」。對此我的理解是《通用規範漢字表》不鼓勵「彞」的使用，但對於已經存在「彞」的文本，由於《通用規範漢字表》也沒有告訴我們可以把它們替換為哪個適當的規範字，為避免出錯，當以保留原樣為宜。因此無論是繁轉簡或簡轉繁，都不需要做「彞<=>彝」的轉換。

「秘<=>祕」的問題，按現在的理解，繁轉簡應做「祕=>秘」；簡轉繁也是比較尷尬，如果 OpenCC 認定「祕」是正體，則應該「秘=>祕」，但考量台灣、香港多數情況都用「秘」，可能還得加上地區字轉換回「秘」；若 OpenCC 認定「秘」「祕」語義有別應區分，則繁轉簡應改為「秘=>秘 祕」及少數適當詞彙轉換為「祕」。

「唇<=>脣」的問題，按現在的理解，繁轉簡應做「脣=>唇」；簡轉繁方面，如果 OpenCC 仍認「脣」為正體，可以先不改，但考量港台都是以「唇」為主，應該考慮加地區字轉換「脣=>唇」。

「冢<=>塚」的問題，按現在的理解，繁轉簡應做「塚=>冢」；簡轉繁方面，即使 OpenCC 認「冢」為正體，我認為人名的「塚」都是應區分的，因此應「冢=>冢 塚」，並建詞彙表把部分「冢」轉為「塚」，例如「手塚治虫」等等。又因台港多用「塚」，應再加上地區字轉換「冢=>塚」（部分例外可建詞表維持「冢=>冢」）。
