### ISSUE TITLE
「脣/唇」異體字是否應取消簡繁轉換？

### ISSUE THREAD

**Issue by danny0838** [BYVoid/OpenCC#435]
《簡化字總表》把「脣」列為不再使用的異體字。「唇」「脣」不是繁簡字關係，如果 OpenCC 不處理異體字，此字或許不應該納入簡繁轉換。

地區轉換方面就比較尷尬，《常用國字標準字體表》只有「脣」字。《異體字字典》以「脣」為正字（作「嘴唇」義時）。Big5 編碼中，「脣」「唇」都列為常用字。可是就台灣日常使用而言，「唇」是壓倒性的多數，「脣」幾乎沒有人用。所有台灣的網站、新聞媒體、出版著作，甚至國小到高中的國語文課本，絕大部分都是用「唇」字。

**Comment by danny0838** [comment]
有結論嗎？我個人認為取消「唇<=>脣」的簡繁轉換比較簡單。既然兩岸三地幾乎都只用「唇」，不轉換應該不會造成什麼實質困擾。

**Comment by sgalal** [comment]
我推測當初 OpenCC 標準制訂時，因為台灣標準、香港標準都是用「脣」，所以用「脣」。

但實際上香港、台灣都是用「唇」，其實沒有地方用「脣」XD

所以關鍵是要不要把 OpenCC 標準也改用「唇」。我想這個可以討論後決定。

**Comment by BYVoid** [comment]
確實如此，包括日本在內，「唇」更加常用，不過更加保守的韓國使用「脣」。

我個人傾向於維持OpenCC不變，使用「脣」，但是中國大陸、臺灣、香港可以都用「唇」。

簡繁轉換中隱含了對中國大陸標準的異體字轉換，嚴格講無歧義的單字簡繁轉換就是異體字轉換。
