### ISSUE TITLE
「秘/祕」異體字是否應取消簡繁轉換？

### ISSUE THREAD

**Issue by danny0838** [BYVoid/OpenCC#437]
如題，《簡化字總表》無此二字，這兩字似乎不是簡繁轉換的範圍。

**Comment by danny0838** [comment]
《通用规范汉字表》有規範中國正體是「秘」。台灣兩字都用。

如果要取消，目前 STPhrases.txt 裡的「秘=>祕」是否也應該取消？即：

```
个中奥秘	箇中奧祕
秘制	祕製
秘录	祕錄
```

如果不做異體字轉換，應改為：

```
个中奥秘	箇中奧秘
秘制	秘製
秘录	秘錄
```

**Comment by sgalal** [comment]
> 如果不做異體字轉換，應改為：
> 
> ```
> 个中奥秘	箇中奧秘
> 秘制	秘製
> 秘录	秘錄
> ```

我贊同這樣修改

**Comment by hfhchan** [comment]
香港實際上已近全盤用秘。

**Comment by danny0838** [comment]
最近的一些想法參考https://github.com/BYVoid/OpenCC/issues/433#issuecomment-650566055。簡而言之，繁轉簡應該要維持「祕=>秘」。

至於簡轉繁，我個人認為二字字義是不完全相同的，應該從分。「神祕」、「祕密」等詞如果堅持正統，當是「祕」為正體、「秘」為異體；但「秘魯」按習慣翻譯為「秘」而不用「祕」，「便秘」只能用「秘」，此外按字典「秘」還可解為「香草」。由於「秘」在台港較常用，且字義涵蓋較廣，簡轉繁時應以「秘=>秘 祕」為宜，並另建詞表把「神秘」、「秘密」等詞轉為「祕」。但因台港習慣「秘」是相對多數，可能要考慮地區用字轉換「祕=>秘」，或者按習慣考量直接以「秘」為正體？
