### ISSUE TITLE
「黏/粘」異體字是否應取消簡繁轉換？

### ISSUE THREAD

**Issue by danny0838** [BYVoid/OpenCC#438]
《簡化字總表》無此二字，應該算中國/台港澳間的異體字或地區用字差異。

目前 `TSCharacters.txt` 有黏=>粘，`STCharacters.txt` 無相關定義，但 `STPhrases.txt` 又有一些相關詞組。

不曉得中國異體是否也當做簡繁轉換處理。如果要當簡繁轉換，`STCharacters.txt` 應該要加回 粘=>黏，如果不視作簡繁轉換，看是要移除相關轉換還是加到 `TWVariants.txt`。

**Comment by sgalal** [comment]
中國大陸「粘」、「黏」是區別使用的。「黏」讀 nián ㄋㄧㄢˊ 例如「黏土」、「黏性」，「粘」讀 zhān ㄓㄢˉ 例如「粘貼」、「粘膠」、「油粘米」。

應該不視為簡繁關係。

**Comment by danny0838** [comment]
這樣說來似乎也不應該加入台灣異體了？

**Comment by hfhchan** [comment]
香港幾乎一律用黏？腸黏連也是黏。

**Comment by danny0838** [comment]
本來是誤以為中國只用「粘」。如果三地都是二字有區分的用，那應該不用地區字轉換。至於如果個別用詞也有差異，那就比較麻煩了，可能只能就幾個較明確的詞做地區詞轉換了。

**Comment by buganini** [comment]
「粘」在台灣有用於姓氏，讀nian2

**Comment by danny0838** [comment]
抱歉，我之前查錯版本。目前的 OpenCC 並沒有「黏/粘」的簡繁轉換。而就前述討論也可確定「黏」與「粘」有一些字義差異，因此也不適合做地區用字轉換。

未來若有發現特定用詞兩岸三地用法明顯不同，可再加入適當的地區詞轉換。
