### ISSUE TITLE
阳谷=>陽穀/陽谷

### ISSUE THREAD

**Issue by danny0838** [BYVoid/OpenCC#441]
目前的轉換表是「阳谷=>陽穀」、「阳谷县=>陽穀縣」，尷尬的是「陽谷」也是專有名詞（中醫穴名），在中醫相關文本相當常用。

我想至少可以先加入「阳谷穴=>陽谷穴」，至於「阳谷=>陽穀」應改為「阳谷=>陽穀/陽谷」或「阳谷=>陽谷/陽穀」可能有得討論了……。

**Comment by sgalal** [comment]
贊同。「阳谷=>陽穀」應改為「阳谷=>陽穀/陽谷」或「阳谷=>陽谷/陽穀」可以根據詞頻決定。

**Comment by danny0838** [comment]
有比較權威且開放的詞頻資料庫嗎？找了一個[中研院](http://elearning.ling.sinica.edu.tw/CWordfreq.html)的詞頻庫，不過看起來有點老了，兩個詞都找不到……。

**Comment by danny0838** [comment]
RIME 自帶的 essay.txt 中，「陽穀」629、「陽谷」0。

Google 搜尋「"陽谷"」有 156,000 筆，「"陽穀"」有 80,900 筆。

百度搜尋「陽谷」有 119,000 筆，「陽穀」有 31,500 筆。

看來結果有點分歧呢……。

**Comment by BYVoid** [comment]
可以添加一些合成詞來分別。
