### ISSUE TITLE
巖 岩

### ISSUE THREAD

**Issue by sgalal** [BYVoid/OpenCC#473]
現時 `st_multi.txt`：

```
岩	巖 岩	「岩」只用於「岩石」相關意義，其餘用「巖」。	沉積岩 岩漿 巖壁 中空成巖
```

但「岩」、「巖」實際上均為「岩石」義。

P.S.: 日文從分，讀音不同，但具體差別似不明確。

**Comment by BYVoid** [comment]
日語「岩」「巌」音讀均爲「がん」，你是說訓讀不同嗎？

**Comment by sgalal** [comment]
對，訓讀不同，「岩」いわ，「巖」いわお。但我剛剛又重新查詢了其他詞典，似乎並沒有區別，均可以讀 いわ 和 いわお。

**Comment by hfhchan** [comment]
古代「岩」雖然作為「巖」的俗字，但在現實使用上「巖」「岩」用法上並不完全重合。
我主張繼續區分，「巖」留給傳統意義上的「巖」，即懸崖峭壁，「巖壁」「巖穴」「巖石」（指「巖、石」），而「岩」留給地質學上的石頭分類，比如「岩石」「沉積岩」「岩漿」。

**Comment by William8915** [comment]
> 對，訓讀不同，「岩」いわ，「巖」いわお。但我剛剛又重新查詢了其他詞典，似乎並沒有區別，均可以讀 いわ 和 いわお。

日語訓讀主要是「岩」いわ，「巖」いわお，輸入法都是這樣設定，雖然可以讀成另一種但是罕用。語源上説お（ほ）是秀，高く秀でている之義。不過日文的這種區分僅可作為參考。

**Comment by sgalal** [comment]
> 古代「岩」雖然作為「巖」的俗字，但在現實使用上「巖」「岩」的用法並不完全重合。
> 我主張繼續區分，「巖」留給傳統意義上的「巖」，即懸崖峭壁，「巖壁」「巖穴」「巖石」（指「巖、石」），而「岩」留給地質學上的石頭分類，比如「岩石」「沉積岩」「岩漿」「岩層」。

好
