### ISSUE TITLE
Can not make an instance of OpenCC with configuration file tw2t.json

### ISSUE THREAD

**Issue by songjiz** [BYVoid/OpenCC#519]
Hi，I am making a ruby [gem](https://github.com/songjiz/opencc-rb) for OpenCC, and I found that can not make an instance of OpenCC when using `tw2t.json` configuration file. 
So I try with C lang, but the result is same. I'm not familiar with C lang and if I use it incorrectly, please let me know.
Thanks!

```c
#include <stdio.h>
#include <string.h>
#include <opencc/opencc.h>

int main() {
  const char* input = "汉字";
  char* converted;
  opencc_t opencc = opencc_open("tw2t.json");
  if (opencc == (opencc_t)-1) {
    printf("Error: can not make an instance of OpenCC ):");
  } else {
    converted = opencc_convert_utf8(opencc, input, strlen(input));
    printf(converted);
    opencc_convert_utf8_free(converted);
    opencc_close(opencc);
  }
  return 0;
}

```

```shell
gcc -l opencc main.c -o test
```

```shell
./test # => Error: can not make an instance of OpenCC ):
```

**Comment by BYVoid** [comment]
tw2t was recently added https://github.com/BYVoid/OpenCC/commit/e25b0559fa523fd003d3fd3205ef2a1a381c5746 by @sgalal. What's your version?

**Comment by songjiz** [comment]
@BYVoid 
Thanks for your reminder.
I am using v1.1.1 and this version does not support tw2t. It's ok under the master branch. I did not pay attention to the README document. 😁
