### ISSUE TITLE
毫无干劲 => 毫無干勁

### ISSUE THREAD

**Issue by timxx** [BYVoid/OpenCC#521]
单独转换“干劲”结果为“幹勁”，“毫无干劲“一起转换得出来是“毫無干勁”
似乎是分词分成 毫/无干/劲 了，因为”无干“转换结果就是”無干“

**Comment by sgalal** [comment]
可以將「毫无」加入詞典中

**Comment by sgalal** [comment]
Can you create a pull request for that?
