### ISSUE TITLE
Dict::Match() does not check for exact match

### ISSUE THREAD

**Issue by coin3x** [BYVoid/OpenCC#523]
Broken since be2492c
https://github.com/BYVoid/OpenCC/blob/539e4e9e3d86bb1d0d817fd531cf7107263c5199/src/MarisaDict.cpp#L48-L52

https://github.com/BYVoid/OpenCC/blob/539e4e9e3d86bb1d0d817fd531cf7107263c5199/src/DartsDict.cpp#L55-L60

Example Dict:
爲 -> 為

`maxLength`: 3

```cpp
std::string query("爲123");
dict->Match(query);
```
`len`: 6

Expected: `Optional::Null`
Actual: `DictEntry 爲 -> 為`

**Comment by BYVoid** [comment]
Thanks.
