### ISSUE TITLE
请问是否会考虑收录游戏相关的名词转换

### ISSUE THREAD

**Issue by digglife** [BYVoid/OpenCC#540]
游戏名示例 ：
|简体中文| 繁体中文|
| ---- | ----|
|塞尔达 |薩爾達|
|马力欧| 瑪利歐|
|刺客信条|刺客教條|

如果符合项目本意，我可以提 PR。

**Comment by sgalal** [comment]
谢谢！

可以仿照已有的文件名称，新建一个单独的文件

**Comment by sgalal** [comment]
@digglife ping?

**Comment by digglife** [comment]
不好意思，前些天休息没写Code 😄

PR已提交，请审阅。

另外，很多游戏可能存在副标题翻译也不同的问题，但副标题通常是一些比较常见的词组，并非游戏专有，所以没有提交到列表里。

以 Need For Speed 为例，几乎每一代的副标题的翻译都不一样。

| 台湾正体 | 大陆简体|
| ---- | ---- |
|極速快感：玩命山道 | 极品飞车：生死卡本谷|
|極速快感：超熱力追緝 | 极品飞车：热力追踪|
|極速快感：新全民公敵 | 极品飞车：最高通缉|
|極速快感：職業街頭 | 极品飞车：街头狂飙|
|極速快感：亡命天涯 | 极品飞车：亡命狂飙|
|極速快感：進化世代 | 极品飞车：变速|
|極速快感：臥底風雲 | 极品飞车：无间风云|
|極速快感：生存競速 | 极品飞车：宿敌|

**Comment by digglife** [comment]
这次主要是爬了 Wikipedia 上的相关网页获取到的对应关系，后续会持续更新。

**Comment by sgalal** [comment]
谢谢！我不确定 Wikipedia 会不会有 License 的问题

**Comment by digglife** [comment]
游戏标题的翻译应该是公有领域吧？换句话说「Mario」 对应简体中文「马力欧」这个应该不算是 Wikipedia 的原创内容吧，即便是当真这个翻译本身有 License，那也应该是任天堂的？我虽然玩儿游戏，但知识也有限，不可能知道所有游戏相关的繁简对应，只能通过网络搜集，如果 Wikipedia 看到的这种翻译不能用，那还真不知道哪里的能用了。

**Comment by sgalal** [comment]
有道理

**Comment by BYVoid** [comment]
謝謝添加，我在pull request中留言了。

**Comment by dqwyy** [comment]
很明显不存在任何的侵权问题，放心用，无须担忧。
如需更多资讯，请参照
https://zh.wikipedia.org/wiki/Module:CGroup/Games
