### ISSUE TITLE
Linux 相关术语转换错误（“衍生发行版”）

### ISSUE THREAD

**Issue by hosiet** [BYVoid/OpenCC#549]
问题发现于 https://www.debian.org/derivatives/index.zh-tw.html 页面中。

复现方法：

```
% cat a.txt
衍生发行版
发行版

% opencc -c s2tw.json < ./a.txt
衍生髮行版 （错误）
發行版 （正确）
```

“生发”影响了语义导致转换错误。希望 opencc 能够进行额外处理。

**Comment by sgalal** [comment]
可以在词库中加入以「生」字结尾的词，如「衍生」
