### ISSUE TITLE
rapidjson not found when set USE_SYSTEM_RAPIDJSON=ON

### ISSUE THREAD

**Issue by hosiet** [BYVoid/OpenCC#553]
The latest commit 6cdd438556c176d9f13f092796663e8745bc76e7 introduced `USE_SYSTEM_*`. When set `USE_SYSTEM_RAPIDJSON=ON`, opencc will not build successfully.

The reason is that currently `src/Config.cpp` is using `#include "document.h"` to include header file from rapidjson library:

https://github.com/BYVoid/OpenCC/blob/6cdd438556c176d9f13f092796663e8745bc76e7/src/Config.cpp#L22-L24

However, the canonical path of this header is `/usr/include/rapidjson/document.h` when installed in the system. As an example, you may find a file list of libjapidson in Fedora at https://koji.fedoraproject.org/koji/rpminfo?rpmID=23064012 :

```

/usr/include/rapidjson | 0
/usr/include/rapidjson/allocators.h | 10,311
/usr/include/rapidjson/document.h | 114,196
/usr/include/rapidjson/encodedstream.h | 10,686
/usr/include/rapidjson/encodings.h | 28,553
/usr/include/rapidjson/error | 0
/usr/include/rapidjson/error/en.h | 3,870
/usr/include/rapidjson/error/error.h | 5,824
/usr/include/rapidjson/filereadstream.h | 2,988
/usr/include/rapidjson/filewritestream.h | 3,139
/usr/include/rapidjson/fwd.h | 4,035
/usr/include/rapidjson/internal
[... omitted]

```

This means that the buildsystem will not be able to find document.h in build time. Perhaps we should use `include <rapidjson/document.h>` in this case.

On the other hand, librapidjson natually provides `RapidJSONConfig.cmake` file, which may ease CMake configuration. Maybe we should consider using that.

**Comment by BYVoid** [comment]
Does https://github.com/BYVoid/OpenCC/commit/fbc670770c69f7891e917708637b702a25378034 fix the problem?

I don't have an environment to verify this change.

It should be great if you can help support `RapidJSONConfig.cmake`.

**Comment by hosiet** [comment]
Thanks, the previous commit fixes this problem.

Whether to use `.cmake` config is another question. For the current specific issue, it can be marked as fixed.
