### ISSUE TITLE
Conversion of 著 from Traditional to Simplified

### ISSUE THREAD

**Issue by dddlr** [BYVoid/OpenCC#555]
著 is currently not converted correctly from Traditional Chinese (Taiwan standard) to Simplified Chinese.

For example, 看著 著急 著數 are converted to 看著 著急 著数 on the [OpenCC demo site](https://opencc.byvoid.com/) instead of 看着 着急 着数. I've noticed that many Hong Kong websites use 著 instead of the Hong Kong/Mainland Chinese standard 着 to write zoek6, so it's not only an issue in Taiwan.

Only existing issue I could find was #5 back in 2011, but that was about Simplified to Traditional conversion, not the other way around.

**Comment by yan12125** [comment]
Apparently tw2s (Traditional Chinese (Taiwan Standard) to Simplified Chinese) converts "著" while t2s (Traditional Chinese to Simplified Chinese) does not.
```
$ echo "看著 著急 著數" | opencc -c t2s 
看著 著急 著数

$ echo "看著 著急 著數" | opencc -c tw2s
看着 着急 着数
```

**Comment by ayaka14732** [comment]
@yan12125 👍🏻️
