### ISSUE TITLE
严重建议开发一款Chrome扩展，这样能更方便的随手转换

### ISSUE THREAD

**Issue by dodolook8** [BYVoid/OpenCC#562]
希望能像Chrome上的扩展：“简繁转化工具”、“繁简转换”那样开发一个crx扩展，有输入框，在右上角图标处点开就能用，可在里面转。谢谢。

**Comment by BYVoid** [comment]
Chrome擴展依賴WebAssembly，必須先把OpenCC編譯到WebAeesmbly纔可以。

**Comment by sgalal** [comment]
之前的 issue 裏好像有人做過？

**Comment by dodolook8** [comment]
简繁汉字转换 0.0.1   https://chrome.google.com/webstore/detail/simplified-traditional-ch/imnghkiliggemhkejgppikbgocegpjec/
这款扩展就做到了，里面代码用的就是你们opencc的库，但很可惜，它只能转换页面里的文字。希望能开发个有输入框的，我们能复制进去转换。就像“简繁转化工具”、“繁简转换”这2个chrome商店里的扩展。

> Chrome擴展依賴WebAssembly，必須先把OpenCC編譯到WebAeesmbly纔可以。


简繁汉字转换 0.0.1   https://chrome.google.com/webstore/detail/simplified-traditional-ch/imnghkiliggemhkejgppikbgocegpjec/
这款扩展就做到了，里面代码用的就是你们opencc的库，但很可惜，它只能转换页面里的文字。希望能开发个有输入框的，我们能复制进去转换。就像“简繁转化工具”、“繁简转换”这2个chrome商店里的扩展。

**Comment by sgalal** [comment]
有输入框的话，https://opencc.byvoid.com/ 应该可以

**Comment by tnychn** [comment]
小弟前幾天寫了個類似的 Chrome/Firefox 擴展，事後才看到這個 issue 😂 。
我用了 [opencc-js](https://github.com/nk2028/opencc-js) 來做網頁中文字的簡繁轉換，不需要 WebAssembly 編譯。
這個擴展沒有輸入框，但跟 @dodolook8 提到的 [Simplified Traditional Chinese Converter](https://chrome.google.com/webstore/detail/simplified-traditional-ch/imnghkiliggemhkejgppikbgocegpjec/) 不同的是可以一鍵轉換頁面內所有文字和自動轉換頁面內 JavaScript 渲染的文字。希望採納。

Source Code: https://github.com/tnychn/opencc-extension

**Comment by sgalal** [comment]
@tnychn 讚！可以將 <https://github.com/tnychn/opencc-extension> 加入到本專案 README 中

**Comment by sgalal** [comment]
Fixed in #600
