### ISSUE TITLE
Python package for Windows is not uploaded

### ISSUE THREAD

**Issue by BYVoid** [BYVoid/OpenCC#564]
@mingruimingrui 

I tried to run the workflow: https://github.com/BYVoid/OpenCC/runs/2028516999?check_suite_focus=true

It was successful, but I could only find packages for mac and linux uploaded to: https://pypi.org/manage/project/OpenCC/release/1.1.2/

**Comment by BYVoid** [comment]
Right. https://github.com/BYVoid/OpenCC/blob/master/.github/workflows/python.yml#L15 does not have 3.9 either.

**Comment by AntonOfTheWoods** [comment]
Sorry, I've only used poetry for pushing to pypi. It is strange though because there does appear to be a 3.9 for Mac, though I might be misinterpreting. In any case, there is an error when trying to install via poetry with 3.9 on Linux

**Comment by mingruimingrui** [comment]
Woah sorry! Py3.9 was in beta when I last updated the github ci. Let me also take a look at potential build errors for windows.

**Comment by mingruimingrui** [comment]
Py3.9 is an easy fix, just add to build matrix.

**Comment by mingruimingrui** [comment]
Windows github workflow is a little strange, github action seems to have stopped short of uploading to pypi
