### ISSUE TITLE
1.1.2 版本下 fcitx-rime log 中提示 opencc config not found

### ISSUE THREAD

**Issue by ouuan** [BYVoid/OpenCC#570]
```
$ cat /tmp/rime.fcitx-rime.ERROR
Log file created at: 2021/03/21 11:11:09
Running on machine: ouuan-acer-laptop-archlinux
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0321 11:11:09.719727   544 simplifier.cc:45] opencc config not found: /usr/share/rime-data/opencc/emoji.json
E0321 11:11:09.720994   544 simplifier.cc:45] opencc config not found: /usr/share/rime-data/opencc/symbol.json
```

1.1.1 版本中无此问题。我正在尝试编译，如果顺利的话会进行 git bisect。

UPD: 我放弃本地编译了：

1. 两个版本间编译安装的方式有较大变化：https://github.com/archlinux/svntogit-community/commit/102df42c21c7cdb5769b8f2baa6ae5bee30d2888#diff-37538beb61ff63edebbf735dfcf39e5d732f49183d6beb097169d971875ca422
2. 我在 bisect 的时候 5f76d79940dc4b32e7736835745dc134564b9cd9 直接让我一启动 rime 就卡死..不知道是不是编译方式有问题。

**Comment by sgalal** [comment]
Fixed in https://github.com/rime/rime-emoji/issues/28
