### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by AntonOfTheWoods** [BYVoid/OpenCC#571]
It seems that browser support could be possible for opencc. This is particularly interesting now that service workers and PWAs are making rich, offline experiences possible. Is there some major reason for not supporting browsers with the JS/TS code?

**Comment by sgalal** [comment]
Try [nk2028/opencc-js](https://github.com/nk2028/opencc-js)

**Comment by AntonOfTheWoods** [comment]
> Try [nk2028/opencc-js](https://github.com/nk2028/opencc-js)

Thanks @sgalal ! Is there some explanation of how the config options in `opencc-js` relate to those in this project? I am using the python version server-side, and very, very much want to have the same behaviour client-side too. Basically, I want the `t2s.json` behaviour, and `t: Traditional Chinese (OpenCC standard. Do not use unless you know what you are doing)` is all I can see. Or should that warning also be applied to the `t2s.json` that I'm using, and 
```const converter = OpenCC.Converter({ from: 't', to: 'cn' });```

```const converter = OpenCC.Converter('t2s.json');```

Will give exactly the same results?

**Comment by sgalal** [comment]
opencc-js is a separate project created by me.

> Will give exactly the same results?

Yes, `{ from: 't', to: 'cn' }` in opencc-js is designed to yield the same results as `'t2s.json'` in OpenCC. However, the versions of the conversion dictionaries may be slightly different, so in extremely rare cases the results may be different.

> Or should that warning also be applied to the `t2s.json` that I'm using?

Yes, I suggest using `tw2s`, `tw2sp` or `hk2s` depends on your input. It would be better to have a general one (e.g. something like `GeneralTraditionalChinese2s`), but unfortunately, this feature is not supported yet (Related: #493).

**Comment by AntonOfTheWoods** [comment]
> opencc-js is a separate project created by me.

Awesome, thanks.

> > Will give exactly the same results?
> 
> Yes, `{ from: 't', to: 'cn' }` in opencc-js is designed to yield the same results as `'t2s.json'` in OpenCC. However, the versions of the conversion dictionaries may be slightly different, so in extremely rare cases the results may be different.

That definitely works for me! :-)

> 
> > Or should that warning also be applied to the `t2s.json` that I'm using?
> 
> Yes, I suggest using `tw2s`, `tw2sp` or `hk2s` depending on your input. It would be better to have a general one (e.g. something like `GeneralTraditionalChinese2s`), but unfortunately, this feature is not supported yet (Related: #493).

My usecase is basically I really don't want traditional characters in my database at all (at this stage of the project), because that means I risk getting duplicates (a traditional and a simplified). The input can come from anywhere but I only want to go in one direction (t*->s). I know the actual situation is super complicated, and knowing whether something is "simplified" or not can sometimes be a matter of opinion. I intend to think about how this should be optimised later but for the moment, having any traditional characters at all is a massive headache, so I just want to get rid of all of them, whatever variant they belong to and make them as "simplified" as possible.

**Comment by sgalal** [comment]
> My usecase is basically I really don't want traditional characters in my database at all.

I see. In this case, there should be a `GeneralTraditionalChinese2s` option. However, since this feature is not supported yet, it is okay to continue using the `t2s` option.

**Comment by AntonOfTheWoods** [comment]
Actually for others, for future reference, it appears that nk2028/opencc-js doesn't properly support es6 imports, making it a pain to use in many circumstances.
