### ISSUE TITLE
In Wiki, the link to zhtable is outdated

### ISSUE THREAD

**Issue by MapleCCC** [BYVoid/OpenCC#594]
The link to zhtable in [this wiki section](https://github.com/BYVoid/OpenCC/wiki/%E7%B7%A3%E7%94%B1#wikipedia) has been outdated, and should be updated to `https://phabricator.wikimedia.org/source/mediawiki/browse/master/maintenance/language/zhtable/`. Unfortunately I can't open a pull request to change Wiki content, ending up having to open an issue here.

**Comment by sgalal** [comment]
Thank you! Fixed in https://github.com/BYVoid/OpenCC/wiki/%E7%B7%A3%E7%94%B1/6f3643162307911e8e1b90df3733b44b96f3bc58.

**Comment by Freed-Wu** [comment]
Wiki disappeared. Why?

**Comment by Freed-Wu** [comment]
https://github.com/BYVoid/OpenCC?tab=readme-ov-file#links-%E7%9B%B8%E9%97%9C%E9%8F%88%E6%8E%A5 still introduce non-existent wiki
