### ISSUE TITLE
転貼 does not get translated to 轉貼 in s2tw or s2twp mode

### ISSUE THREAD

**Issue by andrea-w-wang** [BYVoid/OpenCC#598]
as title.
OpenCC version: 1.1.2 (python)

To reproduce:
```
from opencc import OpenCC
cc = OpenCC('s2tw') 
print(cc.convert("転貼")) # get back "転貼"

```

**Comment by sgalal** [comment]
転 is a Japanese character, so it will not be affected when converting from simplified Chinese to traditional Chinese.
