### ISSUE TITLE
Add a build flag to disable building data for cross compilation

### ISSUE THREAD

**Issue by alex-the-man** [BYVoid/OpenCC#615]
Hello, I'm using OpenCC on iOS.

When OpenCC is cross compiled, the build fails as https://github.com/BYVoid/OpenCC/blob/master/data/CMakeLists.txt#L139 executes the cross compiled opencc_dict (targeting arm64) on the host system (x86_64).

Do you mind if I add a build flag `BUILD_DATA` following https://github.com/BYVoid/OpenCC/blob/master/CMakeLists.txt#L26  to let us disable data/dict generation during cross compilation?

If you like the idea, I could send a PR.

**Comment by driver1998** [comment]
I am trying to cross compile to Windows ARM64 on x86_64 host, and hit the same issue. A build flag to disable dict generation would be great, we build for all available architecture anyways, no need to generate the same data again.

**Comment by BYVoid** [comment]
Feel free to create pull requests. I am closing this issue now.
