### ISSUE TITLE
PyPI Github action not working

### ISSUE THREAD

**Issue by AntonOfTheWoods** [BYVoid/OpenCC#617]
It looks like the last release did not cause the PyPI action to run, and there is no `1.1.3` on PyPI.

This means there is still no Linux version for 3.9.

I will submit a version for 3.10 when we have this fixed.

**Comment by ayaka14732** [comment]
@mingruimingrui Can you help with this?

**Comment by AntonOfTheWoods** [comment]
Looks like we now have both 3.9 and 3.10, thanks for your help on this @ayaka14732 !
