### ISSUE TITLE
TS

### ISSUE THREAD

**Issue by carmel** [BYVoid/OpenCC#619]
|Traditional| Simplified|
|-- | --|
|於 | 于|
|牠 | 它|
|彀 | 够|
|慇 | 殷|
|繙 | 翻|
|搆 | 构|
|摀 | 捂|
|罣 | 挂|
|榖 | 谷|

**Comment by oscarsun72** [comment]
菩薩慈悲：末學讀《史記三家注》時的劄記也可參考：
https://oscarsun72.blogspot.com/2021/09/blog-post_20.html
感恩感恩　南無阿彌陀佛
