### ISSUE TITLE
皮肤->面板

### ISSUE THREAD

**Issue by Jyunhou** [BYVoid/OpenCC#620]
简体->台湾繁体，皮肤被转换为面板。

查阅汉典网和教育部《重編國語辭典修訂本》，`面板`没有`皮肤`的释义，`皮肤`也没有`面板`的释义，两者可谓毫不相干。两岸的`皮肤`和`面板`分别是同义的。

+ 教育部《重編國語辭典修訂本》
    1. https://dict.revised.moe.edu.tw/dictView.jsp?ID=24697
    1. https://dict.revised.moe.edu.tw/dictView.jsp?ID=31561
+ 汉典网
    1. https://www.zdic.net/hans/皮肤
    1. https://www.zdic.net/hans/面板

两者不应混淆，`皮肤`即是`皮膚`，`面板`即是`面板`。

**Comment by oscarsun72** [comment]
菩薩慈悲：「皮膚」是直譯 skin（以人體喻事物），「面板」是意譯（「面」字也是以人體喻事物）。
目前于傳統中文詞義中是仍未流用通徹者，唯新中國者通之。感恩感恩　南無阿彌陀佛

**Comment by Jyunhou** [comment]
看了下应该是在台湾IT词库里面定义了“皮肤”->“面板”。然而在没有提供多结果转换的现状下，皮肤直接转换为面板是否有不妥？大多数情况下遇到的简体“皮肤”，应是台湾用词之“皮膚”而非“面板”，使用此IT用词在更多情况下是错误转换。我在使用BiliBili繁体版时见过很多次皮肤->面板的转换，基本都是错误的转换，甚至是转换后难以理解。

**Comment by oscarsun72** [comment]
> 看了下应该是在台湾IT词库里面定义了“皮肤”->“面板”。然而在没有提供多结果转换的现状下，皮肤直接转换为面板是否有不妥？大多数情况下遇到的简体“皮肤”，应是台湾用词之“皮膚”而非“面板”，使用此IT用词在更多情况下是错误转换。我在使用BiliBili繁体版时见过很多次皮肤->面板的转换，基本都是错误的转换，甚至是转换后难以理解。

所以說不能只是作字詞的單獨轉換，還得去由上下文、前後文來判斷，這需要大數據作為後台，人工智能AI作為引擎，原理類似翻譯軟體，不是一蹴可幾、等閒可視的。感恩感恩　南無阿彌陀佛

**Comment by tiansh** [comment]
这个规则是因为你用了TWPhrasesIT.txt 这个规则吧？因为有些简体字翻译会把 skin 翻译成皮肤，所以会有问题。如果不是计算机专门的文章，建议不要使用这些规则。我经常下载到小说里面在那写着“物件”“功能表”的，我还得给他翻译回来……

微软的术语表（Microsoft Terminology Collection）里面有这条：

> en: skin
> zh-CN: 外观
> zh-HK: 面板
> zh-TW: 面板
> Definition: A customized user interface that overlays an existing user interface. A skin customizes the look of the program but does not affect its functionality. Programs that allow the use of skins usually make standards available for the creation and distribution of new skins.

**Comment by oscarsun72** [comment]
menu 被譯成「菜單」或「（開始）功能表」的情形也類似。車同軌易，書同文難，愈見AI塗還遠。感恩感恩　南無阿彌陀佛

**Comment by Jyunhou** [comment]
> 这个规则是因为你用了TWPhrasesIT.txt 这个规则吧？因为有些简体字翻译会把 skin 翻译成皮肤，所以会有问题。如果不是计算机专门的文章，建议不要使用这些规则。我经常下载到小说里面在那写着“物件”“功能表”的，我还得给他翻译回来……
> 
> 微软的术语表（Microsoft Terminology Collection）里面有这条：
> 
> > en: skin
> > zh-CN: 外观
> > zh-HK: 面板
> > zh-TW: 面板
> > Definition: A customized user interface that overlays an existing user interface. A skin customizes the look of the program but does not affect its functionality. Programs that allow the use of skins usually make standards available for the creation and distribution of new skins.
> 
> 维基百科的 CGroup/IT 则是
> 
> > en: skin
> > 皮肤=>zh-tw:外觀
> > 皮肤=>zh-hk:佈景主題
> > 皮肤=>zh-mo:佈景主題

我用的是s2twp规则，实际上我希望转换常用台湾词汇，但目前问题在于，一旦转换为台湾词汇，就会把IT术语中的皮肤（面板）也给转换了，但是一般生活中很少出现skin/面板这个词汇，同时info/资讯又非常常见。例如比较日常的词组可能有“皮膚科資訊”，如果不使用TWPhrasesIT,就会转换成“皮膚科信息”，如果使用了就轉換成“面板科資訊”（什么鬼东西？）。总而言之，把 皮肤->面板 这个日常很少见的转换，和 信息->资讯 以及其它常用转换放在一起，就很为难。要么转换出来非常不道地（一定是共谍x），要么一看就是机翻……

**Comment by saeziae** [comment]
[MtF Wiki](https://github.com/mtf-wiki/MtF-Wiki)涉及大量醫學內容，在利用 openCC 生成部分繁體頁面的時候也遇到了非常多的「面板」，屬於是一臉無奈。

**Comment by oscarsun72** [comment]
> [MtF Wiki](https://github.com/mtf-wiki/MtF-Wiki)涉及大量醫學內容，在利用 openCC 生成部分繁體頁面的時候也遇到了非常多的「面板」，屬於是一臉無奈。

這也正即大數據與AI表現身手與能耐的時候了，才知道**人工智慧**與**人的智慧**，差一個字，何啻千里。感恩感恩　南無阿彌陀佛
