### ISSUE TITLE
布灑器？布用填？

### ISSUE THREAD

**Issue by tiansh** [BYVoid/OpenCC#632]
转换规则里面有这两个词，这两个词根本搜不到相关的内容，不知道是哪里错了。

**Comment by sgalal** [comment]
@tiansh 同意，欢迎 Pull Request

**Comment by tiansh** [comment]
@sgalal 如果觉得需要去掉，谁方便直接改掉吧，懒得检出项目再提交就为了删两行文字了 @_@

**Comment by sgalal** [comment]
好，我来修复，感谢反馈
