### ISSUE TITLE
写了个针对 1.1.3 版本对应的iOS pod 库，不知道能否加入到 readme 中

### ISSUE THREAD

**Issue by OHeroJ** [BYVoid/OpenCC#647]
iOSOpenCC： [https://github.com/swiftdo/OpenCC](https://github.com/swiftdo/OpenCC)

**Comment by sgalal** [comment]
歡迎 pr

**Comment by OHeroJ** [comment]
> 歡迎 pr

https://github.com/BYVoid/OpenCC/pull/648
