### ISSUE TITLE
预编译文件无法下载

### ISSUE THREAD

**Issue by xiaoyifang** [BYVoid/OpenCC#655]
https://github.com/BYVoid/OpenCC/wiki/Download#prebuild-%E9%A0%90%E7%B7%A8%E8%AD%AF

![image](https://user-images.githubusercontent.com/105986/153540410-d149c156-d175-41cf-8378-2b682aa1a47e.png)

**Comment by ayaka14732** [comment]
可能太久沒有提交，導致檔案過期了 XD 現在應該可以了

**Comment by longlongvip** [comment]
Now I can't download it again
