### ISSUE TITLE
在已安装cmake的window10下编译失败

### ISSUE THREAD

**Issue by jellyqwq** [BYVoid/OpenCC#659]
$ ./build.cmd

D:\OpenCC>cmake -S. -Bbuild -DCMAKE_INSTALL_PREFIX:PATH=.
-- Building for: NMake Makefiles
CMake Deprecation Warning at CMakeLists.txt:20 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Error at CMakeLists.txt:22 (project):
  Running

   'nmake' '-?'

  failed with:

   系统找不到指定的文件。

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "D:/OpenCC/build/CMakeFiles/CMakeOutput.log".

D:\OpenCC>cmake --build build --config Release --target install
系统找不到指定的文件。
CMake Error: Generator: execution of make failed. Make command was: nmake -f Makefile /nologo install &&

[https://github.com/BYVoid/OpenCC/blob/master/CMakeLists.txt#L19](url)
`######## Project settings
cmake_minimum_required(VERSION 2.8)
set (PACKAGE_NAME opencc)
project (${PACKAGE_NAME} CXX)
include (CTest)`

**Comment by dnasdw** [comment]
看起来是没安装VS。
