### ISSUE TITLE
「剋 」念「kei」时不应该转化为「克」

### ISSUE THREAD

**Issue by tusooa** [BYVoid/OpenCC#661]
「剋 」念「kei」时表示「打，骂」，简化字应不转化为「克」。

例如

https://en.wiktionary.org/wiki/%E5%89%8B#Pronunciation_2 （简化字也是「剋 」）

https://www.zdic.net/hans/%E5%89%8B （有kei读音）
https://www.zdic.net/hant/%E5%85%8B （无kei读音，只有ke）

# downstream
https://github.com/rime/rime-luna-pinyin/issues/41

**Comment by tiansh** [comment]
这字读 kei 的时候几乎没法组词，组词出来也会发现也有读 ke 的时候，感觉很难处理。

**Comment by tusooa** [comment]
> 这字读 kei 的时候几乎没法组词，组词出来也会发现也有读 ke 的时候，感觉很难处理。

是这样子。如果能有读音标注辅助转换，可能会好点儿。别的像干/乾的问题可能也能缓解。

**Comment by tiansh** [comment]
我之前试过整理这几个字的转换规则，最后我发现统一转换成 克 可能好点。毕竟 剋 字用量太小了。而且还是单子成词，根本没法写规则。。。

**Comment by tusooa** [comment]
> 我之前试过整理这几个字的转换规则，最后我发现统一转换成 克 可能好点。毕竟 剋 字用量太小了。而且还是单子成词，根本没法写规则。。。

但是我自己又很喜欢用这个字...

**Comment by tusooa** [comment]
> 我之前试过整理这几个字的转换规则，最后我发现统一转换成 克 可能好点。毕竟 剋 字用量太小了。而且还是单子成词，根本没法写规则。。。

能不能先做成一对多的形式？`剋 -> 克 剋` 「克」作首选，同时保留「剋」的选项

**Comment by sgalal** [comment]
Fixed by #671
