### ISSUE TITLE
[用語轉換] "虛擬機器" 不應被轉換為 "虛擬機器器"

### ISSUE THREAD

**Issue by a0000778** [BYVoid/OpenCC#665]
"虛擬機器" 不應被轉換為 "虛擬機器器"

搭配瀏覽器擴充套件自動轉換的情況下，可能出現 "虛擬機器器器器器器器器...."

轉換設定：
原文=簡中
目標=繁中
異體字轉換=台灣標準
地域用詞轉換=台灣模式

**Comment by oscarsun72** [comment]
菩薩慈悲：這就好像我在做ctext站 [quick edit ](https://ctext.org/library.pl?if=en&file=77458&page=34&editwiki=326338#editor)的文本編輯，判斷[是否要加添「<p>」字串](https://ctext.org/library.pl?if=en&file=78251&page=29&editwiki=385792#editor)一樣。 若在段落末已經綴有「<p>」了，就不添加。想AI也不過如此，多寫幾個 if 判斷吧，只是效能就成了下一個問題爾。
[            #region 標題篇名前段補上分段符號](https://github.com/oscarsun72/TextForCtext/blob/a90519ca2dfecba1fc68611b522b00cb9169805a/WindowsFormsApp1/Form1.cs#L1578)
感恩感恩　南無阿彌陀佛
