### ISSUE TITLE
简体转香港繁体，临「床」转成了臨「牀」，床字转化问题

### ISSUE THREAD

**Issue by woobrain** [BYVoid/OpenCC#678]
有的词语中是需要转化臨牀，但是有的词语中是需要转化臨床，目前发现的规律是临床在单独存在或在最前面时是臨牀

如：中风及临床神经科学理学硕士-->中風及臨床神經科學理學碩士

临床心理学哲学硕士-->臨牀心理學哲學碩士

心理学博士（临床心理学）-->心理學博士（臨牀心理學）

**Comment by ayaka14732** [comment]
統一用「牀」
