### ISSUE TITLE
「口吃」和「口喫」區分

### ISSUE THREAD

**Issue by forFudan** [BYVoid/OpenCC#681]
當前設置 s2t.json 時，「口吃」會轉爲「口喫」，是否應該考慮將此二字區分開來？

原因：此二字原本分工明確，即「喫」表示同進食有關的動作，而「吃」（音ji2）則用來表示「口吃」義。後俗以「吃」代「喫」義，前者完全包含後者。「吃」在大多數時可轉爲「喫」，惟表「口吃」義時（音ji2），不應與「喫」相混。本着 OpenCC 「能分則不合」的原則，故有此提議。

**Comment by ayaka14732** [comment]
OpenCC 是區分兩者的，只是轉換詞典中遺漏了

**Comment by forFudan** [comment]
> OpenCC 是區分兩者的，只是轉換詞典中遺漏了

非常感謝！
