### ISSUE TITLE
Release to deploy new versions to package managers

### ISSUE THREAD

**Issue by AntonOfTheWoods** [BYVoid/OpenCC#689]
Python 3.10 support has been available for 6 months now but is still not available on PyPI as no release has been made.

Could you please cut a release?

cc. @BYVoid @sgalal @ayaka14732

**Comment by ayaka14732** [comment]
Sorry that I don't know how to make a release in the OpenCC repository. If you don't need to consider the performance, you can use the new StarCC, which is compatible with OpenCC but not optimised for performance yet.

**Comment by AntonOfTheWoods** [comment]
Thanks for your reply @ayaka14732 . I have created https://github.com/BYVoid/OpenCC/pull/692 that should do the code update part. I don't know how releases are done after that, maybe via a tag or something that gets picked up automatically?

**Comment by AntonOfTheWoods** [comment]
After initial testing, the update seems to work perfectly. Thanks @ayaka14732 !
