### ISSUE TITLE
閤 不应该转换为 合

### ISSUE THREAD

**Issue by duSupport** [BYVoid/OpenCC#702]
閤在作为姓氏（xia 2）时应该是简体”门“字里面一个”合“，新华2020发行的第12版新华字典中 閤 字的简体也已经变为 简体”门“字里面一个合字了。

**Comment by groverlynn** [comment]
#735 
參考https://dict.revised.moe.edu.tw/dictView.jsp?ID=3953&la=0&powerMode=0
沒有找到你說的作姓氏簡化為𬮤的依據

**Comment by duSupport** [comment]
閤姓很罕见，全国閤姓的人也就几千个人，我知道你找不到出处，但是他们自己用普通话的确是读（xia 2）同霞音。能不能不要简化为合，毕竟新华字典也没将它简化为合了。简化为合后，閤姓的人根本没法打出自己的姓名。另外，閤姓的有相当一大部分居住在湖北省随州市随县府河镇。如果有机会的话，可以找相关人实地求证。

> #735 參考https://dict.revised.moe.edu.tw/dictView.jsp?ID=3953&la=0&powerMode=0 沒有找到你說的作姓氏簡化為𬮤的依據

**Comment by duSupport** [comment]
![Screenshot_20221203_152650](https://user-images.githubusercontent.com/9265494/205430168-45418393-6b8e-44b9-bce9-88d2ec88fdc6.jpg)

**Comment by HaaiSo** [comment]
http://data.library.sh.cn/jp/resource/work/xrq2td2w8ulvkntm
上为依据《中华閤氏族谱》之简要介绍，确是聚居在湖北随州。虽然链接中写的是「合氏」，但实为机器简化之误，在孔网搜索可得：
https://book.kongfz.com/682960/6260545456
这里可以看到族谱上其实是「閤氏」。孔夫子旧书网搜索「閤氏」共有2个族谱在售，卖家均在湖北。
> #735 參考https://dict.revised.moe.edu.tw/dictView.jsp?ID=3953&la=0&powerMode=0 沒有找到你說的作姓氏簡化為𬮤的依據

**Comment by HaaiSo** [comment]
![screencapture-linkedin-pub-dir-2024-05-15-20_35_04](https://github.com/BYVoid/OpenCC/assets/8848342/3253ce48-63e9-4034-8c27-2123d15c0763)
在领英搜索「閤」，也可以看到很多姓閤的人，这个姓氏确实是存在的。

**Comment by HaaiSo** [comment]
https://www.xiaohongshu.com/explore/61398a61000000002103b9dd
閤作为姓氏读作xia的实证一例

**Comment by HaaiSo** [comment]
https://news.sina.com.cn/s/2008-04-23/082613780619s.shtml
閤作为姓氏读作xia的例证之二
