### ISSUE TITLE
未來是否支持韓國漢字的轉換？

### ISSUE THREAD

**Issue by Hotege** [BYVoid/OpenCC#709]
例如韓國圍棋棋手尹潣重（來源於https://godb.shogidb2.com/en/game/players/%E5%B0%B9%E6%BD%A3%E9%87%8D ），他的名字中的潣沒有對應的中文字，目前翻繁體中文譯作尹閔重（尹闵重，來源于https://goratings.org）。
使用OpenCC的convert將會導致Exception。

**Comment by Hotege** [comment]
我錯了，Exception並不是在convert上

**Comment by BYVoid** [comment]
你好，所謂的Exception是什麼錯誤？

目前尚未有韓國漢字到簡化字的數據。
