### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ChiaYuSu** [BYVoid/OpenCC#710]
I'm having problems with `FileNotFoundError` in my environment, and I'm using Python version number `3.10.6`.

Error code.
`FileNotFoundError: Could not find module 'C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\opencc\clib\bin\opencc.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

**Comment by Yaekiou** [comment]
我之前也遇到了這個問題，如果你的電腦上沒有安裝 https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 或許可以試一試

**Comment by ChiaYuSu** [comment]
> 我之前也遇到了這個問題，如果你的電腦上沒有安裝 https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 或許可以試一試

This works successfully in my environment. Thank you very much.

Note, my enviromnent:
- Windows 11 ARM
- Python version 3.10.6
