### ISSUE TITLE
Convert OpenCC into R package

### ISSUE THREAD

**Issue by turbanisch** [BYVoid/OpenCC#717]
I was wondering whether there already exists an R package to access OpenCC programmatically or whether there are plans to develop one. Probably porting the existing C or Python versions to R is not that much work but I thought I'd rather ask before I try to contribute myself.

**Comment by ayaka14732** [comment]
I searched on Google and found this: https://github.com/Lchiffon/ropencc

**Comment by turbanisch** [comment]
Ah shoot, it's not that I did not search on Google but somehow I missed this entirely. Very much appreciated!
