### ISSUE TITLE
make: *** [all] Error 2

### ISSUE THREAD

**Issue by Jorigorn** [BYVoid/OpenCC#72]
[root@centos-server OpenCC]# make
[  2%] Building CXX object src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o
In file included from /root/workspace/OpenCC/src/Common.hpp:37,
                 from /root/workspace/OpenCC/src/BinaryDict.hpp:21,
                 from /root/workspace/OpenCC/src/BinaryDict.cpp:19:
/root/workspace/OpenCC/src/Exception.hpp:45: error: expected ‘;’ before ‘noexcep                                                                                        t’
/root/workspace/OpenCC/src/Exception.hpp:49: error: expected ‘;’ before ‘protect                                                                                        ed’
In file included from /root/workspace/OpenCC/src/Common.hpp:39,
                 from /root/workspace/OpenCC/src/BinaryDict.hpp:21,
                 from /root/workspace/OpenCC/src/BinaryDict.cpp:19:
/root/workspace/OpenCC/src/Optional.hpp: In constructor ‘opencc::Optional<T*>::O                                                                                        ptional()’:
/root/workspace/OpenCC/src/Optional.hpp:72: error: ‘nullptr’ was not declared in                                                                                         this scope
/root/workspace/OpenCC/src/Optional.hpp: In member function ‘bool opencc::Option                                                                                        al<T*>::IsNull() const’:
/root/workspace/OpenCC/src/Optional.hpp:83: error: ‘nullptr’ was not declared in                                                                                         this scope
In file included from /root/workspace/OpenCC/src/DictEntry.hpp:22,
                 from /root/workspace/OpenCC/src/Dict.hpp:22,
                 from /root/workspace/OpenCC/src/SerializableDict.hpp:21,
                 from /root/workspace/OpenCC/src/BinaryDict.hpp:22,
                 from /root/workspace/OpenCC/src/BinaryDict.cpp:19:
/root/workspace/OpenCC/src/UTF8Util.hpp: In static member function ‘static std::                                                                                        string opencc::UTF8Util::Join(const std::vector<std::basic_string<char, std::cha                                                                                        r_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, s                                                                                        td::char_traits<char>, std::allocator<char> > > >&, const std::string&)’:
/root/workspace/OpenCC/src/UTF8Util.hpp:181: error: expected initializer before                                                                                         ‘:’ token
/root/workspace/OpenCC/src/UTF8Util.hpp:189: error: expected primary-expression                                                                                         at end of input
/root/workspace/OpenCC/src/UTF8Util.hpp:189: error: expected ‘;’ at end of input
/root/workspace/OpenCC/src/UTF8Util.hpp:189: error: expected primary-expression                                                                                         at end of input
/root/workspace/OpenCC/src/UTF8Util.hpp:189: error: expected ‘)’ at end of input
/root/workspace/OpenCC/src/UTF8Util.hpp:189: error: expected statement at end of                                                                                         input
/root/workspace/OpenCC/src/UTF8Util.hpp:180: warning: unused variable ‘first’
/root/workspace/OpenCC/src/UTF8Util.hpp:189: error: expected ‘}’ at end of input
/root/workspace/OpenCC/src/UTF8Util.hpp:189: warning: no return statement in fun                                                                                        ction returning non-void
/root/workspace/OpenCC/src/UTF8Util.hpp: In static member function ‘static std::                                                                                        string opencc::UTF8Util::Join(const std::vector<std::basic_string<char, std::cha                                                                                        r_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, s                                                                                        td::char_traits<char>, std::allocator<char> > > >&)’:
/root/workspace/OpenCC/src/UTF8Util.hpp:196: error: expected initializer before                                                                                         ‘:’ token
/root/workspace/OpenCC/src/UTF8Util.hpp:199: error: expected primary-expression                                                                                         before ‘return’
/root/workspace/OpenCC/src/UTF8Util.hpp:199: error: expected ‘;’ before ‘return’
/root/workspace/OpenCC/src/UTF8Util.hpp:199: error: expected primary-expression                                                                                         before ‘return’
/root/workspace/OpenCC/src/UTF8Util.hpp:199: error: expected ‘)’ before ‘return’
In file included from /root/workspace/OpenCC/src/DictEntry.hpp:23,
                 from /root/workspace/OpenCC/src/Dict.hpp:22,
                 from /root/workspace/OpenCC/src/SerializableDict.hpp:21,
                 from /root/workspace/OpenCC/src/BinaryDict.hpp:22,
                 from /root/workspace/OpenCC/src/BinaryDict.cpp:19:
/root/workspace/OpenCC/src/Segments.hpp: In constructor ‘opencc::Segments::Segme                                                                                        nts(std::initializer_list<const char*>)’:
/root/workspace/OpenCC/src/Segments.hpp:34: error: expected initializer before ‘                                                                                        :’ token
/root/workspace/OpenCC/src/Segments.hpp:37: error: expected primary-expression b                                                                                        efore ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:37: error: expected ‘;’ before ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:37: error: expected primary-expression b                                                                                        efore ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:37: error: expected ‘)’ before ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:37: error: expected primary-expression b                                                                                        efore ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:37: error: expected ‘;’ before ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp: In constructor ‘opencc::Segments::Segme                                                                                        nts(std::initializer_list<std::basic_string<char, std::char_traits<char>, std::a                                                                                        llocator<char> > >)’:
/root/workspace/OpenCC/src/Segments.hpp:40: error: expected initializer before ‘                                                                                        :’ token
/root/workspace/OpenCC/src/Segments.hpp:43: error: expected primary-expression b                                                                                        efore ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:43: error: expected ‘;’ before ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:43: error: expected primary-expression b                                                                                        efore ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:43: error: expected ‘)’ before ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:43: error: expected primary-expression b                                                                                        efore ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp:43: error: expected ‘;’ before ‘}’ token
/root/workspace/OpenCC/src/Segments.hpp: In member function ‘std::string opencc:                                                                                        :Segments::ToString() const’:
/root/workspace/OpenCC/src/Segments.hpp:119: error: expected initializer before                                                                                         ‘:’ token
/root/workspace/OpenCC/src/Segments.hpp:122: error: expected primary-expression                                                                                         before ‘return’
/root/workspace/OpenCC/src/Segments.hpp:122: error: expected ‘;’ before ‘return’
/root/workspace/OpenCC/src/Segments.hpp:122: error: expected primary-expression                                                                                         before ‘return’
/root/workspace/OpenCC/src/Segments.hpp:122: error: expected ‘)’ before ‘return’
In file included from /root/workspace/OpenCC/src/Dict.hpp:22,
                 from /root/workspace/OpenCC/src/SerializableDict.hpp:21,
                 from /root/workspace/OpenCC/src/BinaryDict.hpp:22,
                 from /root/workspace/OpenCC/src/BinaryDict.cpp:19:
/root/workspace/OpenCC/src/DictEntry.hpp: In constructor ‘opencc::StrMultiValueD                                                                                        ictEntry::StrMultiValueDictEntry(const std::string&, const std::vector<const cha                                                                                        r*, std::allocator<const char*> >&)’:
/root/workspace/OpenCC/src/DictEntry.hpp:151: error: expected initializer before                                                                                         ‘:’ token
/root/workspace/OpenCC/src/DictEntry.hpp:154: error: expected primary-expression                                                                                         before ‘}’ token
/root/workspace/OpenCC/src/DictEntry.hpp:154: error: expected ‘;’ before ‘}’ tok                                                                                        en
/root/workspace/OpenCC/src/DictEntry.hpp:154: error: expected primary-expression                                                                                         before ‘}’ token
/root/workspace/OpenCC/src/DictEntry.hpp:154: error: expected ‘)’ before ‘}’ tok                                                                                        en
/root/workspace/OpenCC/src/DictEntry.hpp:154: error: expected primary-expression                                                                                         before ‘}’ token
/root/workspace/OpenCC/src/DictEntry.hpp:154: error: expected ‘;’ before ‘}’ tok                                                                                        en
/root/workspace/OpenCC/src/DictEntry.hpp: In member function ‘virtual std::vecto                                                                                        r<const char*, std::allocator<const char*> > opencc::StrMultiValueDictEntry::Val                                                                                        ues() const’:
/root/workspace/OpenCC/src/DictEntry.hpp:169: error: expected initializer before                                                                                         ‘:’ token
/root/workspace/OpenCC/src/DictEntry.hpp:172: error: expected primary-expression                                                                                         before ‘return’
/root/workspace/OpenCC/src/DictEntry.hpp:172: error: expected ‘;’ before ‘return                                                                                        ’
/root/workspace/OpenCC/src/DictEntry.hpp:172: error: expected primary-expression                                                                                         before ‘return’
/root/workspace/OpenCC/src/DictEntry.hpp:172: error: expected ‘)’ before ‘return                                                                                        ’
In file included from /root/workspace/OpenCC/src/BinaryDict.cpp:20:
/root/workspace/OpenCC/src/Lexicon.hpp: In destructor ‘opencc::Lexicon::~Lexicon                                                                                        ()’:
/root/workspace/OpenCC/src/Lexicon.hpp:35: error: expected initializer before ‘:                                                                                        ’ token
/root/workspace/OpenCC/src/Lexicon.hpp:38: error: expected primary-expression be                                                                                        fore ‘}’ token
/root/workspace/OpenCC/src/Lexicon.hpp:38: error: expected ‘;’ before ‘}’ token
/root/workspace/OpenCC/src/Lexicon.hpp:38: error: expected primary-expression be                                                                                        fore ‘}’ token
/root/workspace/OpenCC/src/Lexicon.hpp:38: error: expected ‘)’ before ‘}’ token
/root/workspace/OpenCC/src/Lexicon.hpp:38: error: expected primary-expression be                                                                                        fore ‘}’ token
/root/workspace/OpenCC/src/Lexicon.hpp:38: error: expected ‘;’ before ‘}’ token
/root/workspace/OpenCC/src/BinaryDict.cpp: In member function ‘size_t opencc::Bi                                                                                        naryDict::KeyMaxLength() const’:
/root/workspace/OpenCC/src/BinaryDict.cpp:26: error: expected initializer before                                                                                         ‘:’ token
/root/workspace/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression                                                                                         before ‘return’
/root/workspace/OpenCC/src/BinaryDict.cpp:29: error: expected ‘;’ before ‘return                                                                                        ’
/root/workspace/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression                                                                                         before ‘return’
/root/workspace/OpenCC/src/BinaryDict.cpp:29: error: expected ‘)’ before ‘return                                                                                        ’
/root/workspace/OpenCC/src/BinaryDict.cpp: In member function ‘virtual void open                                                                                        cc::BinaryDict::SerializeToFile(FILE_) const’:
/root/workspace/OpenCC/src/BinaryDict.cpp:49: error: expected initializer before                                                                                         ‘:’ token
/root/workspace/OpenCC/src/BinaryDict.cpp:181: error: expected primary-expressio                                                                                        n at end of input
/root/workspace/OpenCC/src/BinaryDict.cpp:181: error: expected ‘;’ at end of inp                                                                                        ut
/root/workspace/OpenCC/src/BinaryDict.cpp:181: error: expected primary-expressio                                                                                        n at end of input
/root/workspace/OpenCC/src/BinaryDict.cpp:181: error: expected ‘)’ at end of inp                                                                                        ut
/root/workspace/OpenCC/src/BinaryDict.cpp:181: error: expected statement at end                                                                                         of input
/root/workspace/OpenCC/src/BinaryDict.cpp:48: warning: unused variable ‘keyCurso                                                                                        r’
/root/workspace/OpenCC/src/BinaryDict.cpp:48: warning: unused variable ‘valueCur                                                                                        sor’
/root/workspace/OpenCC/src/BinaryDict.cpp:181: error: expected ‘}’ at end of inp                                                                                        ut
make[2]: *_\* [src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/libopencc.dir/all] Error 2
make: **\* [all] Error 2
[root@centos-server OpenCC]#

**Comment by Jayenovn** [comment]
我的gcc版本已经升级到5.2.0，还是报相同的错误。
运行
cd build/rel
make clean
make VERBOSE=1
输出结果是
make[2]: *** [src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o] 错误 1
make[2]: Leaving directory `/usr/local/OpenCC/build/rel'
make[1]: *** [src/CMakeFiles/libopencc.dir/all] 错误 2
make[1]: Leaving directory `/usr/local/OpenCC/build/rel'
make: *** [all] 错误  
@BYVoid
