### ISSUE TITLE
"輸入輸出文件是同一個文件"作爲一種例外情況沒有得到處理

### ISSUE THREAD

**Issue by xieyuheng** [BYVoid/OpenCC#74]

**Comment by Quotation** [comment]
我也有同样疑问，`opencc -i abc.txt -o abc.txt`执行后，abc.txt变为空文件。希望在这种情况下，能直接覆盖输入文件。

**Comment by jakwings** [comment]
Windows: `opencc -i abc.txt | mtee abc.txt > NUL`

Linux: `(opencc -i abc.txt | tee abc.txt) > /dev/null`

**Comment by xieyuheng** [comment]
可能我所說的問題  並不是程序本身用戶接口的嚴重問題  而沒有改進的必要

**Comment by BYVoid** [comment]
已經實現，但是只會檢查`-i`與`-o`字面上是否一樣，並沒有解析絕對路徑、符號鏈接。 https://github.com/BYVoid/OpenCC/commit/d4007e341b6777b0a5a1d0dbd5707b0da99896f3
