### ISSUE TITLE
關於纔和才

### ISSUE THREAD

**Issue by garyyeap** [BYVoid/OpenCC#756]
看了 #369 這個 PR，看來是有意爲之的把「剛才」「才行」之類的換成「纔」？
但老實說，身爲繁體中文的長期使用者我幾乎沒看過人這樣用的，對我來說其實也困擾常常要手動轉換？

隨便找一些例子：

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/798943/209127449-baaf5416-9327-4219-974b-11fb19497596.png">

<img width="934" alt="image" src="https://user-images.githubusercontent.com/798943/209127531-c80a554a-e85e-4b7d-b30f-cd2437ccfdb8.png">

基本上都是用「才」，除了那些簡繁自動翻譯出來的外幾乎沒看過有人用，請問這樣轉換的依據是？

**Comment by ayaka14732** [comment]
README 中講得不清楚，需要使用香港模式（s2hk）或台灣模式（s2tw）

**Comment by garyyeap** [comment]
所以是開發者在使用中時用了不適合的設定？

**Comment by ayaka14732** [comment]
對，在使用時，應該根據情況選用香港模式（s2hk）或台灣模式（s2tw）

**Comment by groverlynn** [comment]
> 所以是開發者在使用中時用了不適合的設定？

@garyyeap 並不是。「纔」是正字。元．關漢卿《竇娥冤》第四折：「至十七歲與夫配合，纔得兩年，不幸兒夫亡化。」
然而現代漢字圈已經幾乎全部用俗字「才」取代正字「纔」，實際上造成了一俗（「才」）對多正（「才」、「纔」）。`t`是兼容所有繁體的，所以需要收錄罕見的「纔」。如果想要台標（或港標）的繁體，就選`s2tw`（或`s2hk`），不要選`s2t`。

**Comment by oscarsun72** [comment]
可以參考　賢超法師大德如何實作自動標點的，對於上下文語意的判斷，確實如其AI之名。鄙人中文博士畢業、曾是兼任助理教授，自認　他這古文文言自動標點能力，不再我之下，多在我之上。想繁簡轉換亦多須藉由文字所在情境脈絡來判斷者也。。。。感恩感恩　讚歎讚歎　南無阿彌陀佛
