### ISSUE TITLE
OpenCC收表外字嗎

### ISSUE THREAD

**Issue by ywxt** [BYVoid/OpenCC#762]
未出現在「通規」表中，而是由民間類推簡化的字，在OpenCC在的範圍內嗎？

**Comment by ywxt** [comment]
整理碼表時發現收字不全，如果可以，我會提個PR，大概有100多個。

**Comment by danny0838** [comment]
目前應該是不收的。我之前有建議增加類推簡化的方案，但目前還無相關共識，參 https://github.com/BYVoid/OpenCC/issues/217#issuecomment-650021879

**Comment by ywxt** [comment]
多謝回覆，既然如此，那我就先關閉issue了
