### ISSUE TITLE
请问我想在 php java 语言中使用，应该如何操作？

### ISSUE THREAD

**Issue by hiscaler** [BYVoid/OpenCC#77]
请问我想在 php java 语言中使用，应该如何操作？
php 的话编译成dll 扩展并启用就可以了？
java 的呢？编译成 jar?
不太明白，请指教一下，多谢。

**Comment by yutong1984** [comment]
php中可以使用opencc-php扩展，java可以调用php的http接口，如果是单服务器可以直接使用jopencc都是不错的选择
