### ISSUE TITLE
t2s not found or not accessible.

### ISSUE THREAD

**Issue by jack6th** [BYVoid/OpenCC#781]
mingw32 opencc 1.1.6 on Windows
```
opencc -i a.txt -c t2s
t2s not found or not accessible.
```
opencc cannot find the t2s.json unless I specify an absolute path of t2s.json. 
In tesseract there is an environment variable TESSDATA_PREFIX which can solve the issue like this.
Please add an environment variable OPENCCDATA_PREFIX which allow the user to specify the configure json files path.

**Comment by BYVoid** [comment]
in the next version, you will be able to specify `--path` explicitly.
