### ISSUE TITLE
centos7与ubuntu16系统 opencc源码编译时遇到bug

### ISSUE THREAD

**Issue by suyanhj** [BYVoid/OpenCC#787]
问题1：在源码编译opencc时，默认cmakefile中指定的cmake版本是3.5，编译时实际上会遇到找不到依赖包的问题，如图：
![image](https://github.com/BYVoid/OpenCC/assets/95021771/2c48011d-feab-493a-9ecf-44d79b91cdde)
![image](https://github.com/nauxliu/opencc4php/assets/95021771/79091f67-a16a-4e32-8456-c9d469916844)
解决： 需要手动下载一份最新的cmake，我用3.26版本就能正常编译

问题2：如果编译时遇到 c++14报错的问题，也需要改cmakefile，指定c++版本
解决：
g++ -std=c++11 -E - < /dev/null           // 可检查本地gcc支持哪个版本的c++，可以试试c++11，都是向下兼容
sed -ri-bak 's#(.*-std=)c++14$#\1c++11#' CMakeLists.txt           // 非交互式修改配置文件

**Comment by luoben4040** [comment]
我也遇到这个问题。
g++ -std=c++11 -E - < /dev/null ：
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "<stdin>"

我把OpenCC目录里的CMakeLists.txt修改：两处c++14修改为c++11，执行make还是如你的图2报错。

请问这个该怎么解决呢？

**Comment by suyanhj** [comment]
> 我也遇到这个问题。 `g++ -std=c++11 -E - < /dev/null ： cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default] 我把OpenCC目录里的CMakeLists.txt修改：两处c++14修改为c++11，执行make还是如你的图2报错。 请问这个该怎么解决呢？

gcc、cmake啥版本，什么系统来着的

**Comment by luoben4040** [comment]
> > 我也遇到这个问题。 `g++ -std=c++11 -E - < /dev/null ： cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default] 我把OpenCC目录里的CMakeLists.txt修改：两处c++14修改为c++11，执行make还是如你的图2报错。 请问这个该怎么解决呢？
> 
> gcc、cmake啥版本，什么系统来着的
CentOS 7.9.2009 x86_64(Py3.7.9)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
cmake version 3.7.2

**Comment by suyanhj** [comment]
> > gcc、cmake啥版本，什么系统来着的
> > CentOS 7.9.2009 x86_64(Py3.7.9)
> > gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
> > cmake version 3.7.2

可以参考我的这个博客来，图一和图二都是cmake版本不够，最低3.10版本，c++报错当时没截图，所以提交issue的时候是分开写的
https://www.cnblogs.com/suyanhj/articles/17460147.html

**Comment by luoben4040** [comment]
> > > gcc、cmake啥版本，什么系统来着的
> > > CentOS 7.9.2009 x86_64(Py3.7.9)
> > > gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
> > > cmake version 3.7.2
> 
> 可以参考我的这个博客来，图一和图二都是cmake版本不够，最低3.10版本，c++报错当时没截图，所以提交issue的时候是分开写的 https://www.cnblogs.com/suyanhj/articles/17460147.html
>

谢谢。重新编译了cmake，现在安装成功了。
非常感谢。
