### ISSUE TITLE
转换错误

### ISSUE THREAD

**Issue by CjangCjengh** [BYVoid/OpenCC#801]
「她的散发散发着清香」转换后为「她的散發散發着清香」
应为「她的散髮」

**Comment by Dropless-arch** [comment]
opencc 支持词汇级别的转换, 这种依赖语境的应该做不到?
「她的散发散发着清香」
「她的散发清香的散发」
这两句句首 "她的散发" 中的散发分别是 "散髮" 与 "散發", 要靠语境才能分辨.
