### ISSUE TITLE
是否可以直接编辑*.ocd2文件

### ISSUE THREAD

**Issue by yangzhongke** [BYVoid/OpenCC#803]
我们的项目中有一些自定义的词汇要加入ocd2，因为属于组织内部的专用词汇，不方便直接PR提交到这里合并，是否有工具可以编辑ocd2文件，还是只能下载全部代码，然后手动编辑STPhrases.txt之类的文件然后重新编译才可以？
谢谢

**Comment by vvsolo** [comment]
自定义一个 TSCustom.txt，然后生成 ocd2 文件：
`opencc_dict.exe -i TSCustom.txt -o TSCustom.ocd2 -f text -t ocd2`

编辑 JSON 文件，按格式在最后加上自定义包就可以了
这样也有助于后期升级。
