### ISSUE TITLE
繁简字转化是否应以《现代汉语词典》为标准

### ISSUE THREAD

**Issue by muler-hussel** [BYVoid/OpenCC#818]
一般来说，大陆的繁简字转化，官方规定以《通用规范汉字表》和《现代汉语词典》（第七版）为准。我查看了[STCharacters.txt](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/STCharacters.txt)和[TSCharacters.txt](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TSCharacters.txt)，如STC中第一项㐷→傌，根据《现代汉语词典》，未收录“㐷”，而“傌”只作为“骂”的异体字出现，则理论上来说，“㐷”不能转化为“傌”。（异体字也是不推荐使用的，因此“骂”也不能转化为“傌”）；STC中还有说→說，根据标准，“說”是旧字形，现在应转化为“説”，相关标准同样可见于《现代汉语词典》。
TSC中㑮→𫝈，“㑮”字《现代汉语词典》中未收录，则不应进行类推简化。

**Comment by danny0838** [comment]
個人覺得可以分成含類推簡化與不含類推簡化的轉換方案。 https://github.com/BYVoid/OpenCC/issues/217#issuecomment-650021879 有談過類似問題。

**Comment by groverlynn** [comment]
你相當於在問「正月初一是否應該全人類都吃水餃」。

**Comment by LaoshuBaby** [comment]
转换应以目标地区的用词用词习惯和规范为准而非来源为准吧？转换为港台繁体的时候自然要按照港台的习惯，除非你要的是“大陆繁体”这种极为特殊的场景

**Comment by BYVoid** [comment]
OpenCC並未完全遵照《现代汉语词典》標準。如果有興趣，你可以提供一個次標準的對照表。
