### ISSUE TITLE
兼容macos新版系统，建议修改Makefile文件

### ISSUE THREAD

**Issue by odinxu** [BYVoid/OpenCC#829]
建议修改Makefile文件
PREFIX = /usr
修改为
PREFIX = /usr/local

以兼容macos新版系统，就算是用sudo也禁止写文件到 /usr/bin/ ,  /usr/share/ , /usr/lib/   这些目录。

**Comment by groverlynn** [comment]
/usr is for linux, not for unix/macOS or win
plz refer to the cmake file for real paths
