### ISSUE TITLE
Windows CLI，被转换的文本文件编码为GB18030时，--output 无效

### ISSUE THREAD

**Issue by ZSkycat** [BYVoid/OpenCC#850]
当被转换的文本文件编码为UTF-8时，工作正常。
当被转换的文本文件编码为GB18030时，--output 无效，输出成空文件，且结果输出到控制台。
当被转换的文本文件编码为UTF-16 LE时，工作异常，报错或输出不正确的内容。

另外 wiki 的 ｢Prebuild 預編譯｣ 下载已失效。
https://github.com/BYVoid/OpenCC/wiki/Download#download-%E4%B8%8B%E8%BC%89

**Comment by BYVoid** [comment]
僅支持UTF-8。
