### ISSUE TITLE
`字节跳动`(大陆简体) 错误转换为 `位元組跳動`(台湾繁体)

### ISSUE THREAD

**Issue by LaoshuBaby** [BYVoid/OpenCC#864]
源字符串：`字节跳动`
期待的目标字符串：`字節跳動`
实际得到的结果：`位元組跳動`

截屏：
![Open位元組跳動CC](https://github.com/BYVoid/OpenCC/assets/42690037/ab3028ad-8368-4997-adce-0cd9255f6f99)

参考：
![zh-Hant-TW-wikipedia](https://github.com/BYVoid/OpenCC/assets/42690037/d6fbeeab-5e87-44f5-911e-3dd9481222c9)

---

其他信息技术企业名称因包含了专有名词而被误转换的：

* #865 (摩尔线程)

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/commit/8ef6b5ee497c399e028f2fa79fd5fad2cad1869a
