### ISSUE TITLE
`摩尔线程`(大陆简体) 错误转换为 `摩爾執行緒`(台湾繁体)

### ISSUE THREAD

**Issue by LaoshuBaby** [BYVoid/OpenCC#865]
源字符串：`摩尔线程`
期待的目标字符串：`摩爾綫程`
实际得到的结果：`摩爾執行緒`

截图：

![科技名词果然很容易撞车](https://github.com/BYVoid/OpenCC/assets/42690037/f7b80c08-6bcd-427e-a447-0e0b5de1d8bd)

参考：

![看来不止OpenCC会犯这个错](https://github.com/BYVoid/OpenCC/assets/42690037/0c00b2b1-3017-4c22-a048-85833b53e902)
在中文维基百科亦有[提报](https://zh.wikipedia.org/w/index.php?title=Wikipedia:%E5%AD%97%E8%AF%8D%E8%BD%AC%E6%8D%A2/%E4%BF%AE%E5%A4%8D%E8%AF%B7%E6%B1%82&diff=prev&oldid=77757958#-{%E6%91%A9%E7%88%BE%E5%9F%B7%E8%A1%8C%E7%B7%92}-)过这一错误的自动转换

---

其他信息技术企业名称因包含了专有名词而被误转换的：

* #864 (字节跳动)

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/commit/8ef6b5ee497c399e028f2fa79fd5fad2cad1869a
