### ISSUE TITLE
GLIBCXX_3.4.29

### ISSUE THREAD

**Issue by yuanjie-ai** [BYVoid/OpenCC#866]
"message": "/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /www/server/pyporject_evn/versions/3.10.0/lib/python3.10/site-packages/opencc/clib/opencc_clib.cpython-310-x86_64-linux-gnu.so)",

**Comment by jeff-getlucky** [comment]
Same error, please use 1.1.6
