### ISSUE TITLE
未收錄的兩岸異譯化學元素

### ISSUE THREAD

**Issue by 910JQK** [BYVoid/OpenCC#87]
鑀 锿
鉳 锫
砈 砹
鍅 钫
鎦 镥
鋂 镅
錼 镎
鎝 锝

**Comment by 910JQK** [comment]
參考：
http://ptable.com/
http://tieba.baidu.com/p/2586394220

**Comment by BYVoid** [comment]
感謝，已經在繁簡轉換和臺灣異體字轉換中添加了。注意默認簡繁轉換並不轉換這些字，因爲這些字都有對應的同形繁體。

c24292f4e742b983cf136149c88d48683e702d56
