### ISSUE TITLE
香港繁体转简体，[尼乾子]转换为了[尼干子]

### ISSUE THREAD

**Issue by poweryu** [BYVoid/OpenCC#870]
模式：香港繁体转简体
源字符串：尼乾子
目前转换结果：尼干子
预期转换结果：尼乾子
说明：在佛经中，“尼乾子”是尼乾陀．若提子的信徒，目前“尼乾陀．若提子”可以正常转换，“尼乾子”转换异常，请补充到词库中。

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/commit/8003092cbb2ac82b36a97a6c8bff154d230aa156

**Comment by poweryu** [comment]
@BYVoid 谢谢
