### ISSUE TITLE
ABI breaking changes in patch release

### ISSUE THREAD

**Issue by ziyao233** [BYVoid/OpenCC#885]
In commit 562ff89 ("Introduce 'argv0' parameter to SimpleConverter, and fix Bazel bundled paths of runfiles.") and a89faa7 ("Support additional lookup paths in the opencc command line converter. "), prototype change of method `Config::NewFromFile()` breaks the ABI. This causes errors like

```
2024-08-02 19:12:11.688379 addonloader.cpp:38] Failed to load library for addon rime on /usr/lib/fcitx5/librime.so. Error: /usr/lib/librime.so.1: undefined symbol: _ZN6opencc6Config11NewFromFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
I2024-08-02 19:12:11.688409 addonmanager.cpp:201] Could not load addon rime
```

when running programs dynamically linked with previous version of OpenCC.

As OpenCC supports to be built as shared library, we should always keep the ABI stable between minor and patch releases. Introducing a reloaded version `Config::NewFromFile()` should be a better solution.

**Comment by BYVoid** [comment]
The changed ABI is added back. https://github.com/BYVoid/OpenCC/commit/556ed22496d650bd0b13b6c163be9814637970ae

Please wait and use the next version. I will soon release v.1.1.9.

**Comment by ziyao233** [comment]
thanks for your work!

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/releases/tag/ver.1.1.9
