### ISSUE TITLE
簡正轉換別字表

### ISSUE THREAD

**Issue by LNDDYL** [BYVoid/OpenCC#93]
http://founder.acgvlyric.org/iu/doku.php/w:%E7%B0%A1%E6%AD%A3%E8%BD%89%E6%8F%9B%E5%88%A5%E5%AD%97%E8%A1%A8

**Comment by LNDDYL** [comment]
「张三丰」是「張三丰」，而不是「張三豐」。

**Comment by BYVoid** [comment]
OpenCC 1.0.2 轉換「张三丰」是「張三丰」。

**Comment by LNDDYL** [comment]
「北美发行」變「北美髮行」，「南美发行」變「南美髮行」。

**Comment by LNDDYL** [comment]
我在臉書上給您留言了。

**Comment by LNDDYL** [comment]
http://bbs.zdic.net/thread-144015-1-1.html
