### ISSUE TITLE
can not make on centos 6

### ISSUE THREAD

**Issue by davyzhang** [BYVoid/OpenCC#94]
$ make
[  2%] Building CXX object src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/Common.hpp:42,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.hpp:21,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:19:
/home/zhangdavy/Documents/lib/OpenCC/src/Exception.hpp:43: error: expected ‘;’ before ‘noexcept’
/home/zhangdavy/Documents/lib/OpenCC/src/Exception.hpp:45: error: expected ‘;’ before ‘protected’
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/Common.hpp:44,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.hpp:21,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:19:
/home/zhangdavy/Documents/lib/OpenCC/src/Optional.hpp: In constructor ‘opencc::Optional<T*>::Optional()’:
/home/zhangdavy/Documents/lib/OpenCC/src/Optional.hpp:62: error: ‘nullptr’ was not declared in this scope
/home/zhangdavy/Documents/lib/OpenCC/src/Optional.hpp: In member function ‘bool opencc::Optional<T*>::IsNull() const’:
/home/zhangdavy/Documents/lib/OpenCC/src/Optional.hpp:70: error: ‘nullptr’ was not declared in this scope
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:22,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/Dict.hpp:22,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/SerializableDict.hpp:21,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.hpp:22,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:19:
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp: In static member function ‘static std::string opencc::UTF8Util::Join(const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, const std::string&)’:
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:195: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:203: error: expected primary-expression at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:203: error: expected ‘;’ at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:203: error: expected primary-expression at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:203: error: expected ‘)’ at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:203: error: expected statement at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:194: warning: unused variable ‘first’
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:203: error: expected ‘}’ at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:203: warning: no return statement in function returning non-void
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp: In static member function ‘static std::string opencc::UTF8Util::Join(const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’:
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:210: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:213: error: expected primary-expression before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:213: error: expected ‘;’ before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:213: error: expected primary-expression before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/UTF8Util.hpp:213: error: expected ‘)’ before ‘return’
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:23,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/Dict.hpp:22,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/SerializableDict.hpp:21,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.hpp:22,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:19:
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp: In constructor ‘opencc::Segments::Segments(std::initializer_list<const char*>)’:
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:33: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:36: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:36: error: expected ‘;’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:36: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:36: error: expected ‘)’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:36: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:36: error: expected ‘;’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp: In constructor ‘opencc::Segments::Segments(std::initializer_list<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >)’:
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:39: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:42: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:42: error: expected ‘;’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:42: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:42: error: expected ‘)’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:42: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:42: error: expected ‘;’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp: In member function ‘std::string opencc::Segments::ToString() const’:
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:98: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:101: error: expected primary-expression before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:101: error: expected ‘;’ before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:101: error: expected primary-expression before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/Segments.hpp:101: error: expected ‘)’ before ‘return’
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/Dict.hpp:22,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/SerializableDict.hpp:21,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.hpp:22,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:19:
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp: In constructor ‘opencc::StrMultiValueDictEntry::StrMultiValueDictEntry(const std::string&, const std::vector<const char*, std::allocator<const char*> >&)’:
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:131: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:134: error: expected ‘;’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:134: error: expected ‘)’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:134: error: expected ‘;’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp: In member function ‘virtual std::vector<const char*, std::allocator<const char*> > opencc::StrMultiValueDictEntry::Values() const’:
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:144: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:147: error: expected primary-expression before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:147: error: expected ‘;’ before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:147: error: expected primary-expression before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/DictEntry.hpp:147: error: expected ‘)’ before ‘return’
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:20:
/home/zhangdavy/Documents/lib/OpenCC/src/Lexicon.hpp: In destructor ‘opencc::Lexicon::~Lexicon()’:
/home/zhangdavy/Documents/lib/OpenCC/src/Lexicon.hpp:34: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Lexicon.hpp:37: error: expected ‘;’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Lexicon.hpp:37: error: expected ‘)’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/Lexicon.hpp:37: error: expected ‘;’ before ‘}’ token
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp: In member function ‘size_t opencc::BinaryDict::KeyMaxLength() const’:
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:26: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:29: error: expected ‘;’ before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:29: error: expected ‘)’ before ‘return’
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp: In member function ‘virtual void opencc::BinaryDict::SerializeToFile(FILE*) const’:
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:49: error: expected initializer before ‘:’ token
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:179: error: expected primary-expression at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:179: error: expected ‘;’ at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:179: error: expected primary-expression at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:179: error: expected ‘)’ at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:179: error: expected statement at end of input
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:48: warning: unused variable ‘keyCursor’
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:48: warning: unused variable ‘valueCursor’
/home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:179: error: expected ‘}’ at end of input
make[2]: *** [src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/libopencc.dir/all] Error 2
make: *** [all] Error 2

$ gcc --version
gcc (GCC) 4.7.2 20121015 (Red Hat 4.7.2-5)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ clang --version
clang version 3.7.0 (trunk 228844)
Target: x86_64-unknown-linux-gnu
Thread model: posix

clang and gcc is my own build, cause it doesn't ship with default

gcc from 
$ which gcc
/opt/centos/devtoolset-1.1/root/usr/bin/gcc

clang from llvm build

**Comment by davyzhang** [comment]
centos info:

Description:	CentOS release 6.3 (Final)
Release:	6.3
Codename:	Final

$ echo $CXX
/usr/bin/clang++

**Comment by davyzhang** [comment]
$ make VERBOSE=1
/usr/bin/cmake -H/home/zhangdavy/Documents/lib/OpenCC -B/home/zhangdavy/Documents/lib/OpenCC --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/zhangdavy/Documents/lib/OpenCC/CMakeFiles /home/zhangdavy/Documents/lib/OpenCC/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/zhangdavy/Documents/lib/OpenCC'
make -f src/CMakeFiles/libopencc.dir/build.make src/CMakeFiles/libopencc.dir/depend
make[2]: Entering directory `/home/zhangdavy/Documents/lib/OpenCC'
cd /home/zhangdavy/Documents/lib/OpenCC && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/zhangdavy/Documents/lib/OpenCC /home/zhangdavy/Documents/lib/OpenCC/src /home/zhangdavy/Documents/lib/OpenCC /home/zhangdavy/Documents/lib/OpenCC/src /home/zhangdavy/Documents/lib/OpenCC/src/CMakeFiles/libopencc.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/zhangdavy/Documents/lib/OpenCC'
make -f src/CMakeFiles/libopencc.dir/build.make src/CMakeFiles/libopencc.dir/build
make[2]: Entering directory `/home/zhangdavy/Documents/lib/OpenCC'
/usr/bin/cmake -E cmake_progress_report /home/zhangdavy/Documents/lib/OpenCC/CMakeFiles 20
[  2%] Building CXX object src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o
cd /home/zhangdavy/Documents/lib/OpenCC/src && /usr/bin/c++   -DLOCALEDIR=\"/usr/share/locale/\" -DPACKAGE_NAME=\"opencc\" -DPKGDATADIR=\"/usr/share/opencc/\" -DVERSION=\"1.0.2\" -Dlibopencc_EXPORTS -fPIC -I/home/zhangdavy/Documents/lib/OpenCC/src/../deps/darts-clone -I/home/zhangdavy/Documents/lib/OpenCC/src/../deps/rapidjson-0.11 -I/home/zhangdavy/Documents/lib/OpenCC/src/../deps/tclap-1.2.1    -std=c++0x -Wall -o CMakeFiles/libopencc.dir/BinaryDict.cpp.o -c /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/Common.hpp:42,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.hpp:21,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:19:
/home/zhangdavy/Documents/lib/OpenCC/src/Exception.hpp:43: error: expected ‘;’ before ‘noexcept’
/home/zhangdavy/Documents/lib/OpenCC/src/Exception.hpp:45: error: expected ‘;’ before ‘protected’

**Comment by davyzhang** [comment]
also tried 
$ alias cmake="cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"
$ make
[  2%] Building CXX object src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/Common.hpp:42,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.hpp:21,
                 from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:19:
/home/zhangdavy/Documents/lib/OpenCC/src/Exception.hpp:43: error: expected ‘;’ before ‘noexcept’
/home/zhangdavy/Documents/lib/OpenCC/src/Exception.hpp:45: error: expected ‘;’ before ‘protected’

ran out of ideas :cry:

**Comment by davyzhang** [comment]
I add these lines to CMakeLists.txt, finally it use clang to compile,

    SET (CMAKE_C_COMPILER             "/usr/local/bin/clang")
    SET (CMAKE_C_FLAGS                "-Wall -std=c99")
    SET (CMAKE_C_FLAGS_DEBUG          "-g")
    SET (CMAKE_C_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
    SET (CMAKE_C_FLAGS_RELEASE        "-O4 -DNDEBUG")
    SET (CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g")

    SET (CMAKE_CXX_COMPILER             "/usr/local/bin/clang++")
    SET (CMAKE_CXX_FLAGS                "-Wall -v -stdlib=libc++")
    SET (CMAKE_CXX_FLAGS_DEBUG          "-g")
    SET (CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
    SET (CMAKE_CXX_FLAGS_RELEASE        "-O4 -DNDEBUG")
    SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g")

    SET (CMAKE_AR      "/usr/local/bin/llvm-ar")
    SET (CMAKE_LINKER  "/usr/local/bin/llvm-ld")
    SET (CMAKE_NM      "/usr/local/bin/llvm-nm")
    SET (CMAKE_OBJDUMP "/usr/local/bin/llvm-objdump")
    SET (CMAKE_RANLIB  "/usr/local/bin/llvm-ranlib")

but I still get errors:
clang -cc1 version 3.7.0 based upon LLVM 3.7.0svn default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/zhangdavy/Documents/lib/OpenCC/src/../deps/darts-clone
 /home/zhangdavy/Documents/lib/OpenCC/src/../deps/rapidjson-0.11
 /home/zhangdavy/Documents/lib/OpenCC/src/../deps/tclap-1.2.1
 /usr/local/include
 /usr/local/bin/../lib/clang/3.7.0/include
 /usr/include
End of search list.
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.cpp:19:
In file included from /home/zhangdavy/Documents/lib/OpenCC/src/BinaryDict.hpp:21:
/home/zhangdavy/Documents/lib/OpenCC/src/Common.hpp:26:10: fatal error: 'algorithm' file not found

$ls -l
/usr/include/c++/4.7.2 -> /opt/centos/devtoolset-1.1/root/usr/include/c++/4.7.2

Sorry I don't really familiar with make/makefile,

**Comment by BYVoid** [comment]
It seems that your compiler doesn't support keyword `noexcept`.

Could you please try to compile the code here? http://stackoverflow.com/questions/18039709/error-expected-before-noexcept

**Comment by davyzhang** [comment]
The noexcept error is fixed by using newer version of gcc and force it to use clang++ to compile in cmake files.

The lastest error is 'algorithm' file not found

Can you compile opencc on centos 6.x version?

**Comment by BYVoid** [comment]
This error doesn't make sense to me. Every C++ compiler should has a copy of STL headers. It seems that your system compiler is corrupted.

**Comment by davyzhang** [comment]
Maybe the home build version of gcc and clang get some issues, but can you try to build opencc on centos6, and shed some light on this system? Maybe a prebuilt binary ?I would really appreciate that, I know it currently not on your target system list, but centos is a widely used server system, support this platform can make opencc a great tool for automated publish processes, Thanks for your time, you can close this now.
